### ISSUE TITLE
[Jupiter] Display graduation date in "Fall 2017" format

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#1003]
With agreement from FGSR and Leah, we'd like to display the graduation date field for theses in the "Fall 2016" format rather than the current "2016-11" format. The underlying data will still use "2016-11", so it won't be changed. The edit form for theses also does not need to change (since it is only used by admin users). The change applies only to search results and full item displays. OAI is out of scope. 

The graduation_date field is normalized to YYYY-MM, with MM = 06 or 11. This should map to "Spring YYYY" when the MM is 06, and "Fall YYYY" when the MM is 11. Fall back to just YYYY for any other value of MM or when MM is absent.

Related to #798. Weiwei has reviewed email discussion of that issue at the time to clarify some of the history.

**Comment by weiweishi** [comment]
The original requirements on the deposit form will remain unchanged - consider this as a new requirement, for public interface.

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/jupiter/blob/e797c4f9961bff205e5482c190f884102db9a6c2/app/views/items/_thesis.html.erb#L40

https://github.com/ualbertalib/jupiter/blob/e797c4f9961bff205e5482c190f884102db9a6c2/app/helpers/items_helper.rb#L24-L40

Here's how the deposit side is mapped to 'Spring' 'Fall'
https://github.com/ualbertalib/jupiter/blob/e797c4f9961bff205e5482c190f884102db9a6c2/app/models/draft_thesis.rb#L5-L12
https://github.com/ualbertalib/jupiter/blob/e797c4f9961bff205e5482c190f884102db9a6c2/app/models/draft_thesis.rb#L48-L49
https://github.com/ualbertalib/jupiter/blob/e797c4f9961bff205e5482c190f884102db9a6c2/app/models/draft_thesis.rb#L160-L164
