### ISSUE TITLE
Batch Ingest Sivakoff

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1006]
**Brief description of the batch**
New batch for Sivakoff.

**Manifest**
https://docs.google.com/spreadsheets/d/1-RoVK0t7sJ34DiuSvQ8ciGYXqRhfnhxHMat4n6HzmnA/edit#gid=0

**Batch files**
https://drive.google.com/drive/folders/1GibeuUR5gT3FHx6uK5f4ol0S9U_Zr_LG

**Comment by anayram** [comment]
Batch files available from
https://drive.google.com/drive/folders/1YP-dZq_T81RqiFSfKjkNAKynbPZABCNr?usp=sharing
(link open to specific users only)

**Comment by dancockcroft** [comment]
@anayram This batch isn't quite ready for ingest, I'll re-add the 'batch ingest ready' label when it's ready to go.

**Comment by anayram** [comment]
@dancockcroft - my mistake, this comment was meant for an avalon batch ingest, not this one.

thanks!

**Comment by dancockcroft** [comment]
@weiweishi Tested and ready for ingest.

**Comment by dancockcroft** [comment]
One license ported to 4.0.

**Comment by dancockcroft** [comment]
Manually deposited.
