### ISSUE TITLE
Add missing indexes to DB

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1007]
**Is your feature request related to a problem? Please describe.**
Found https://github.com/plentz/lol_dba which scans your application models and displays a list of columns that probably should be indexed. It has a suggestion for us.

**Describe the solution you'd like**
$ lol_dba db:find_indexes

* TIP: if you have a problem with the index name('index name too long') you can solve with the :name option. Something like :name => 'my_index'.
* run `rails g migration AddMissingIndexes` and add the following content:

    class AddMissingIndexes < ActiveRecord::Migration
      def change
        add_index :active_storage_attachments, [:active_storage/blob_id, :draft_item_id]
        add_index :active_storage_attachments, [:active_storage/blob_id, :draft_thesis_id]
        add_index :active_storage_attachments, [:active_storage/blob_id, :jupiter_core/attachment_shim_id]
      end
    end

**Comment by pgwillia** [comment]
Thanks for looking into this.  It's not a useful hint so I'll close.

**Comment by murny** [comment]
Yeah its a cool tool, but I think it gets a bit confused with how it traces through the rails model in terms of how active storage behaves. 

But good idea though and thanks for opening a ticket! :+1:
