### ISSUE TITLE
Batch ingest Worrall

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1021]
**Brief description of the batch**
New publications from Dr. Worrall.

**Manifest**
https://docs.google.com/spreadsheets/d/16QwN-7V82EQ5HUyxpyD19bhIyjIFwaBhG9P69b7bTZY/edit#gid=0

**Batch files**
https://drive.google.com/drive/folders/1ko4iMw61HY1OySa3Fcu_rk_G12ieXWrD

**Additional notes**
The copyright license for one item could not be found.

**Comment by dancockcroft** [comment]
@weiweishi Ready for ingest.

**Comment by weiweishi** [comment]
completed. batch ingest report:
https://docs.google.com/document/d/1-UAhSbI8-_ySqmspREGAFSSRp385yVvL2TokcqvN18s/edit
