### ISSUE TITLE
Recover Jupiter Triplestore

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1050]
Our current GraphDB triplestore has been down since the December incident. @piyapongch needs to work with @henryzhang87  to recover the triplestore.

**Comment by sfarnel** [comment]
@weiweishi can you confirm access details with @anayram and @danydvd as we do not seem to have access and are wondering if we have the correct information. Thanks!

**Comment by weiweishi** [comment]
Hi Sharon, this is closed because Peter has created a separate ticket in
DI_internal https://github.com/ualbertalib/di_internal/issues/58. The work
is still ongoing and you can see this ticket on the project board. We will
document the details once the work is actually completed.

Weiwei


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by sfarnel** [comment]
Thanks @weiweishi
