### ISSUE TITLE
chromedriver-helper is deprecated after 2019-03-31. 

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1057]
Please update to use the 'webdrivers' gem instead.
See flavorjones/chromedriver-helper#83

chromedriver-helper would download the latest webdriver so that the tests just worked on travis. It doesn't look like the suggested replacement will do this for us ualbertalib/discovery#1574

**Comment by ConnorSheremeta** [comment]
Webdriver now downloads the latest driver just like chromedriver-helper. Some workarounds needed for VCR though
