### ISSUE TITLE
Batch ingest SLIS

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1059]
**Brief description of the batch**
Leftover items from previous investigation.

**Manifest**
https://docs.google.com/spreadsheets/d/1kgdLE3HV6lGtX5tlfC_mcH-dtlO-bNKXnnN6CVsWslU/edit#gid=0

**Batch files**
https://drive.google.com/drive/folders/1mTLyE6ys-r4bgyOQDFF4_ZadWCLpNRp9

**Comment by dancockcroft** [comment]
@weiweishi Tested and ready for ingest.

**Comment by weiweishi** [comment]
completed: report is at:
https://docs.google.com/document/d/1c30Em0yNOKMpTMyKuyE7QLddJlVEUUq59GsxVrVGx_M/edit
