### ISSUE TITLE
2018 theses with date submitted beginning '0018' instead of '2018'

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#1061]
WIP - @anayram is still investigating. This issue is a place to track the problem.

While investigating an [OAI issue](https://github.com/ualbertalib/fcrepo4-oaiprovider/issues/48) Peter found that [a 2018 thesis](https://era.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=oai_etdms&identifier=oai:era.library.ualberta.ca:4eb7bf99-a9d8-41de-82ea-f3f3d677b1dc) was showing its ```etd_ms:date``` field as ```0018-07-17T00:00:00.000Z```. @anayram investigated and found 662 items (all with model "IRThesis") in the Solr index that have a field ```date_submitted_ssim``` with the year ```0018```. 

This may turn out to be a bug in the ingest process that pulls dissertations from Alfresco into ERA. If so, we'll want to fix it before the next ingest job.

**Comment by anayram** [comment]
Corrected dates and info to clean this up available at https://drive.google.com/file/d/0B-wPdqHEduXteWt3a3Z1bC1tY2Q4Ync3ZURuN1NpWVFzWjJV/view?usp=sharing

**Comment by pbinkley** [comment]
I've finished the updates to the date_submitted and date_accepted fields. @anayram please have a look, and we can close this issue. I notice that the last item in the worksheet (7ccbbfa3-e30c-4cd4-a85f-26f25cdbca3b) has no new date_submitted and date_accepted values, and the object in Fedora has no values either; I haven't looked into the history of this object.

**Comment by anayram** [comment]
Thanks @pbinkley. Dates look good now.

I am closing this ticket and will follow up separately on the items lacking date_submitted an date_accepted.
