### ISSUE TITLE
Batch ingest Birchall_Postprints

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1065]
**Brief description of the batch**
Brand new batch for Birchall

**Manifest**
https://docs.google.com/spreadsheets/d/1D2ZAhXwx_-eb_3GFPNDtyH54PfcyE9s8Bz3PExQbho0/edit#gid=0

**Batch files**
https://drive.google.com/drive/folders/1vFizjzG29FeA29-xWLNb68dZRO4ZkR_5

**Additional notes**
Note the very distant embargo dates.

**Comment by dancockcroft** [comment]
@weiweishi Ready for ingest.

**Comment by weiweishi** [comment]
completed. 

report is here:

id,url,title
b771b160-8e02-4042-bea1-25a5a2db2876,https://era.library.ualberta.ca/items/b771b160-8e02-4042-bea1-25a5a2db2876,Designing public open space to support seismic resilience: A systematic review
d3aa3a3f-8264-4b6d-87c0-dd1dd24f5357,https://era.library.ualberta.ca/items/d3aa3a3f-8264-4b6d-87c0-dd1dd24f5357,"Local-scale climate change stressors and policy response: the case of Homer, Alaska "
c2ce7f50-5c83-45f5-bf2f-9fccb0995428,https://era.library.ualberta.ca/items/c2ce7f50-5c83-45f5-bf2f-9fccb0995428,Climate Change Impacts and Resilience: An Arctic Case Study
f13e8ac2-8db2-4591-99f7-5bcacf499295,https://era.library.ualberta.ca/items/f13e8ac2-8db2-4591-99f7-5bcacf499295,Financial market services: Climate finance and climate change adaptation
34b56fe3-0caf-49fd-9036-837a8eb87797,https://era.library.ualberta.ca/items/34b56fe3-0caf-49fd-9036-837a8eb87797,Vulnerable communities: The need for local-scale climate change adaptation planning
fc1811c2-da4e-4c8b-a4f4-1457994fea02,https://era.library.ualberta.ca/items/fc1811c2-da4e-4c8b-a4f4-1457994fea02,Community planning opportunities: Building resilience to climate variability using coastal naturalisation
708ab5da-a8e4-4e4f-b358-9c097350d6e5,https://era.library.ualberta.ca/items/708ab5da-a8e4-4e4f-b358-9c097350d6e5,Climate change planning: Understanding policy frameworks and financial mechanisms for disaster relief
086d29fa-fda2-4b10-b090-e75cb23b0551,https://era.library.ualberta.ca/items/086d29fa-fda2-4b10-b090-e75cb23b0551,An Investigation into the early stages of New Zealand’s Voluntary Carbon Market
