### ISSUE TITLE
Batch ingest Anthropology Collection 

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/jupiter#1104]
**Brief description of the batch**
The Bryan/Gruhn Anthropology Collection

**Manifest**
[https://drive.google.com/file/d/1y8m-vfURqwFtLe7s671zIFvGKNkEq7R3/view?usp=sharing](https://drive.google.com/file/d/1y8m-vfURqwFtLe7s671zIFvGKNkEq7R3/view?usp=sharing)

**Batch files**
The files are too large and will be provided on an external HDD

**Comment by weiweishi** [comment]
@danydvd this url to the manifest file on google drive doesn't seem to work?

**Comment by danydvd** [comment]
Sorry @weiweishi url is fixed.

**Comment by leahvanderjagt** [comment]
Opening this issue. The campus contact for this collection has asked for an estimate date for when these data can be loaded to ERA. Can we proceed with this batch ingest soon? If yes, what date do we estimate? There will be many thousands of files and a lot of data, so we should probably alert @henryzhang87 and schedule the batch. @weiweishi , thoughts?

**Comment by seanluyk** [comment]
Manifest and files now in the Repositories shared drive. Project is documented [in Trello](https://trello.com/c/29e52B8P) so closing this issue.
