### ISSUE TITLE
Batch ingest Lewis

### ISSUE THREAD

**Issue by mmstang** [ualbertalib/jupiter#1107]
**Brief description of the batch**
Batch ingest of green clearance articles for Lewis.

**Manifest**
https://docs.google.com/spreadsheets/d/1dMU2sH8bQJt5hmU4Qo-lItj13SiniYTX_k9tiVcP3mI/edit#gid=0

**Batch files**
https://drive.google.com/drive/folders/14_yKoPc8iDbKH9x_gRxMesnYswjvI2ln

**Comment by dancockcroft** [comment]
Manually deposited.
