### ISSUE TITLE
Batch ingest doesn't take older licenses

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1115]
**Describe the bug**
Batch ingest failed because it errored out on validating licenses for anything that's not on this list:
https://github.com/ualbertalib/jupiter/blob/master/config/controlled_vocabularies/license.yml

**Expected behavior**
 we should be able to batch ingest with older licenses:
https://github.com/ualbertalib/jupiter/blob/master/config/controlled_vocabularies/old_license.yml
**Example batch**
https://github.com/ualbertalib/jupiter/issues/1088

**Comment by pgwillia** [comment]
Looks like there is already a test for this: https://github.com/ualbertalib/jupiter/blob/fdd3dad51ae8323184e1249f249574eb1a290e1a/test/models/item_test.rb#L211-L223

**Comment by pgwillia** [comment]
And we seed data from this list too https://github.com/ualbertalib/jupiter/blob/fdd3dad51ae8323184e1249f249574eb1a290e1a/db/seeds.rb#L139

Asked for access to the batch to investigate further.

**Comment by pgwillia** [comment]
It looks like the ingest script only accounts for the one https://github.com/ualbertalib/jupiter/blob/fdd3dad51ae8323184e1249f249574eb1a290e1a/lib/tasks/batch_ingest.rake#L120

**Comment by mbarnett** [comment]
Looks like the work related to this is already merged. Closing (re-open if I'm wrong).
