### ISSUE TITLE
Bring in StyleLint NPM package

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1120]
https://github.com/ualbertalib/discovery/blob/1b1904c69d07ef1528f48b3862fece839e2274d9/Gemfile#L50

>The Sass core team is now building Sass in Dart instead of Ruby, and will no longer be maintaining the Ruby implementation unless a maintainer steps up to help. Since the SCSS-Lint project relies on the Ruby Sass implementation, this means it will eventually not support the latest Sass features and bug fixes.

>Two alternatives worthy of consideration are stylelint and sass-lint, with sass-lint having closer feature parity to SCSS-lint.

**Comment by murny** [comment]
We are now on Webpacker, I have removed SCSS LInt gem. But we should bring in something like Stylelint from NPM.

More info: https://stylelint.io/

**Comment by murny** [comment]
Jupiter is now using stylelint.io so we can now close this.
