### ISSUE TITLE
[Jupiter]500 Error when facet by type image

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#1129]
**Describe the bug**
When attempting to facet across all ERA items by type Image, a 500 error is returned.

**To Reproduce**
1. Go to ERA home page
2. Click on Search to retrieve all items
3. Scroll down to Item Type Filter
4. Click on Image
5. A 500 error is returned

**Expected behavior**
One would expect a result list of all ERA items of type Image.

**Screenshots**
![image](https://user-images.githubusercontent.com/4697932/57400025-c4f28180-718f-11e9-9d34-93a558097acc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser and Version: Chrome Version 74.0.3729.131 (Official Build) (64-bit), Firefox Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by pgwillia** [comment]
I did a little investigation.  There is an item with an image that's "not an image".  I'm not sure which item it is, but rollbar could help us triangulate. https://rollbar.com/ualbertalib/jupiter/items/647/?item_page=1&#instances

**Comment by pgwillia** [comment]
Can use [search.json](https://era.library.ualberta.ca/search.json?facets[item_type_with_status_sim][]=image&search=) to help narrow down.

It's this one! https://era.library.ualberta.ca/items/f1c4404a-f946-4077-8356-572b5cc10b0a

**Comment by sfarnel** [comment]
Interesting; thanks @pgwillia! Interestingly, if you try and navigate to the Halpern collection (which this item is from) you get the same error, so it must be that image. @pbinkley @weiweishi is there any way to see if we can get the object from OpenStack to see if it's corrupted? The original dvds may be in the vault if we need to go that far back.

**Comment by pbinkley** [comment]
the [file](http://localhost:8090/fedora/rest/prod/23/04/2f/38/23042f38-c5be-4159-83a4-183766576614/files/386e8920-c46a-4566-80fe-6c8bea2afb37/fcr:fixity) is not a jpeg. 

```
$ identify 87_102c.jpg 
identify: Not a JPEG file: starts with 0xef 0xbf `87_102c.jpg' @ error/jpeg.c/JPEGErrorHandler/340.
```

I'll see if we have a good copy in Swift.

**Comment by pbinkley** [comment]
I've confirmed that the file in the old Fedora 3 repo (wolves) has the same SHA1 checksum as the file in Jupiter (48c88c0c7638cfb5de2cdd2dde76b98b33ad0e52), so it must have been corrupt when we got it.

**Comment by pbinkley** [comment]
Conclusion: we need a new image from source.

**Comment by mbarnett** [comment]
actual crashes are at long last fixed, tracking the possibility of getting a non-corrupt copy of that file over on #898
