### ISSUE TITLE
[Jupiter]Thumbnail not available

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1133]
It could be because the first item is video (https://era.library.ualberta.ca/items/b4d04116-334a-4374-98a6-d2bbc450636b), or that the pdf is damaged in some way (https://era.library.ualberta.ca/items/bd23ff2c-c36d-43d2-be7b-1b3714ff92c0). 

For each of the "Occurences" in the rollbar issue, scroll to the end of the `request.url` and search for the clues from the file name.  For example `damavandi_babak_spring2012.pdf` could search for "Damavandi Babak"

View details in Rollbar: [https://rollbar.com/ualbertalib/jupiter/items/645/](https://rollbar.com/ualbertalib/jupiter/items/645/)

**Comment by ConnorSheremeta** [comment]
@pgwillia I'm having a hard time determining what this issue is asking for. Is it to investigate the different reasons why the thumbnail isn't available? Is it to create a fix so that the thumbnail show's the fallback image in these cases? Something else?

**Comment by pgwillia** [comment]
My intention with this issue is to investigate the Rollbar errors grouped by  https://rollbar.com/ualbertalib/jupiter/items/645/.  

The ultimate goal is so that the 'MiniMagick::Invalid' errors stop occurring but there are many reasons this error could occur. I think we need to know what these are and then create issues for a proposed fix for each type.

**Comment by ConnorSheremeta** [comment]
After investigating many occurrences of this error in rollbar, by either tracking down the item through the request.headers.Referer column or searching by clues in the filename, it appears that this error occurs whenever there is an attempt to load a thumbnail of a broken file (PDF or video.) The only way to get these errors to stop occurring would be to remove/fix those broken files which is currently being done in issue #. There could be better handling of broken images where an [alternative image is loaded on error](https://stackoverflow.com/questions/39884691/rails-load-default-image-if-image-tag-cannot-load-image-from-url). This would allow us to display a broken file icon which would look better visually.

**Comment by weiweishi** [comment]
This is good practice. I have just discovered, when going through the occurrences in rollbar, an object with a password protected pdf file - https://era.library.ualberta.ca/items/c4c749ad-77af-4646-be77-8ac8b349b48f, although the visibility is set to be open access. We can't stop users to upload such files, but to present a generic thumbnail image makes sense.
