### ISSUE TITLE
St. Stephen's Theses in incorrect Collections

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1143]
@weiweishi @leahvanderjagt 

Shelley Westermann has requested we move the following theses from the Grad Studies community / Theses and Dissertations collection. ERA railroads us into this community/collection because it's a thesis deposit. Could you please manually move these items?

To be moved to the Department of Psychotherapy and Spirituality (St. Stephen's College) collection (5c8c183b-6b68-405a-8245-0eab5ec37d4b):

Aita, Joyce: https://era.library.ualberta.ca/items/fa5aad6d-c5c6-472c-8bdf-8f1c2932ab74
Cheung, Cecilia: https://era.library.ualberta.ca/items/8e3f17b3-f580-497a-893e-73c921112d61
Dauphinee, Cate: https://era.library.ualberta.ca/items/28d9417a-4f55-4992-b5a3-b8aa1b1d6794
Foster, Laura David: https://era.library.ualberta.ca/items/b5357307-5c61-46a5-a28f-9291fba04a2d
Way, Brian David: https://era.library.ualberta.ca/items/90f4c222-e1f6-4207-87f9-10fc5c771d1f
Mearon, Joyce: https://era.library.ualberta.ca/items/079283f4-3644-4320-8151-a4ffedd2b7c9

To be moved to the Department of Theology DMin (St. Stephen's College) collection (f4e29217-73a9-4d29-9929-d9110e4c0bc4):

Gatera, Emmanuel: https://era.library.ualberta.ca/items/8365710b-84a9-4b38-9045-bd07a15817c0

**Comment by dancockcroft** [comment]
In the meantime, a new batch for 2018 theses was requested. Given how few there were and the fact this issue was still open, I felt it was best to manually deposit these items and change the communities/collections at once.

To be moved to the Department of Theology DMin (St. Stephen's College) collection:

Salomons, Wenda Annette: https://era.library.ualberta.ca/items/b02a82e0-ac48-4679-a044-b3e55d2d0168
Doucet, Marc Gerard: https://era.library.ualberta.ca/items/31ba1e9a-d097-4075-8993-6321b2c6be5f
Ichwan, Juswantori: https://era.library.ualberta.ca/items/eb8c0c0d-cf0c-4c7e-bd03-5e96f79b8a27
Krumins, Norbert Michael: https://era.library.ualberta.ca/items/f16f9757-72a1-47fe-989d-3e5db8b9ef55


To be moved to the Department of Psychotherapy and Spirituality (St. Stephen's College) collection:

Crichton, Joel, A.: https://era.library.ualberta.ca/items/3b31a9f2-2f47-448c-a60f-b04dbf71907c
Gelink, Lorian Nicole: https://era.library.ualberta.ca/items/553cda41-a3fa-4c6a-a969-f21845297d38

**Comment by weiweishi** [comment]
@dancockcroft I have made the changes to the several collections for St. Stephen's so they appear for admins as community/collections that a thesis can be deposited into. Do you mind making the changes to the individual thesis to reflect the changes you'd like? Thanks and sorry for the delay.

**Comment by dancockcroft** [comment]
@weiweishi Will do, thank you!
