### ISSUE TITLE
By default list communities and collections A-Z by title

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#115]
In all admin and browse views, sort communities by title (a-z). 
Sort collections listed under communities by title. 

Applies to:
-manage communities and collection pages (admin/communities_and_collections)
-community detail pages(communities/XXXX)
-community browse(/communities)

**Comment by mbarnett** [comment]
We're changing these pages to present a search-driven (ie. have facetable browse pages), so this impacts the search sort order. Moving to Search epic.

**Comment by weiweishi** [comment]
And I believe this is completed.
