### ISSUE TITLE
Batch ingest Dentistry Teaching Images

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1158]
**Brief description of the batch**
Batch of images for dentistry project. 

**Manifest**
https://docs.google.com/spreadsheets/d/1F4uDHCVVKSJrQBghYHgcT5pkMzb5gJh27vjNb3blnWI/edit#gid=0

**Batch files**
https://drive.google.com/drive/folders/1ekgHb-G9hBni1hmvExs7VKdlYjShcUCr

**Comment by dancockcroft** [comment]
Several licenses ported to 4.0.

**Comment by dancockcroft** [comment]
Priority.

**Comment by weiweishi** [comment]
@dancockcroft this is completed. Several things to note:
2 objects failed to load:
- line 26 license is: attribution_noderivs_2_0_generic
- line 32 it has both a license and right statement. 

and 'attribution_4_0_sharealike_international' should be 'attribution_sharealike_4_0_international'

You might need to look into the two items there were failed to be ingested. 

Sorry for the delay on this.

**Comment by dancockcroft** [comment]
Thank you! 

- line 26 ported to 4.0 
- line 32 fixed
