### ISSUE TITLE
Hard to "Add collection" to existing communities

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#117]
Users had trouble adding a new collection to an existing community because "Add new collection" is only on community detail page. Users have to click on admin --> manage communities and collections--> Edit --> Update community to get to "Add collection" (or go to Community Browse --> Community name while logged in)

Recommend either:

a) Add "Add collection" button beside "Collections v" button in list of communities on "Manage Communities & Collections" Page (will require resizing of buttons so everything fits in a nice row, OR
b) Add an "Add community" page in dashboard menu like wireframe: https://jupiter.mybalsamiq.com/mockups/6003451.png (would require adding community dropdown menu to "Add collection" form.

**Comment by mbarnett** [comment]
Do you have a preference between A & B? My inclination is towards A (it's slightly less work), but we could do either.

**Comment by sfbetz** [comment]
No preference. Go with easier!

**Comment by mbarnett** [comment]
![You got it dude](http://media.riffsy.com/images/74a52684ad211b0fb3466f7457a64ace/tenor.gif)

**Comment by cwant** [comment]
Fixed via PR #155
