### ISSUE TITLE
Problem with Medical Laboratory Image metadata - inconsistent name order

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#1176]
**Describe the bug**
Author/Creator/contributor when added by end user is first name last name, and those batch ingested ended up as last name, first name. 

1. Go to the collection page (https://era.library.ualberta.ca/communities/f7766168-d234-491a-b27c-2c4a5eecbc99/collections/f1cfc1bb-3601-40b2-92c5-646b4162e3e5)
2. Look at the author/creator/contributor limiters on the left
3. See the inconsistencies

**Expected behavior**
These should be cleaned up so they are all consistently in one format (last name, first name).

On Windows using Chrome

The researcher is eagerly awaiting these fixes so he can showcase the collection and the service (which he is super excited about).

**Comment by weiweishi** [comment]
@sfarnel I can clean up the data on the batch, but looking at the batch ingest manifest, https://docs.google.com/spreadsheets/d/1ZrTS4ah1gO8SMnM-msIWtGizeJlE527w-SfTzcGux14/edit#gid=0 for author/creator/contributor. I think that is how the data was presented. I will see if a student could help me clean up the data and I can run a batch update.

**Comment by sfarnel** [comment]
Thanks @weiweishi The inconsistency came from images entered into ERA through the UI while we waited for batch ingest to be ready. What we need is to make the values consistent across the whole collection and so I wondered if that could be done via a batch process or if it needed to be done through the UI.

**Comment by weiweishi** [comment]
@sfarnel This can definitely be done as a batch. I can pull all the data from the back end, and see if we need any manual work that could use a half hour from a student to check the consistency of all the data, before I run the batch update. I will get the data first this morning, and let's go from there.

**Comment by sfarnel** [comment]
Fantastic; thanks @weiweishi

**Comment by weiweishi** [comment]
@sfarnel was able to clean the data on ERA. Closing.
