### ISSUE TITLE
 [Jupiter] Fix and re enable flapping tests

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#1182]
Those tests in #1181 that are skipped, along with a couple other skipped tests, should be fixed and re-enabled.

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/jupiter/pull/1231/commits/29bd4d2ea07a55801107fa7969028e7d4b62052c may have addressed some of these.

**Comment by mbarnett** [comment]
Closing since I believe this is done (feel free to reopen if etc)
