### ISSUE TITLE
Remove Community and Collection labels from titles

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#119]
Community and Collection detail pages include the collection and community label in the titles: eg here: http://arsenal.library.ualberta.ca/communities/bcd8194d-2c49-4274-905b-634a59e6125c/collections/e8a6cf2d-3b75-46a2-9c24-13b1d0cec8c3

**"Collection:** Presentations (Agricultural, Life & Environmental Sciences)" - This can come out so the title reads "Presentations (Agricultrual, Life & Environmental Sciences)" 

Same for communities.

**Comment by cwant** [comment]
@sfbetz Should I infer that you also want the "Item:" labels removed from the page headers on the item detail pages?

**Comment by sfbetz** [comment]
Yes please! Didn't see those.

**Comment by cwant** [comment]
Merged via PR #134
