### ISSUE TITLE
[Jupiter] Thumbnails overflowing their div

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#1196]
**Describe the bug**
On an item page with a thumbnail, either viewing or uploading, the thumbnail will overflow it's div at a certain width. Adding 'w-100' to the image should do the trick.

**Screenshots**
![Screenshot from 2019-07-10 16-25-12](https://user-images.githubusercontent.com/14242562/61009308-7ef0a000-a32f-11e9-86b1-55b6e238e7ff.png)
![Screenshot from 2019-07-10 16-22-27](https://user-images.githubusercontent.com/14242562/61009309-7ef0a000-a32f-11e9-9348-06717944aa66.png)

**Comment by pgwillia** [comment]
Seems to have been fixed

![image](https://user-images.githubusercontent.com/1220762/143939421-66cec8de-6433-4b7d-8a2b-d61e5beafeff.png)
![image](https://user-images.githubusercontent.com/1220762/143939511-ed1024f5-06eb-47d8-8fa5-de65837739c6.png)
