### ISSUE TITLE
Define Accessibility & Design Principles

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#12]

**Comment by weiweishi** [comment]
This investigation work has resulted in the creation of the following documents:

- [DI Web Application Design Principles](https://docs.google.com/document/d/11ZAFAij9LivFZVRgOfR5AQmgDRrCpkltHMXbtWPGDaQ/edit?usp=sharing)

- [Jupiter: Design Principles](https://docs.google.com/document/d/10Zt-Fod4lG35yEMumCwemb5y7cyX5gjjeE3VpjWT29E/edit?usp=sharing)

The [Jupiter: Design Principles](https://docs.google.com/document/d/10Zt-Fod4lG35yEMumCwemb5y7cyX5gjjeE3VpjWT29E/edit?usp=sharing) is sourced from the former document and is now open for review/comments.

**Comment by mbarnett** [comment]
I think we can call this done, unless there are any objections

**Comment by weiweishi** [comment]
And the checklist for accessibility testing during different stages is at:
https://docs.google.com/document/d/1tYmw3mn7vDEuI8uFMtXrTX3-SyB40II6OhQgHXH4O2I/edit
