### ISSUE TITLE
Collection detail pages missing delete button / breadcrumbs

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#120]
No Delete button on collection detail page: 
http://arsenal.library.ualberta.ca/communities/12c09af9-4a21-48a6-aae3-61e2fca89bb2/collections/d84b9b6c-fc64-481d-aead-8b81735b565f

Can replace link to "Parent Community: XXX" with standard breadcrumb above page title: 

community > collection

**Comment by cwant** [comment]
Done in PR #120
