### ISSUE TITLE
Author/Subject List Pasting

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1211]
**Is your feature request related to a problem? Please describe.**
Manual deposits can take a long time to complete due to individual copy/pasting of each author and keyword. 

**Describe the solution you'd like**
Please add the ability to paste delineated lists into the Authors/Creators and Subject/Keywords fields. 

**Describe alternatives you've considered**
Delineation by commas, semicolons, or even line breaks could work.

**Comment by weiweishi** [comment]
We will use a pipe "|" as a delimiter, as comma, or semicolons may appear in the entry.

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/jupiter/blob/add9c58c6b8c9642931a2e58e296c8ce3bd923c6/app/assets/javascripts/jupiter/item_draft.js#L61-L74

change to delimeter might be what is required
