### ISSUE TITLE
Manage users - CCID

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#123]
Need to add column for CCID (may be different than email if using aliases)

**Comment by mbarnett** [comment]
I'm not 100% on this one, but I don't think that's possible at the moment. We get the email from SAML as part of the CCID sign-in, not from the user, and iirc our conversation with our contact there, they do not currently send aliases. So the only email we'll ever get is their canonical version.

@murny anything about that sound wrong to you?

(I mean, we can still add a CCID column, but my impression right now is that it will always be email - @ualberta.ca in Production).

**Comment by murny** [comment]
yes CCID is always the email (without @ualberta.ca) as you mentioned.

Heres the knowledge base article: https://uofaprod.service-now.com/kb_view.do?sysparm_article=KB0012533

(currently we are keeping the ccid in the identity table and only keeping the email and displayName on user table)

**Comment by sfbetz** [comment]
Okay- that's all good!
