### ISSUE TITLE
Batch ingest ICARD

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1249]
**Brief description of the batch**
Monoord request from the HelpDesk. This batch should have priority.

**Manifest**
https://docs.google.com/spreadsheets/d/1uPGm0v5TCCaKoRFkH67mioBV1G0rm2qNBs5mmH-K0Vw/edit#gid=0

**Batch files**
https://drive.google.com/drive/folders/1tDDeCr0GjIEOuwgINynSL4CPzhXDBvCc

**Comment by dancockcroft** [comment]
Tested, should be ready for ingest.

**Comment by hhpicker** [comment]
Depositing manually.

**Comment by weiweishi** [comment]
deposit completed:
report is 
[2019_09_10_20_11_47.txt](https://github.com/ualbertalib/jupiter/files/3597628/2019_09_10_20_11_47.txt)

**Comment by weiweishi** [comment]
@hhpicker Forgot to include you in the response.
