### ISSUE TITLE
Autocomplete / autosuggest users in search

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#125]
Can we do an autocomplete / autosuggest search from list of users? there may be hundreds of user accounts with unfamiliar name spelling - this would make life easier for admins.

**Comment by sfbetz** [comment]
Clarification - talking about search box on Manage Users page

**Comment by cwant** [comment]
For reference, here is the wireframe:

https://jupiter.mybalsamiq.com/projects/jupiter/Admin%20-%20user%20management

One comment about the desktop version: if clicking on an autocompleted button goes to the user's page, does there really need to be a search button? (I am guessing no.)
