### ISSUE TITLE
Pull Community/Collection ID's for repopulation

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1253]
Requesting to pull the most current list of community/collection names and corresponding ID's from ERA in order to update the sheets involved in the batch investigation process. Any format will work.

**Comment by weiweishi** [comment]
[collections.txt](https://github.com/ualbertalib/jupiter/files/3535648/collections.txt)
[communities.txt](https://github.com/ualbertalib/jupiter/files/3535649/communities.txt)
Here you go, @dancockcroft Please let me know if they work for your purpose. In collections.txt, it includes collection id, title, and the community id.
