### ISSUE TITLE
Use embargo_history as an audit trail for embargo related activities. 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1258]
**Is your feature request related to a problem? Please describe.**
After discussion with @leahvanderjagt, we have agreed to extend the work in #1219, and use embargo_history to record all embargo related activities:
- When an embargoed item is deposited into the system, capture the embargo_history as follow:
"An embargo was activated at the time of deposit: _DateTime_when_item_is_deposited_. Release date: _embargo_date_. Intended visibility after embargo:  _visibility_after_embargo_"
- When an item is embargoed after deposit, capture the embargo_history as follow:
"An embargo was activated on _DateTime_embargo_activation_ by _user_. Release date: _embargo_date_. Intended visibility after embargo: _visibility_after_embargo_"

embargo_history should be visible on the record view for admin users. It can be displayed at the end of the record.

**Comment by mbarnett** [comment]
Closing – superceded by Connor's papertrail work
