### ISSUE TITLE
Unable to delete ERA item

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#1268]
**Describe the bug**
A user (Jeff Cho) has requested an item be removed (https://era.library.ualberta.ca/items/9ad1779a-e082-48a2-978e-aaca7aa78122) but I am given an error message when I try: `Something went wrong... Item may not have been deleted!`

**To Reproduce**
1. Go to this collection: https://era.library.ualberta.ca/communities/8ab3a896-bbb7-40b7-9c76-4f19830e0c9d/collections/60fc19b1-ff5b-48d7-bcf9-3fc4a8a6a516
2. Click on 'Delete' on the item "Ultraviolet"
3. See error

**Expected behavior**
Item should be removed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3809.100

**Additional context**
Please notify Jeff Cho (jeff.cho@ualberta.ca) once this item has been removed.

**Comment by pgwillia** [comment]
Some more info for whomever ends up working on this issue: https://rollbar.com/ualbertalib/jupiter/items/758/?item_page=0&item_count=100&#instances

**Comment by weiweishi** [comment]
This is one of those cases where the object was in Solr but not in Fedora. Since the request is to remove the object, I have removed it from Solr with REST API.
