### ISSUE TITLE
Consolidate Validations into Validation Plugins

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1288]
We were kind of abusing concerns to share logic between models that defined ad-hoc validations. With the removal of LockedLDPObject, those validations are largely duplicated between model instances (on the theory that concerns weren't really the "right" place for them, and that the concerns were starting to turn into messy ad-hoc inheritance grab-bags).

We should clean this up and establish a better pattern going forward by turning these into proper, reusable validations a la https://github.com/ualbertalib/jupiter/blob/master/app/validators/uri_validator.rb that eliminate the need to define validations like [these](https://github.com/ualbertalib/jupiter/blob/master/app/models/concerns/item_properties.rb#L110-L127) in models

See: https://guides.rubyonrails.org/active_record_validations.html#custom-validators for how to do this

**Comment by mbarnett** [comment]
Specific validations I think are worth targetting:

- visibility_must_be_known (in Depositable.rb) could be a visibility_validator
- publication_status_compound_uri in Item (could be something like a compound_uri validator ala uri_validator)
- publication_status_presence & publication_status_absence in Item (could these just use the normal presence and absence validator? not sure why these are custom at first glance)
- license_xor_rights_must_be_present in Item (could be a custom license_or_rights_validator)
- communities_and_collections_must_exist in Item & Thesis (could be a community_collection_validator)
- visibility_after_embargo_must_be_valid in Item & Thesis (could be a after_embargo_visibility_validator)

**Comment by lagoan** [comment]
Completed validators:
- [ ] visibility_must_be_known (in Depositable.rb) could be a visibility_validator
- [ ] publication_status_compound_uri in Item (could be something like a compound_uri validator ala uri_validator)
- [ ] publication_status_presence & publication_status_absence in Item (could these just use the normal presence and absence validator? not sure why these are custom at first glance)
- [ ] license_xor_rights_must_be_present in Item (could be a custom license_or_rights_validator)
- [ ] communities_and_collections_must_exist in Item & Thesis (could be a community_collection_validator)
- [ ] visibility_after_embargo_must_be_valid in Item & Thesis (could be a after_embargo_visibility_validator)
- [ ] community_validations in collection.

**Comment by lagoan** [comment]
Addressed this issue on #1768 . Closing.
