### ISSUE TITLE
Tracking Ticket for RDF Exporter for OAI-ORE 

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1290]
1) Build on the existing SolrExporter pattern, introduce the concept of an RDF exporter for OAI-ORE support by leveraging the RDF annotations provided by https://github.com/mbarnett/acts_as_rdfable (also, figure out  exactly what the API of the latter should be in providing this information)

2) Figure out a plan is for implementing the necessary PMH verbs for this (ie. start looking at what we need to support ListIdentifiers)

3) Build out a plan for implementing the rest of this

Edit:

We're also using this as a master ticket for tracking other info related to this, eg) example data, OAI validation tools, etc

**Comment by jefferya** [comment]
OAI-PMH validation tool
- Validates the API protocol, request/response via a stand-alone Perl app: <https://github.com/jefferya/oaipmh-validator>

**Comment by mbarnett** [comment]
Done/tracked elsewhere
