### ISSUE TITLE
Add a "Work must belong to at least one community/collection" validation

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#130]
DONE WHEN
- [ ] Validation prevents items from being created without being in any Communities/Collections
- [ ] Seeds & tests working w/ validation

**Comment by cwant** [comment]
Should the validation just check that at least one community/collection path exists for the item?
Or should the validation also query the existence of each community/collection path found? (from Solr)

**Comment by mbarnett** [comment]
The latter probably doesn't hurt, but there's always going to be a race-condition regardless of whichever approach is taken. Perils of using a datastore with no concept of transactions/constraints.
