### ISSUE TITLE
Centralize Abstraction for Thumbnail Generation

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1343]
Right now we call ActiveStorage's `variant`  and `preview` methods in a variety of places , with inconsistent error handling. This is leading to issues where an invalid or corrupted JPEG or other unknown format issue can lead to a page or search 500ing when it attempts to display a thumbnail for the file.

Arguably, calling into ActiveStorage for variants through the items and theses and communitiers and drafts that own these files is a law of demeter violation, and it's that anti-pattern that's at the root of our inability to correctly handle these errors. We should set up a single "clearing house" method for thumbnails across models that can abstract away the variant generation and handle errors consistently and easily.

If you're going to work on this please grab @mbarnett so that we can whiteboard out approaches and come up with a good, scalable solution that will serve us well down the road.

**Comment by pgwillia** [comment]
Some related tickets https://github.com/ualbertalib/jupiter/issues/1129 and https://github.com/ualbertalib/jupiter/issues/898

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/jupiter/blob/6c44b3208ae36ba2d4bed819e01ab6d9256c5609/app/models/community.rb#L51-L56

https://github.com/ualbertalib/jupiter/blob/2877fcb802d291918421d44e7903832b0d6dec10/app/models/jupiter_core/depositable.rb#L99-L118

https://github.com/ualbertalib/jupiter/blob/be07bdabf2cc2e801d9c1ac3e5af75ebdc4ad099/app/models/concerns/draft_properties.rb#L53-L64

https://github.com/ualbertalib/jupiter/blob/f9c878aaf9acd10d00e00137bf087405117bb43a/app/views/items/draft/_thumbnail.html.erb#L2-L17
https://github.com/ualbertalib/jupiter/blob/f9c878aaf9acd10d00e00137bf087405117bb43a/app/views/admin/theses/draft/_thumbnail.html.erb#L2-L17

**Comment by pgwillia** [comment]
Here's the rough approach:
- Community, Depositable and DraftProperties all get an instance method #logo 
- ImagesHelper gets a new method #logo_path which does the error_handling and rollbar reporting
- views call `logo_path(item.logo)`

**Comment by pgwillia** [comment]
Merged into postmigration branch.
