### ISSUE TITLE
Mobile nav menu

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#135]
Realized my wireframes were not very clear! Balsamiq is a bit opaque.

Mobile menu should have these options across the top nav:

When not logged in - ERA logo, Browse, About (dropdown includes static content pages (eg about, contact, how to deposit, etc), My Account (with little person icon), Search icon

When logged in as admin - "My Account" is replaced by name (eg Admin, or CCID) with drop down that includes: Dashboard, Logout

Dashboard only needs to appear when user clicks on dashboard in dropdown. Otherwise, it hides page changes when user click link in dashboard. Users can get to and from dashboard by using dropdown in nav, or breadcrumbs on pages.

Full-sized nav menu can just expand these options (eg about pages can display across page instead of being contained in "about" dropdown)

**Comment by murny** [comment]
Updated in mockups now. Some notes of the navbars are made under the site assets (symbol libraries) under ERA Templates

**Comment by murny** [comment]
@sfbetz closing issue. I think these requirements have now been changed with the work that was done with the homepage/themeing. If something is still left that needs to be fixed, let me know!
