### ISSUE TITLE
Fall 2019 theses - supervisor/co-supervisor and committee lists keywords

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#1356]
**Describe the bug**
Fall 2019 theses appear to have been ingested with the keywords repeating in the supervisor/co-supervisor and committee member fields

**To Reproduce**
1. Go to https://doi.org/10.7939/r3-v2z3-d261 or https://doi.org/10.7939/r3-z68j-p818
2. Click on More Information
3. See keywords appearing where supervisor/co-supervisor and committee members should be

**Expected behavior**
This should include names and departments rather than keywords

**Additional context**
Was this an error on ingest? Or did this data come to us incorrect?
Note that a user contacted us on Nov 15 which is when the theses came out from under embargo

**Comment by weiweishi** [comment]
A python script was created for this ingest cycle to clean up the data we received from IST, and the information for supervisors was incorrectly populated. 
- [ ] @weiweishi batch fix the data
- [ ] @weiweishi to work with @skyu0221 to review the script and make sure the correct information is used. And the script is committed to Github.
