### ISSUE TITLE
Description/Abstract as non-mandatory field on Thesis

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1357]
**Is your feature request related to a problem? Please describe.**
Abstract on the deposit/edit form for thesis is a mandatory field, and it's been validated and error will appear for older theses when they don't have an abstract field, and preventing modification of other fields on these records. 

Question to @leahvanderjagt and @sfarnel, should we remove the validation on the edit form to allow blank abstract? The form is only used by admin users.

**Comment by sfarnel** [comment]
Thanks @weiweishi I think this would be one way of address this issue where we may well have theses with no abstract. I also think it worthwhile to consider whether we should create a model for legacy theses separately as they differ quite a bit from the ETDs

**Comment by weiweishi** [comment]
We can remote the validation for theses prior to 2009. And add this as a conditional validation.
