### ISSUE TITLE
License validation on Edit form to allow older CC licenses

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1359]
Our deposit/edit form validates licenses from this:
https://github.com/ualbertalib/jupiter/blob/integration_postmigration/config/controlled_vocabularies/license.yml
the data model allows the licenses to be older versions:
https://github.com/ualbertalib/jupiter/blob/integration_postmigration/config/controlled_vocabularies/old_license.yml
But the form doesn't allow it. It has prevented our era team to update records unless the license is updated to a new version.

**Comment by mbarnett** [comment]
Believe we can leverage https://guides.rubyonrails.org/active_record_validations.html#conditional-validation to conditionally validate the field based on whether or not the user is an admin.
