### ISSUE TITLE
[ERA] Display issue when hovering over selected facet

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#1374]
**Describe the bug**
There's a display issue when hovering over selected facet (excluding the furthest right facet.) The display issue looks to be an underline on the text that extends to the next box. 

**To Reproduce**
1. Make a search
2. Click on at least two facets
3. Hover over their top box and notice the issue

**Expected behaviour**
No line should be present when hovering.

**Screenshots**
![Screenshot from 2019-12-09 14-06-26](https://user-images.githubusercontent.com/14242562/70473000-670f7a80-1a8d-11ea-92f1-c710fbfb9228.png)

**Desktop:**
 - Chrome

**Comment by mbarnett** [comment]
fixed in prod at last
