### ISSUE TITLE
Issues in Post-Migration Branch

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1375]
- [ ] embargo history is missing https://github.com/ualbertalib/jupiter/commit/96cb5b883b735df20d8ad1f732a0457d18f3dfa2 -- I noticed this when looking at failing tests.  Also embargo logic https://github.com/ualbertalib/jupiter/blob/26c362419e99ed9e4b927ba75f1c1cafb3865dd5/app/models/item.rb#L70-L80 missing which causes a validation error when swapping visibility in test.

**Comment by weiweishi** [comment]
@mbarnett should we do a spike and look into options like https://github.com/paper-trail-gem/paper_trail, to see what we need to do to bring things like embargo history, object changes into the new codebase?

**Comment by weiweishi** [comment]
Related to #1365

**Comment by pgwillia** [comment]
closed by #1365 and #1382
