### ISSUE TITLE
Upgrade Infrastructure for Rails 6

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#1433]
Upgrade anything for staging/production for running Rails 6.
- [x] Rails 6 REQUIRES Ruby 2.5 or greater
- [x] Rails 6 REQUIRES Postgres v9.3 or greater
- [ ] We need Nodejs on server (which i believe we have this! I know we made the switch for discovery as we moved away from `therubyracer` for a javascript runtime to nodejs)
- [ ] Need yarn installed
- [ ] Test `RAILS_ENV=production bundle exec rails assets:precompile`. Should still work with no problems, no changes need. More info here: https://github.com/rails/webpacker#deployment

**Comment by mbarnett** [comment]
Done and dusted
