### ISSUE TITLE
[ERA] Create tests surrounding updating logo

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#1436]
Tests should be created surrounding the addition of 'item.logo_id = nil' and 'thesis.logo_id = nil' in app/models/item.rb and app/models/thesis.rb respectively. It was found that without this line this error occurs: 
```
 ERROR:  update or delete on table "active_storage_attachments" violates foreign key constraint "fk_rails_a9238d43b0" on table "items"
DETAIL:  Key (id)=(36) is still referenced from table "items".
```
You could just add a unit test where an item/thesis that has an existing logo is updated with a new draft

**Comment by mbarnett** [comment]
Just need to add a regression test to ensure this error does not recur.

**Comment by ConnorSheremeta** [comment]
Lines added are here:
https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/models/item.rb#L98
https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/models/thesis.rb#L98

**Comment by ConnorSheremeta** [comment]
Closed as the system tests in https://github.com/ualbertalib/jupiter/issues/1435 suffice
