### ISSUE TITLE
Community: description cannot be null, requires `presence: true`

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#145]
From #133 looks like collections descriptions are optional but community descriptions are required.

From data dictionary: https://github.com/ualbertalib/metadata/blob/master/data_dictionary/Jupiter%20Profile%20Template.md#jupitercommunity--pcdmobject

**Comment by cwant** [comment]
@sfbetz @leahvanderjagt this needs your input.

According to a comment made by Leah to Matt in a meeting, community descriptions are optional:

* https://github.com/ualbertalib/jupiter/issues/38#issuecomment-323792140

According to old ERA requirements doc, and data dictionary, community descriptions are required:

* https://docs.google.com/document/d/1tpDL3N6rgE_rQr1X4hPP-wIv4uCcOUINPLIhHu23DTw/edit
* https://github.com/ualbertalib/metadata/blob/master/data_dictionary/jupiter_profile_template.md

**Comment by leahvanderjagt** [comment]
I think I've given conflicting instructions, sorry about that. They should
be optional in the data dictionary. Sometimes we have to create them before
we have a description and many current ones are lacking one, so make them
optional and I'll deal with getting them populated through our
service/outreach work.

Leah

**Comment by cwant** [comment]
@zschoenb, @danydvd please see the above comment about data dictionary.

**Comment by murny** [comment]
Closing this issue then as this is currently implemented accordingly. Cheers :+1:

**Comment by zschoenb** [comment]
A comment has been added to the data dictionary re: description in collections: 

A description is required for communities and optional for collections. An exception is when a community must be created but a description is not immediately ready/available.

The comment will be visible tomorrow morning.

**Comment by murny** [comment]
```
A description is required for communities and optional for collections. An exception is when a community must be created but a description is not immediately ready/available.
```

I would say that's not required then and more so optional? Let's not make this complicated. Your either required (has to be required for anything to get save) or optional.

**Comment by zschoenb** [comment]
Sounds good. Will be corrected tomorrow morning.

**Comment by zschoenb** [comment]
A comment on description in the collection profile now simply states: `Recommended for communities`

**Comment by zschoenb** [comment]
A separate profile has been created for each of 'community' and 'collection' to make room for these nuances.
