### ISSUE TITLE
add check_passenger for Nagios

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1454]
@henryzhang87 asked
>There is a gem called check_passenger which can be installed for Nagios monitoring purposes.
Would you mind including it in your Gemfile for the next release? It can be used to check processes, live_processes, memory etc

```
[root@bedford ~]# check_passenger processes
Passenger 6.0.4 OK - 12 processes|process_count=12;;;0;12
[root@bedford ~]# check_passenger live_processes
Passenger 6.0.4 OK - 0 live processes|live_process_count=0;;;0;12
[root@bedford ~]# check_passenger memory
Passenger 6.0.4 OK - 415MB memory used|memory=415;;;0;
```

**Comment by murny** [comment]
Jupiter doesn't need this as a dependency (added to our Gemfile) 🤔. 

Should be able to install it on the server (whether manually or via playbook) as they suggest in the readme: https://github.com/aredondo/check_passenger#installation
E.g: `gem install check_passenger` as a global gem on the server

**Comment by pgwillia** [comment]
Thu, Feb 6, 11:01 AM Weiwei responded to Henry's request and suggested using ansible to install this gem via a playbook.
