### ISSUE TITLE
Add authentication for Jupiter's APIs

### ISSUE THREAD

**Issue by lagoan** [ualbertalib/jupiter#1480]
**Is your feature request related to a problem? Please describe.**
Jupiter needs to provide a way to access its APIs from different clients. The simplest way to accomplish this could be with a system user account and a token. 

**Describe the solution you'd like**
Basic http authentication and sessions would be the easiest approach.

**Describe alternatives you've considered**
We could also go with JWTs or PASETOs but sometimes their implementations have security problems and have added complexity

**Additional context**
From comment https://github.com/ualbertalib/jupiter/pull/1370#issuecomment-561799351

**Comment by mbarnett** [comment]
I think we can close this thanks to #1522? (feel free to reopen if I'm wrong)
