### ISSUE TITLE
Data Migration for Post-Fedora Jupiter

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1490]
- [ ] Data migration from production ERA to https://github.com/ualbertalib/jupiter/tree/integration_migration_phase1. 
- [ ] Data migration from https://github.com/ualbertalib/jupiter/tree/integration_migration_phase1 to https://github.com/ualbertalib/jupiter/tree/integration_postmigration

Current status:
new staging server: era-app-stg-1.library.ualberta.ca is deployed with integration_migration_phase1. It links to current ERA staging Fedora and staging solr cloud. The data is synced from ERA production on Jan 28. The migration took 86 mins to complete. Here are the list of issues in the current migration:

- invalid data type for one item: 
```
4b3e0c51-33f7-4de9-97ad-d8bd298a8e92
Validation failed: Item type translation missing: en.activerecord.errors.models.ar_item.attributes.item_type.not_recognized
```
The content type is http://vivoweb.org/ontology/core#ConferencePaper, which is invalid. Can't update the data: get an `ActiveFedora::ObjectNotFoundError (Couldn't find IRItem with 'id'=4b3e0c51-33f7-4de9-97ad-d8bd298a8e92)" `error. Item is in Solr but not in Fedora?

- Argument out of range error message for Thesis:
for example: 3a787d61-b640-42b2-9cf1-b306e161503c. 
Item is not accessible through rails console
```
irb(main):006:0> Thesis.find('3a787d61-b640-42b2-9cf1-b306e161503c')
Traceback (most recent call last):
        6: from app/models/jupiter_core/locked_ldp_object.rb:87:in `inspect'
        5: from app/models/jupiter_core/locked_ldp_object.rb:87:in `map'
        4: from app/models/jupiter_core/locked_ldp_object.rb:88:in `block in inspect'
        3: from app/models/jupiter_core/locked_ldp_object.rb:713:in `block in define_cached_reader'
        2: from app/models/jupiter_core/locked_ldp_object.rb:449:in `coerce_value'
        1: from app/models/jupiter_core/locked_ldp_object.rb:481:in `coerce_value'
ArgumentError (argument out of range)
```
It has a date_accepted  "date_accepted_ssim":["2000"], instead of a valid date string. 
Item is accessible from both Solr and Fedora. (http://gillingham2.library.ualberta.ca:8080/fedora/rest/prod/3a/78/7d/61/3a787d61-b640-42b2-9cf1-b306e161503c). This issue might be related #1195

**Comment by mbarnett** [comment]
We want to for everything deposited before 2009, clear out date_accepted and we will use graduation date for that information.
