### ISSUE TITLE
Remove Matomo tracking on Jupiter

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1493]
As an early experiment to see if we can replace GA because of privacy concerns, we implemented Matomo. But without a systematic review on what's been collected, and a lack of framework on our requirements for web stats, we would like to decommission Matomo at this stage, and will reevaluate our needs and requirements in the future, and assess if there will be a need for an in-house web analytics tool. 

Please remove the Matomo tracker we have implemented on Jupiter.

**Comment by pgwillia** [comment]
Was introduced by this PR https://github.com/ualbertalib/jupiter/pull/602/files

**Comment by murny** [comment]
Believe this is now done and merged in. Closing issue.
