### ISSUE TITLE
reporting short 500 error in ERA Feb 24 2020

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1495]
Submitted via email from:Era.Helpdesk@ualberta.ca

Devs,

This item would return a 500 error when I was attempting an Admin edit (add
CCID protection) between roughly 11:15 and 2:00 PM today.

https://doi.org/10.7939/r3-yhvm-jp82

The edit/save went through properly by 2:15

Anna
ERA Help

--

**Comment by weiweishi** [comment]
related to #1494

**Comment by weiweishi** [comment]
this particular issue is fixed by @henryzhang87 to change owner and permissions. Will use #1494 to follow up on troubleshooting.
