### ISSUE TITLE
Enable new Rubocops

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1524]
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:

 - Style/HashEachMethods (0.80)

 - Style/HashTransformKeys (0.80)

 - Style/HashTransformValues (0.80)

For more information: https://docs.rubocop.org/en/latest/versioning/

**Comment by mbarnett** [comment]
Looks like we can close this thanks to #1526? (feel free to reopen if I'm wrong)
