### ISSUE TITLE
Investigate, Document, and Plan Out Untangling of Draft Publication Status

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1556]
## Problem

The term "published" is heavily overloaded in the codebase. In `Item`, there is an attribute, `publication_status`, that indicates whether or not certain kinds of items have been published in the sense of (for example, it's an Article and it was published in a Journal somewhere instead of being a preprint or whatever. This is _not related_ to the following, but needs to be kept in mind when understanding the codebase.

This is distinct from the boolean attribute `is_published_in_era` in the DraftItem and DraftThesis models, which was intended to indicate whether or not a Draft had ever been "published" into a corresponding Item or Thesis, or whether or not it was just a draft that had never progressed to becoming a visible item. This column is leveraged in a scope, `scope :drafts, -> { where(is_published_in_era: false) }`

However, somehow we've acquired multiple different ways of understanding when a Draft is or isn't "published" in the above sense, unrelated to the `is_published_in_era` column. There is a `status` enum in the `DraftProperties` concern shared by `DraftItems` and `DraftThesis` which has the following values: `enum status: { inactive: 0, active: 1, archived: 2 }`. 

Furthermore, there's a _second_ scope, `scope :unpublished, -> { where(status: :active).where('uuid IS NULL') }`, which seems to be looking at both the status and the absence of a "uuid" (the uuid is the id of the corresponding Item or Thesis model).

It's unclear how these things (status, is_published_in_era, the drafts scope, and the unpublished scope) co-exist, or why we need two columns, or why the `unpublished` scope does not take into account the value of `is_published_in_era`. It seems like we have competing implementations here, and probably consequently either one of these mechanisms is unused, or there are some bugs in how draft publication states are being managed because only one of these two mechanisms is being updated.

## Next Steps

1. Firstly, we need to figure out what columns and scopes are being used where, so that we understand what the current situation is in the codebase.
2. Second, we need to document the current state of the codebase, by adding explanatory comments to status enum, the drafts scope, and the unpublished scope, clearly explaining what situations these things are being used to managed, and by adding an explanation to this ticket of what things are being used where, and how they interact.
3. Finally, we need to plan out a refactoring of the codebase to simplify the whole concept of publishing/unpublishing drafts in ERA so that we don't have these competing columns.

**Comment by murny** [comment]
# Questions

Given the excellent problem summary above, I will attempt to break down the details from researching the codebase to hopefully clear up the confusion around the different implementations we have for "draft" and "publish" items/theses. 

Mainly we want to figure out and answer the following questions:
- What is the difference between all these competing implementations? Why do we have `status` enum, `is_published_in_era` boolean column, drafts and unpublished scopes in our codebase? 
- Do we really need both Item and DraftItem (or Thesis and DraftThesis) models?

# What is the difference between all these competing implementations?

## `status` enum
We have a [Active Record Enum]( https://edgeguides.rubyonrails.org/active_record_querying.html#enums) for Status on DraftItem/DraftThesis models (found in [DraftProperties concern](https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/models/concerns/draft_properties.rb#L7))
Example: `enum status: { inactive: 0, active: 1, archived: 2 }` 

This `status` enum plays a huge role in our Depositing Item/Thesis workflow (step by step wizard) for creating new and editing existing Items/Theses. 

I will explain each status and the overall Deposit workflow.

When a DraftItem/DraftThesis object is first created it is in the `inactive` status (this is the default state). The `inactive` status excludes almost all model validations we have for these objects meaning you can create one without a title, description, etc. The reason for this, is the "Deposit" link on ERA actually is a "post" request which will create a new draft object to be used with the form wizard. We will also cleanup any of these `inactive` draft objects via a rake task in the case that a user clicks on "Deposit" and walks away leaving an "inactive" Draft Item/Thesis in our database (See Enhancements section below for a way to improve this current process). 

When a user fills out the first step of the wizard, this Draft object status gets converted from `inactive` to `active`.  Meaning the user has started a Deposit and the Draft object is now "active". From code point of view, `active` status enables a bunch of validations on the draft object. `active` draft object requires a title, description, graduation date/term, community/collection pair, creator, etc. We also use `active` status to flag any draft objects which are "unpublished" (aka anything that is not `inactive` and not `archived`) which will be talked below in `unpublished` scope section.

When the user successfully deposits an Item/Thesis, the draft object gets converted from `active` to `archived`. This is also the point in time where we take that DraftItem/DraftThesis and move all the data into a brand new Item/Thesis object. We also take that new Item/Thesis primary ID and update the previous DraftItem/DraftThesis `uuid` column with this information.
Once in "archived" status and its UUID column has a value in it, the draft object is considered "Published". There should now be a valid Item/Thesis in the database now.

So as a summary, we use this `status` enum heavily for the deposit lifecycle of a DraftItem/DraftThesis object. From looking at this `status` value, you can tell if its just been freshly created (inactive), a user has begun the wizard form (active), or if a user has finished and successfully deposited it into ERA (archived).

### Enhancements

## `unpublished` scope

## `is_published_in_era` boolean

## `drafts` scope

**Comment by mbarnett** [comment]
Thanks Shane, this is all super helpful. I'm on board with all of your suggestions in the conclusion and we can probably create a couple of tickets to make these changes.

The one other suggestion that comes to mind is that we summarize your explanation of the way the status enum interacts with the draft lifecycle and add it as a comment [here](https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/models/concerns/draft_properties.rb#L7), so that there's some documentation in the codebase explaining the situation

**Comment by murny** [comment]
I believe the main objective of this issue is now accomplished. We have removed the main confusion (is_published_in_era boolean and drafts scope) and added code documentation to the status enum. Also ticketed up a few improvements to jupiter from this discovery.

Closing out issue
