### ISSUE TITLE
Enable New Rubocops

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1581]
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Lint/RaiseException (0.81)
 - Lint/StructNewOverride (0.81)
For more information: https://docs.rubocop.org/en/latest/versioning/

**Comment by pgwillia** [comment]
The StructNewOverride cop warns that for https://github.com/ualbertalib/jupiter/blob/03691d9211db9010901af6a846a6a73edb1b2dfd/app/models/jupiter_core/solr_services/facet_result.rb#L3
Lint/StructNewOverride: :count member overrides Struct#count and it may be unexpected.

**Comment by murny** [comment]
This is now merged. Closing this issue
