### ISSUE TITLE
Merge PR #1590 once JQuery v3.5.1 is released

### ISSUE THREAD

**Issue by lagoan** [ualbertalib/jupiter#1599]
From @murny:

Looks like unintended breaking change in JQuery v3.5.0 which is breaking bootstrap and few other libraries we have. Breaking change is documented here: https://github.com/jquery/jquery/issues/4665

Sounds like this will be fixed in v3.5.1 (once this PR gets merged: https://github.com/jquery/jquery/pull/4666). So once v3.5.1 gets released, we can upgrade.

_Originally posted by @murny in https://github.com/ualbertalib/jupiter/pull/1590#issuecomment-615022773_

**Comment by murny** [comment]
This has now been upgraded. Closing issue
