### ISSUE TITLE
Items which require data cleanup

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1636]
- [ ]  Item 4b3e0c51-33f7-4de9-97ad-d8bd298a8e92 has undefined `item_type_with_status`
https://era.library.ualberta.ca/search?search=Fedora+4+OAI+Provider+Diagram
![image](https://user-images.githubusercontent.com/1220762/81230300-74824f80-8fae-11ea-9c05-003b7dce758f.png)
item belongs to @piyapongch.  We've determined that it needs to be deleted in the console
- [ ] 7475f152-e0e2-4465-82af-03986decadcb has a typo in the visibility so you can't edit it
- [ ] dd0a292a-65ea-4499-8133-30ee2db630a7 has an argument out of range () when trying to parse the Time which prevents editing

**Comment by mbarnett** [comment]
These seem fixed, I think?

**Comment by mbarnett** [comment]
Closing unless someone knows more about this than I do and can still recreate any of this
