### ISSUE TITLE
Index date_created into a year created

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#166]
DONE WHEN:

- [ ] date_created changed to string to allow for free-formed entry
- [ ] year_created solr index somehow intelligently populating from date-like strings (Peter suggests 4 digit regexes) (Shane suggested Chronic, which might give better results in some cases, but we might need to fall back to a regex for some proposed inputs like "before 1989").

**Comment by pbinkley** [comment]
Here's the [corresponding issue](https://github.com/ualbertalib/metadata/issues/109) on the data dictionary.

**Comment by weiweishi** [comment]
migrated object will have sort_year generated. This needs to be populated during item deposit.

**Comment by cwant** [comment]
Is there anything else needed for this ticket now that `sort_year` is implemented?

**Comment by weiweishi** [comment]
feel this is completed. Close it for now. If I miss anything, please feel free to reopen.
