### ISSUE TITLE
Facets being misleading for Items Search on Collection Show page 

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#1661]
**Describe the bug**
Facets are being shown in a misleading way which could cause confusion for users. It appears you have the ability to remove the collection facet (which is applied by default on the Collection Show page), but this does nothing as results are still being filtered by this facet.

**To Reproduce**
1. Go to a collection show page (e.g: https://era.library.ualberta.ca/communities/b41cdbfd-6af2-4a13-8ba6-59725565d445/collections/d777db5c-b38f-4326-9e4a-c856b6389031)
2. No facets being shown:
![image](https://user-images.githubusercontent.com/1930474/82711535-e3b0a280-9c42-11ea-89a3-04dd7c8bdfaa.png)

3. Click on a new facet (say author facet), now two facets are being shown (one for author and one for the default collection (the collection for the show page)):
![image](https://user-images.githubusercontent.com/1930474/82711574-0642bb80-9c43-11ea-8542-ef9ee49b66c1.png)

4. If we attempt to remove the default collection facet, it will do a request to the server and rerender the exact same page, still showing two facets
5. If we remove the author facet, then we get the previous results but now with the default collection facet being shown: 
![image](https://user-images.githubusercontent.com/1930474/82711667-430eb280-9c43-11ea-866d-b346e9232f56.png)
6. We can now also remove the default collection facet, which does get removed, however the results coming back are the exact same (we still faceting by this default collection):
![image](https://user-images.githubusercontent.com/1930474/82711711-676a8f00-9c43-11ea-9978-30fce91aa78a.png)

**Expected behavior**
We probably shouldn't be showing the default collection as a facet at any point. It's already assumed you are only showing items within this collection when viewing the collection show page. By showing this facet and having the current behaviour of it being removable could cause confusion to end users.

**Comment by mbarnett** [comment]
Fixed on prod
