### ISSUE TITLE
Investigate "This file is processing and will be available shortly "

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1669]
**Describe the bug**
As an admin or a non-admin user, a successful deposit results in "This file is processing and will be available shortly" 
![image](https://user-images.githubusercontent.com/1220762/83202219-5e2a6800-a104-11ea-848d-6eb6d5a4721a.png)

It appears that this doesn't resolve after the sidekiq queue has been cleared or any amount of waiting.

**To Reproduce**
1. Go to 'Deposit'
2. Fill out the wizard
3. Add some files
4. Click on "Save"
5. See "This file is processing and will be available shortly"  for each of the files you've added

**Expected behavior**
The view and download links should be available when the files are completed processing.

**Additional context**
If `fileset_uuid` is not present then the processing message will be shown https://github.com/ualbertalib/jupiter/blob/d8d0f1fbf1196a15bc5fa61cb141ecc0de375b4a/app/views/items/_files_section_sidebar.html.erb#L6
The `fileset_uuid` should be set here so I suspect that we're not reaching line 134 https://github.com/ualbertalib/jupiter/blob/d8d0f1fbf1196a15bc5fa61cb141ecc0de375b4a/app/models/jupiter_core/depositable.rb#L124-L137

Rails 6 update made a few changes to ActiveStorage which may or may not be related https://edgeguides.rubyonrails.org/6_0_release_notes.html#active-storage

**Comment by murny** [comment]
Should be fixed with above PR being merged. Closing issue.
