### ISSUE TITLE
Sort out Jupiter Core temporary namespace

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#167]
Right now there's a [placeholder vocabulary](https://github.com/ualbertalib/jupiter/blob/master/config/vocabularies.yml#L24) that we've been using to add predicates/terms we've needed as we figure out what other kinds of information we need to record in Fedora to make the system work properly. 

These terms do not all necessarily belong in one namespace, as there might be other vocabularies and existing predicates out there that cover our needs, so these terms need to be worked through with Metadata to figure out what's best for each need, and where we may need to mint new terminologies.

This is going to be an evolving project as the system evolves, because we're going to continue to find unanticipated instances of information we need to store to make the system work.

**Comment by weiweishi** [comment]
This is handled with work in #165, and information is documented in data dictionary.
