### ISSUE TITLE
`content_tag` is deprecated, we should work to replace this with `tag.<name>` but the autocorrect was not helpful

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1706]
Rails/ContentTag: Use tag instead of content_tag. (rails/rails#25195, https://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-content_tag)

`content_tag` is deprecated, we should work to replace this with `tag.<name>` but the autocorrect was not helpful

_Originally posted by @pgwillia in https://github.com/ualbertalib/jupiter/pull/1697#issuecomment-642278419_

**Comment by lagoan** [comment]
Fix merged into integration_postmigration

**Comment by lagoan** [comment]
Fix merged into integration_postmigration
