### ISSUE TITLE
Upgrade Fedora docker image to 4.7

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#175]
I think we're using Fedora 4.6 on our docker image currently, and Henry is setting 4.7 up for Production and Staging. We should upgrade our docker image in case there are any differences we need to be aware of in 4.7

**Comment by murny** [comment]
We are currently using 4.7: https://github.com/murny/docker-fcrepo4 (latest is the 4.7 folder)

**Comment by mbarnett** [comment]
Well then that was easy
