### ISSUE TITLE
Oaisys improvement: Error handling should return 4xx status not 200

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#1784]
I noticed when oasis controllers raise exceptions, we capture them here https://github.com/ualbertalib/oaisys/blob/master/app/controllers/oaisys/application_controller.rb  and render a proper view. Which is great 👍 

However, we are returning 200 status codes for these errors. We probably should be returning a proper status code for these.

Small enhancement but basically just add a `status` key to the render method with the code we want to raise:

```
render :error,  status: :bad_request
```

More info: https://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option

**Comment by mbarnett** [comment]
@ConnorSheremeta can you look at the OAI:PMH standard and see if this is compatible with it or not? Because it's so SOAP like I suspect that 200, <error message> might actually be what they want. If the standard doesn't spell it out, you might need to check the Perl validation script you're using and the behaviour of some existing OAI servers.

**Comment by ConnorSheremeta** [comment]
OA has stated this in the documentation (http://www.openarchives.org/OAI/openarchivesprotocol.html):

```
3.1.2.2 Status-Code

OAI-PMH errors are distinguished from HTTP Status-Codes. Since OAI-PMH uses HTTP as a transport layer, servers implementing OAI-PMH must conform to HTTP status code definitions and report relevant HTTP transport layer status via those Status-Codes. OAI-PMH repositories may employ HTTP Status-Codes in addition to "200 OK". For instance, the following Status-Codes may be useful for load balancing in OAI repositories:

    302 - Allows the repository to temporarily redirect an OAI-PMH request to another repository. The URI of the temporary repository should be given by the Location field in the HTTP response.
    503 - Service unavailable, a Retry-After period is specified. Harvesters should wait this period before attempting another OAI-PMH request.
```

Our current implementation gives 200 for errors along with other implementations that I have tested.

Looks like we're good to stick with a 200, closing this!
