### ISSUE TITLE
Investigate how to highlight terms in search results descriptions

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#1800]
From EPIC: https://github.com/ualbertalib/jupiter/issues/1610

When my search results are returned, I expect to be able to see where the keyword shows up and highlighted within the results.

Example: 
![image](https://user-images.githubusercontent.com/1930474/89468431-ac776b00-d734-11ea-80cb-e78a581ffb7b.png)

![image](https://user-images.githubusercontent.com/1930474/89468452-b4cfa600-d734-11ea-800c-67de7d0ffaed.png)

I know elasticsearch has a "highlighting" feature which gives us exactly this behaviour (more info: https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html). Solr must have something similar we can look into.

**Comment by pgwillia** [comment]
Check out https://lucene.apache.org/solr/guide/6_6/highlighting.html
