### ISSUE TITLE
add after_commit_everywhere to Gemfile for AASM deprecation

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#1801]
**Describe the bug**
```
[DEPRECATION] :after_commit AASM callback is not safe in terms of race conditions and redundant calls.
              Please add `gem 'after_commit_everywhere', '~> 0.1', '>= 0.1.5'` to your Gemfile in order to fix that.
```

Related to https://github.com/ualbertalib/jupiter/pull/1793

**To Reproduce**
1. On setup of the application `rake db:setup`
2. See deprecation warning

**Comment by murny** [comment]
I believe this is fixed now with latest version of AASM: https://github.com/ualbertalib/jupiter/pull/1813

Changelog notes: 

`Fix Depreciation message for after_commit_everywhere #695 in PR #696`

Seems like this deprecation will ONLY get raised now if you are using `after_commit` which we are not.
