### ISSUE TITLE
Unable to create collections. Application throws a 404.

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/jupiter#1825]
**Describe the bug**
I cannot create a new collection. I get a 404 message when I try to do so.

**To Reproduce**
1. Go to any community page.
2. Click on 'create collection'

**Expected behavior**
Collection creation should be verified and collection should be present throughout application.

**Screenshots**
Two screenshots attached.

**Desktop (please complete the following information):**
iOS10.14.6
Chrome
Version 84.0.4147.125 

**Additional context**
This is a high-priority problem.

**Comment by mbarnett** [comment]
This definitely, 100%, and for all time, is fixed.
