### ISSUE TITLE
All theses don't belong to one collection

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#1852]
There are 23101 theses on prod but there are only 23008 in the 'Graduate Studies and Research, Faculty of/Theses and Dissertations' collection. We need to determine why those theses are not part of that collection, could be an ingest issue or a deliberate decision. Follow up with Sean or Leah required when the discrepancies are identified.

**Comment by anayram** [comment]
The remaining theses are part of non-ualberta theses collections (mainly St. Stephens').

All theses can be output via etdms metadataPrefix, and I believe LAC should be able to only harvest UofA theses via a OAI Set. Tagging @sfarnel in case there is anything else to add. Adding this to next week's repo meeting agenda.

**Comment by mbarnett** [comment]
Thanks for the explanation, Mariana! We were mostly just confused by the slight discrepancy between the numbers, and wanted to make sure there wasn't some kind of bug lurking somewhere that resulted in this, but that explanation makes sense.

I'm going to close this on the assumption that all is as it should be, but if any other information pops up that indicates that something is wrong here, feel free to re-open.
