### ISSUE TITLE
[Not Urgent] Metadata Only Record

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1854]
Submitted via email from:Era.Helpdesk@ualberta.ca

Hi Dev Team,

We noticed a record without a file attached to it through an interaction
with a user:
https://era.library.ualberta.ca/items/ed021482-3cb4-4ebf-b535-e5553682a76d

This is not an urgent problem, but I just wanted to make sure you're aware,
and that it doesn't point to a larger issue.

Sean

**Comment by mbarnett** [comment]
This doesn't seem to ever have had a file in Jupiter. Hydra noid is 3n203z369 and the fedora 3 id is "uuid:34bc83f3-4f15-413c-a2f6-abf2dc7945f5", so it might be possible for someone to fish an old copy out of somewhere, if those weren't also metadata only?

**Comment by sfarnel** [comment]
Thanks @mbarnett 

@anayram would you be able to take a look at this?

**Comment by pgwillia** [comment]
Appears to have been resolved
![image](https://user-images.githubusercontent.com/1220762/179624121-39ecfd6f-42e9-4e0a-96cf-5a95975ec542.png)
