### ISSUE TITLE
OAI: External institution theses attributed to UofA in oai_dc

### ISSUE THREAD

**Issue by anayram** [ualbertalib/jupiter#1860]
**Describe the bug**
Some theses in ERA that were granted by external institutions (non UofA theses) are attributed "University of Alberta" as publisher in `oai_dc` metadata.

**To Reproduce**
1. Go to [this thesis, published by the Edmonton Social Planning Council](https://era.library.ualberta.ca/items/3a2b9787-147d-48a0-9f14-9ad5d3b843c6), check metadata (no publisher or grantor information available).
2. Check its [equivalent OAI DC metadata](https://era.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:era.library.ualberta.ca:3a2b9787-147d-48a0-9f14-9ad5d3b843c6): where a `<dc:publisher>University of Alberta</dc:publisher>` field is included (its [ETDMS record](https://era.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=oai_etdms&identifier=oai:era.library.ualberta.ca:3a2b9787-147d-48a0-9f14-9ad5d3b843c6) is fine).
3. Additional example: [this thesis](https://era.library.ualberta.ca/items/3cec63f3-ab6e-41db-a01b-e7dfb436bf6c), published by Aberystwyth University, and for its equivalent OAI DC record [click here](https://era.library.ualberta.ca/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:era.library.ualberta.ca:3cec63f3-ab6e-41db-a01b-e7dfb436bf6c).

**Expected behavior**
`dc:publisher` content should only be derived from grantor metadata. Theses that lack a grantor field will be addressed separately.

**Comment by ConnorSheremeta** [comment]
https://github.com/ualbertalib/jupiter/issues/1864 will address this issue, those institutions need to be added to a .yml file which will be done after the upgrade.

**Comment by anayram** [comment]
@pgwillia I think this ticket can be closed. @sfarnel, external universities not in Jupiter's yml file will appear as "Unknown" publisher / grantor in OAI responses. If that is ok, we can close this now and revisit it if needed in the future.
