### ISSUE TITLE
User reported 404 error

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/jupiter#1867]
**Describe the bug**
User receives 404 error when attempting to deposit this item: https://era.library.ualberta.ca/items/6809/draft/review_and_deposit_item

**Additional context**
This user reports experiencing this error on other objects

**Comment by seanluyk** [comment]
@mbarnett any status updates on this error? If this is something we can fix, please let me know!

**Comment by mbarnett** [comment]
Yes Sean, it is something we can fix, and as soon as I have the opportunity to address it, I will do so.

**Comment by seanluyk** [comment]
Thanks, @mbarnett, much appreciated, and my apologies that I'll be adding some more in here reported to ERAHelp soon too

**Comment by mbarnett** [comment]
No problem, report away. That way we can at least keep track of them and I can fix a bunch in one swoop.

In the spirit of establishing some realistic expectations for ticket response timelines: radio silence is probably going to be the norm for at least a week on anything you report at the moment, if it’s valid, until we either need more information or have it fixed. If it’s not something we’re able to fix, you’ll hear something a lot sooner.

(Production data issues with Fedora are basically my responsibility alone for both "has the legacy knowledge" and has-permission-to-monkey-around-on-Prod reasons, so unless something is an emergency it's just going to take me some time to get to them. We don't have the resources to provide more comprehensive coverage and keep the migration moving forward simultaneously, but once we're through that gauntlet it _should_ be smoother sailing.)

**Comment by mbarnett** [comment]
Update: I think I've identified a fairly non-invasive way to automatically remediate this at time-of-deposit; if so, this should resolve all reported issues involving any kind of 404 during a deposit or edit without me having to sink a lot of time into resolving each individual issue.

Working on testing it right now, will likely be able to work with Henry on getting it out to Prod over the next couple of days.

**Comment by seanluyk** [comment]
@mbarnett that would be fantastic, thank you for your continued work on this!

**Comment by mbarnett** [comment]
Ok, I believe these should all now be resolved, and this should be true for anybody reporting any kind of 404 when they tried to edit or deposit an item.

If you run into anybody still reporting issues that look like that after around 10:30 this morning, let me know asap.

**Comment by seanluyk** [comment]
@mbarnett thanks, we'll let you know if any of these issues crop up again by creating a GitHub issue

**Comment by mbarnett** [comment]
Sounds good. Things look pretty stable on my end, so I'm closing this for now.
