### ISSUE TITLE
Community - adding a logo image

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/jupiter#1893]
**Describe the bug**
I know that community editing is currently blocked for admin users, but I'm wondering if it's possible to edit the logo for [this collection](https://era.library.ualberta.ca/communities/27626edf-6c45-4350-ada7-b594a7c20905)?

Apparently, there's a government organization named ERA, so this group is hoping to avoid any confusion between the two.  

![Energy-Efficiency-Alberta](https://user-images.githubusercontent.com/14880206/94319045-09c6b600-ff47-11ea-8edc-563e04339adc.jpg)

**Comment by mbarnett** [comment]
It looks like I should be able to do this from the backend without breaking anything; I'll give this a shot when I have an opportunity (likely next couple of days, will update when it happens)

**Comment by seanluyk** [comment]
@mbarnett perfect, thanks very much!

**Comment by mbarnett** [comment]
Finally had a chance to tackle this, the logo is updated now.

**Comment by seanluyk** [comment]
Much appreciated, thanks so much @mbarnett!
