### ISSUE TITLE
Community description update request - Centre for Teaching and Learning

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/jupiter#1963]
The Centre for Teaching and Learning would like their community description to read:

The Centre for Teaching and Learning (CTL) supports instructors and programs to develop engaging and meaningful learning experiences for students. In addition to offering a variety of programming (including one-on-one consultations, workshops related to teaching and curriculum, and facilitating teaching grants and awards), CTL academic staff are actively involved in disseminating and co-disseminating their CTL-related work to inform and advance practice. Find some of our reports, resources, presentations, and scholarly publications here.

**Comment by mbarnett** [comment]
This should, finally, now be updatable. As should all Community logos, Community and Collection descriptions, etc, etc.

Our long national nightmare is at an end.

**Comment by mbarnett** [comment]
Closing since this should now be self-servable. Feel free to reopen or file a new issue if the user is still experiencing issues.
