### ISSUE TITLE
Fwd: Internal Server Error

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1996]
Submitted via email from:Era.Helpdesk@ualberta.ca

Hello Dev Team,

I didn't think this warranted a GitHub issue as I suspect it's an issue
with the file, but let me know if you'd like me to create one and I can.
I've attached the item in question.

Cheers,

Sean

---------- Forwarded message ---------
From: Carmen Loconte <carmen.loconte@ualberta.ca>
Date: Mon, Nov 23, 2020 at 9:08 AM
Subject: Internal Server Error
To: - erahelp <Era.Helpdesk@ualberta.ca>

Good morning,

I've been able to deposit all other pdfs in this series except this one.
This is the error I get?  Any ideas?

Thanks!
Carmen

4-2-Autres-options-d'acces.pdf<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML
2.0//EN"> <html><head> <title>500 Internal Server Error</title>
</head><body> <h1>Internal Server Error</h1> <p>The server encountered an
internal error or misconfiguration and was unable to complete your
request.</p> <p>Please contact the server administrator at root@localhost
to inform them of the time this error occurred, and the actions you
performed just before this error.</p> <p>More information about this error
may be available in the server error log.</p> </body></html>

-- 
Carmen Loconte
Information Services Specialist
Rutherford South
Edmonton, AB
Canada T6G 2J4
Phone: 780-492-8874
email: carmen.loconte@ualberta.ca

--

**Comment by seanluyk** [comment]
Hi @mbarnett any status updates on this issue? I've received another report from a staff member of issues with some other files in this collection. The files themselves are in French, so I'm wondering if this is an issue with the files themselves?  I'll request access to the files in question

**Comment by mbarnett** [comment]
I have a partial update, and it's only kind of that the files are in French – it's the filenames, specifically in the first case the apostrophe in the file name. Remove that and it deposits fine.

I haven't had a chance to dig into why the file name even matters or where exactly it's causing something to go wrong, though, so I don't have any kind of update on when we could fix this properly. It seems like it shouldn't be hard, but off-hand it also seems like it shouldn't be any issue to begin with.

**Comment by seanluyk** [comment]
Sounds good, thanks, Matt, I'll let them know

**Comment by mbarnett** [comment]
Interestingly I wasn't expecting Fedora to have been the source of the problem here, but I just gave it a show and you can deposit this file just fine, apostrophe and all, with the new deployment.

**Comment by mbarnett** [comment]
Closing since this appears to be fixed after testing some more files with names in different languages. Please reopen or file a new issue if you hear from users that they're still experiencing this, as I'd really like to nail this down if it's still happening.
