### ISSUE TITLE
Weirdness in Additional fields 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/jupiter#2040]
**Describe the bug**
In macOS 11, Chrome, I'm noticing some characters in the following fields appear (additional fields):
- Additional contributors
- Is this item about a place? 
- Is this item about a time?
- Citations for previous publication

When you type in these fields, a colon appears  

**To Reproduce**
1. Go to and item's edit page
2. Expand additional fields
3. See error, type to see additional behaviour

**Screenshots**
<img width="1135" alt="Screen Shot 2020-12-17 at 10 43 42" src="https://user-images.githubusercontent.com/14880206/102523807-4c36f500-4055-11eb-9a8f-d564caaee1fb.png">

**Desktop (please complete the following information):**
 - macOS 11
 - Chrome

**Comment by mbarnett** [comment]
Weiiiird. Not happening on macOS 10.15 and Safari or Firefox. Looking into it...

**Comment by seanluyk** [comment]
This is extra weird. I went back to the item where I noticed this error and it's no longer there: https://doi.org/10.7939/r3-wbrq-9945

Maybe it's my eyes!

**Comment by mbarnett** [comment]
Shane took a stab at recreating with Chrome on Mac and Windows and couldn't turn anything up either. Maybe something really transitory happened with Javascript the first time you tried it?

**Comment by seanluyk** [comment]
Most likely, I tend to find weird issues. I'll keep an eye out for this though

**Comment by mbarnett** [comment]
Going to close this since I can't for the life of me recreate, but reopen if you catch it in action again.
