### ISSUE TITLE
embargo_history, and visibility_after_embargo are needed for Embargo functionality

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#205]
As part of the migration preparation, we've confirmed that:

- [ ]  we need the embargo_history property to keep track of the history of past embargoes, in this format:
```An expired embargo was deactivated on _embargo-expire-date_.  Its release date was _embargo-deactivation-time_.  Intended visibility after embargo was _visibility_after_embargo_```

- [ ]  we will need visibility_after_embargo to keep track of the required visibility after embargo expiration date. (In most case this defaults to "public", but there are use cases where visibility after embargo needs to be "authenticated")

Both properties are available on the embargo object in current HydraNorth, and it will be mapped to new predicates recommended by metadata team.

**Comment by zschoenb** [comment]
is there a need, then for a `embargo_deactivation_time` predicate also?

**Comment by weiweishi** [comment]
No @zschoenb there won't be an attribute as "embargo_deactivation_time". It should use the system time at the time of the embargo lifting in the embargo_history message. Close this ticket as the attributes mentioned above as added as part of #251
