### ISSUE TITLE
Sort direction index nil error

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#2085]
https://rollbar.com/ualbertalib/jupiter/items/1192/

TypeError: no implicit conversion from nil to integer.

Need a fallback for this.

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/jupiter/issues/2077

**Comment by pgwillia** [comment]
This is a duplicate of https://github.com/ualbertalib/jupiter/issues/2077

**Comment by ConnorSheremeta** [comment]
Didn't see that one, thanks for the heads up! Closing this in favour of the previous issue.

**Comment by pgwillia** [comment]
No problem.  You've probably seen 
![image](https://user-images.githubusercontent.com/1220762/104361253-70101e00-54cf-11eb-8689-ed46c16679f3.png)

We can use it to create and link issues between the two systems.
