### ISSUE TITLE
Namespaces for the Vocabulary code

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#2118]
Just as a general note, let's add a ticket to the backlog to introduce the concept of "namespaces" to the vocabulary code and these validators, to clean up the prefix everywhere.

_Originally posted by @mbarnett in https://github.com/ualbertalib/jupiter/pull/2089#discussion_r564121095_

Before
`validates :rights, presence: true, uri: { in_vocabulary: :digitization_rights }`

After
`validates :rights, presence: true, uri: { namespace: :digitization, in_vocabulary: :rights }`

Before
`CONTROLLED_VOCABULARIES[:digitization_resource_type].txt`

After
`Digitization::CONTROLLED_VOCABULARIES[:resource_type].txt`

**Comment by mbarnett** [comment]
Just to note, API wise it will probably be easier to refactor towards & implement something like `CONTROLLED_VOCABULARIES.digitization[:resource_type].txt` or `CONTROLLED_VOCABULARIES[:digitization][:resource_type].txt`

**Comment by mbarnett** [comment]
This is now done with that PR I believe?

**Comment by pgwillia** [comment]
Yes!
