### ISSUE TITLE
accessibility check [ WIP ]

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#220]
Error:
On deposit form
missing form labels 
* Visibility field
* Communities and Collections field

Empty link:
* The Remove link for the "Communities and Collections" 

On search result page:
* Thumbnail on the item search result page

Alert:
On item detail page:
* A main element or main landmark is presented (broken same-page link)
On item search page:
* heading level on title is skipped.

**Comment by murny** [comment]
I believe this is all fixed now? Feel free to reopen if it is not
