### ISSUE TITLE
Replace DataCite EZID API Calls W/ DataCite REST API

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#2268]
The EZID Compatibility API is sunsetting at the end of this year, per https://blog.datacite.org/sunsetting-of-the-ez-api/

We'll need to switch over to their normal API. A cursory glance at GitHub didn't turn out any useful gems (the only thing I saw was one project that hadn't seen an update in over 6 years), so we may need to wrap this ourselves.

**Comment by pgwillia** [comment]
https://rubygems.org/gems/datacite seems to do most of what we need at this point.
```
client = Datacite::Client.new(username: "foo",
                              password: "bar",
                              host: "api.test.datacite.org")
```

https://github.com/ualbertalib/jupiter/blob/3e2d4ae5cd3bc3b1f227b843a725dc1b34d5f10a/app/services/doi_service.rb#L27-L49
Looks like this will be two steps to 1. create and 2. add [attributes](https://support.datacite.org/docs/api-create-dois#create-a-findable-doi)
```
result = client.autogenerate_doi(prefix: '10.0001')
attributes = {
      "event": "publish",
      "doi": "10.5438/0012",
      "creators": [{
        "name": "DataCite Metadata Working Group"
      }],
      "titles": [{
        "title": "DataCite Metadata Schema Documentation for the Publication and Citation of Research Data v4.0"
      }],
      "publisher": "DataCite e.V.",
      "publicationYear": 2016,
      "types": {
        "resourceTypeGeneral": "Text"
      }
result = client.update(id: '10.0001/bc123df4567', attributes: attributes)
```

https://github.com/ualbertalib/jupiter/blob/3e2d4ae5cd3bc3b1f227b843a725dc1b34d5f10a/app/services/doi_service.rb#L51-L76
```
attributes = {
      "event": "publish",
      "doi": "10.5438/0012",
      "creators": [{
        "name": "DataCite Metadata Working Group"
      }],
      "titles": [{
        "title": "DataCite Metadata Schema Documentation for the Publication and Citation of Research Data v4.0"
      }],
      "publisher": "DataCite e.V.",
      "publicationYear": 2016,
      "types": {
        "resourceTypeGeneral": "Text"
      }
result = client.update(id: '10.0001/bc123df4567', attributes: attributes)
```
https://github.com/ualbertalib/jupiter/blob/3e2d4ae5cd3bc3b1f227b843a725dc1b34d5f10a/app/services/doi_service.rb#L78-L80
I don't see an option to delete/remove in the gem.  The docs https://support.datacite.org/reference/dois-2#delete_dois-id
```
require 'uri'
require 'net/http'
require 'openssl'

url = URI("https://api.test.datacite.org/dois/id")

http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true

request = Net::HTTP::Delete.new(url)

response = http.request(request)
puts response.read_body
```
Which isn't what we were doing.  I don't know if there is an equivalent to `status: "#{Ezid::Status::UNAVAILABLE} | withdrawn", export: 'no'`

**Comment by pgwillia** [comment]
Maybe this is equivalent to withdrawn?
```
request.body = "{\"data\":{\"attributes\":{\"event\":\"hide\"}}}"
```

**Comment by johnhuck** [comment]
It looks like the EZ API used its own terms for the 3 DOI states. [1] shows a table with the equivalent native DataCite terms. The state determines whether you are allowed to delete. EZ API had Reserved, Public, and Unavailable [2]. Deletion is an action that can only be applied to a Reserved DOI.

If you need to withdraw a DOI after it has been made public, you change the status to Unavailable, provide a reason (that's what "withdrawn" is in your example) and provide an updated URL that points to a tombstone page (which you are responsible for creating).

The official DataCite states are Draft (=Reserved), Findable (=Public), and Registered (=Unavailable).  I think everything works the same and it's just the names that are different.

I can't tell what the difference is between the the REST API and the MDS (Metadata Store) API. They both seem to do the same thing. However, there is more descriptive information on the MDS API documentation, which may help you sort out how the REST API is supposed to work.

[[1] DOI States](https://support.datacite.org/docs/doi-states)
[[2] EZ API docs](https://web.archive.org/web/20200812004423/https://support.datacite.org/docs/datacite-ez-api-guide)

**Comment by pgwillia** [comment]
ezid metadata was fairly flat
```
{
      datacite_creator: @item.authors.join('; '),
      datacite_publisher: PUBLISHER,
      datacite_publicationyear: @item.sort_year.presence || '(:unav)',
      datacite_resourcetype: DATACITE_METADATA_SCHEME[@item.item_type_with_status_code],
      datacite_resourcetypegeneral: DATACITE_METADATA_SCHEME[@item.item_type_with_status_code].split('/').first,
      datacite_title: @item.title,
      target: Rails.application.routes.url_helpers.item_url(id: @item.id),
      # Can only set status if been minted previously, else its public
      status: @item.private? && @item.doi.present? ? UNAVAILABLE_MESSAGE : Ezid::Status::PUBLIC,
      export: @item.private? ? 'no' : 'yes'
    }
```

I think the same thing for the datacite api would be 
```data: {
      type: "dois",
      attributes: {
        prefix: prefix,
        identifiers: {
          identifier: Rails.application.routes.url_helpers.item_url(id: @item.id)
        },
        creators: {
          name: @item.authors.join('; ')
        },
        titles: {
          title: @item.title
        },
        types: {
          resourceType: DATACITE_METADATA_SCHEME[@item.item_type_with_status_code],
          resourceTypeGeneral: DATACITE_METADATA_SCHEME[@item.item_type_with_status_code].split('/').first
        },
        publisher: PUBLISHER,
        publicationYear: @item.sort_year.presence || '(:unav)',
      }
    }
```

**Comment by pgwillia** [comment]
Or rather we want these: https://support.datacite.org/docs/api-create-dois#create-a-findable-doi
```
{
  "data": {
    "id": "10.5438/0012",
    "type": "dois",
    "attributes": {
      "event": "publish",
      "doi": "10.5438/0012",
      "creators": [{
        "name": "DataCite Metadata Working Group"
      }],
      "titles": [{
        "title": "DataCite Metadata Schema Documentation for the Publication and Citation of Research Data v4.0"
      }],
      "publisher": "DataCite e.V.",
      "publicationYear": 2016,
      "types": {
        "resourceTypeGeneral": "Text"
      },
      "url": "https://schema.datacite.org/meta/kernel-4.0/index.html",
      "schemaVersion": "http://datacite.org/schema/kernel-4"
    }
  }
}
```

@johnhuck do you know what `schemaVersion` would represent for us?

**Comment by pgwillia** [comment]
DOIs are updated when certain fields change
https://github.com/ualbertalib/jupiter/blob/3e2d4ae5cd3bc3b1f227b843a725dc1b34d5f10a/app/models/jupiter_core/doiable.rb#L79-L84
causing the `altered!` event
https://github.com/ualbertalib/jupiter/blob/3e2d4ae5cd3bc3b1f227b843a725dc1b34d5f10a/app/models/jupiter_core/doiable.rb#L54-L59
which marks the object `awaiting_update`
https://github.com/ualbertalib/jupiter/blob/3e2d4ae5cd3bc3b1f227b843a725dc1b34d5f10a/app/models/jupiter_core/doiable.rb#L36-L38
and queues an update job
https://github.com/ualbertalib/jupiter/blob/3e2d4ae5cd3bc3b1f227b843a725dc1b34d5f10a/app/models/jupiter_core/doiable.rb#L90-L92
The job won't run if `awaiting_update` isn't marked
https://github.com/ualbertalib/jupiter/blob/3e2d4ae5cd3bc3b1f227b843a725dc1b34d5f10a/app/services/doi_service.rb#L52

**Comment by pgwillia** [comment]
- need to check if anything needs to happen to existing dois?
  - [ ] can existing (ezid) doi's be found and updated?

**Comment by pgwillia** [comment]
A number of dois have been generated with Datacite api including https://era.library.ualberta.ca/items/525bfc1f-4333-4a10-aa2a-40930be459f7
