### ISSUE TITLE
Facets on mobile

### ISSUE THREAD

**Issue by cwant** [ualbertalib/jupiter#230]
We need to figure out a good way to handle facets on mobile. Current wireframes show them as a dropdown, which may not provide the best design/UX.

Some examples:

* Popup on the side:
  * http://store.steampowered.com/search/?filter=globaltopsellers
  * https://epl.bibliocommons.com/v2/search?frbr=false&locked=false&pagination_page=1&query=cats&searchScope=CAN-EPL&searchType=keyword&sort=relevancy
* Hierarchy of separate pages: https://www.amazon.com/s?rh=i%3Aaps%2Ck%3Atile&keywords=tile&ie=UTF8&qid=1508948716

**Comment by sfbetz** [comment]
Confirmed with user testing. Users had to scroll through long list of confusing filters to get to their results and use of facets in mobile was not as clearly understood as on desktop.

My preference is for the bibliocommons approach: button labelled "filter results" opens filter options on the left hand side. User can select multiple filters. Header of filter menu should just say "Filter results" with "close" button on RH side of menu.
eg: 
https://epl.bibliocommons.com/v2/search?frbr=false&locked=false&pagination_page=1&query=cats&searchScope=CAN-EPL&searchType=keyword&sort=relevancy
