### ISSUE TITLE
Support for case insensitive sorting for search/query in Jupiter

### ISSUE THREAD

**Issue by cwant** [ualbertalib/jupiter#231]
When working on Community sorting, I expected "The department of cat" to be before "The Department of Everything", which wasn't the case.

There should be support for case insensitive sorting (it probably should be the default).

**Comment by mbarnett** [comment]
Pretty sure we just need to tweak the solr config xml soup, but I'll look at it

**Comment by mbarnett** [comment]
Closing, as it sounds like we've now fixed this in Chris' branch with #237
