### ISSUE TITLE
Collection Detail Page (User)

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#247]
To do:
- [x] Collection detail page use the search result display to show list of objects, including faceting, pagination, and sorting (replace #187)

Wireframe is here
![collection detail](https://user-images.githubusercontent.com/2047614/32682279-f60506a0-c630-11e7-95c0-410d7eadc14a.png)

**Comment by cwant** [comment]
WIP PR #271 issued, but blocked by PR #244

**Comment by cwant** [comment]
This one is done.
