### ISSUE TITLE
Item deposit form - Upload Item

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#254]
Wireframe:
![Image of Upload items Mockup](https://jupiter.mybalsamiq.com/mockups/6172847.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Deposit%20-%20Upload%20files

Done when:
- [x] user can attach file(s) from file browser 
- [x] progress bar updated
- [ ] uploaded file(s) will be characterized
  - Should only happen on the deposit? Not in draft?

**Comment by murny** [comment]
Best file upload libraries for this seem to be:
https://github.com/tors/jquery-fileupload-rails (rails gem for https://github.com/blueimp/jQuery-File-Upload)
https://github.com/ncuesta/dropzonejs-rails (rails gem for https://github.com/enyo/dropzone)

Need to look into both libraries to see what abilities they have for sorting/reordering the downloads etc.
