### ISSUE TITLE
Additional properties for community's rails data model

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#256]
These fields need to be added to the community's rails data model:

- [ ] fedora3UUID, predicate ual:fedora3UUID, no need to be on UI, not a required field
- [ ] creator, predicate dcterms:creator, no need to be on UI. (pending answers to the following question)

Question:
- depositor vs creator in https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profiles/community/profile.json. Which one we need to use to keep track of the creator of the community? can depositor be someone other than era admin in the existing data? Do we need to carry that data forward? @ualbertalib/metadata-team 

- how are (or will) write permissions controlled on the collection/community level? (Edit, deposit in, delete) @mbarnett @murny

**Comment by murny** [comment]
- Write permissions are controlled by the user's role (either your an admin or not an admin). Has nothing to do with the object in this case for community/collection (since non admins cannot create/edit these objects)
