### ISSUE TITLE
Item deposit form - progress bar

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#261]
wireframe:

![deposit - describe item](https://user-images.githubusercontent.com/2047614/32847817-4217851c-c9e8-11e7-890f-e7b78391c56d.png)

Wireframe is for reference only. 

Done when:
- [x] implement a progress bar with the deposit form
- [x] status will be updated with user actions on the form to reflect where the user currently is
- [x] can provide navigation to the user to go backward or forward if possible
- [x] future incomplete steps are not navigable

**Comment by murny** [comment]
Found a gem that I will try to use to do the heavily lifting for this wizard/multi step form: https://github.com/schneems/wicked

Will go forward with this and try hooking this up. Gem looks like it is agnostic with what we choose for storing the draft (activerecord or activefedora)
