### ISSUE TITLE
Docker Demo fails to startup: bad URI error

### ISSUE THREAD

**Issue by jefferya** [ualbertalib/jupiter#2610]
**Describe the bug**
Following the Demo instructions with Docker `Docker version 20.10.10, build b485636` and docker-compose `version 1.29.2` startup of the `web` container fails with `bad URI(is not URI?): "'redis://redis/1'" (URI::InvalidURIError)`

**To Reproduce**
1. Install latest Docker: version 20.10.10
2. Install latest docker-compose: version 1.29.2
3. clone repo 5c8bfce (head of the main branch)
4. `docker-compose -f docker-compose.yml up -d` fails to start `web` container with error  `bad URI(is not URI?): "'redis://redis/1'" (URI::InvalidURIError)`

**Expected behavior**
`web` container starts normally with connection to redis

**Desktop (please complete the following information):**
Ubuntu 20.04

**Additional context**

https://github.com/ualbertalib/jupiter/blob/5c8bfce347e951bb99c0026c21ec87a946b3f1d1/docker-compose.demo.yml#L37

**Comment by jefferya** [comment]
New versions of docker-compose, if I understand some of the reports, became subtly more strict when interpreting yaml.

**Comment by murny** [comment]
Believe this can be closed now, should be fixed by #2611
