### ISSUE TITLE
Faceting/Searching of items on admin user detail page

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#262]
Wireframe:
![user detail](https://user-images.githubusercontent.com/2047614/32848858-c71edb82-c9ea-11e7-9e82-6cd8a6bb911c.png)

Bringing faceting and searching, and standard search result list for items on admin user detail page. Paginating and Sorting are already available.

**Comment by cwant** [comment]
This one is blocked by PR #271 (will reuse code from there).

**Comment by cwant** [comment]
The block on this one has been removed.
