### ISSUE TITLE
Faceting/Paginating/Searching/sorting of items on admin items view

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#263]
Wireframe:
![items](https://user-images.githubusercontent.com/2047614/32849003-37f29d30-c9eb-11e7-94b3-4015841864b4.png)

Done when:
- [ ] items are listed with the standard search result list
- [ ] including faceting/pagination/sorting/searching on the page.

**Comment by cwant** [comment]
This one is blocked by PR #271 (will share a lot of code with that one).

**Comment by cwant** [comment]
The block on this one has been removed.

**Comment by cwant** [comment]
Actually, this one is now blocked by work on #262 (will reuse code from there).

**Comment by cwant** [comment]
Yep, was done in #502. This issue may have been kept open since mobile wasn't really addressed in that PR -- I assume that mobile now works (?).

**Comment by mbarnett** [comment]
Yep, I just checked and it appears to be working on mobile too. Closing.
