### ISSUE TITLE
[Spike] Will PMPY shared filesystem architecture work in a cloud environment?

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#2634]
Spike questions:
- What kind of storage do we have reserved?
- Can we do things like FileUtils.copy_file from remote storage?

Context:
Jupiter provides a file path:
https://github.com/ualbertalib/jupiter/blob/adfac5f7dadca913f83f184db8ff7b14fa8fd8b9/app/controllers/aip/v1/entities_controller.rb#L206-L213

PMPY copies the file
https://github.com/ualbertalib/pushmi_pullyu/blob/2e4f5fa1112a13d117738cc478d11d1ea73fa445/lib/pushmi_pullyu/aip/downloader.rb#L64

**Comment by murny** [comment]
Will PMPY live in the cloud? If so, then PMPY shouldn't even exist? It only exists today for the sole reason of being super extra safe by having multiple firewalls. The main reason we built it the way it is, we wanted multiple layers between Swift and the scary world outside. If PMPY lives in the cloud, then this makes no sense anymore.

Jupiter should just be using Sidekiq. Any time an Item/Thesis gets created/updated/etc, it will just queue up a sidekiq job. The sidekiq job will then do the packaging and uploading to Swift. No extra app needed.

**Comment by pgwillia** [comment]
Nice zoom out.  I was thinking in a little tiny box. Should be thinking about preservation, not necessarily the existing box.
