### ISSUE TITLE
Authentication failure Jupiter 2.1.0

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#2636]
**Describe the bug**
Working on deploying 2.1.0 and @henryzhang87 realized on staging that authentication wasn't working
![image](https://user-images.githubusercontent.com/1220762/143277644-6027ee1f-4c20-4a9b-a771-121e33358658.png)

**To Reproduce**
1. Go to 'Log In"
2. Enter your credentials and submit

**Expected behavior**
Login should result in authenticating the user.

**Additional context**
```
I, [2021-11-24T09:02:07.978027 #25179]  INFO -- : [e9e2bcaa-0463-4d70-a5e8-1348ba917d07] Started POST "/auth/saml" for 129.128.46.142 at 2021-11-24 09:02:07 -0700
D, [2021-11-24T09:02:07.978659 #25179] DEBUG -- : [e9e2bcaa-0463-4d70-a5e8-1348ba917d07] (saml) Request phase initiated.
D, [2021-11-24T09:02:07.979565 #25179] DEBUG -- : [e9e2bcaa-0463-4d70-a5e8-1348ba917d07] Created AuthnRequest:  ...
I, [2021-11-24T09:02:08.356199 #25179]  INFO -- : [ec66473f-e1e3-4366-a246-bab1cb734676] Started POST "/auth/saml/callback" for 129.128.46.142 at 2021-11-24 09:02:08 -0700
D, [2021-11-24T09:02:08.357628 #25179] DEBUG -- : [ec66473f-e1e3-4366-a246-bab1cb734676] (saml) Callback phase initiated.
E, [2021-11-24T09:02:08.371894 #25179] ERROR -- : [ec66473f-e1e3-4366-a246-bab1cb734676] (saml) Authentication failure! Garbage component exists at the end: <]>: </p:Response[@ID=$id]/ds:Signature]>: REXML::ParseException, Garbage component exists at the end: <]>: </p:Response[@ID=$id]/ds:Signature]>
I, [2021-11-24T09:02:08.372369 #25179]  INFO -- : [ec66473f-e1e3-4366-a246-bab1cb734676] Processing by SessionsController#failure as HTML
I, [2021-11-24T09:02:08.372498 #25179]  INFO -- : [ec66473f-e1e3-4366-a246-bab1cb734676]   Parameters: {"SAMLResponse"=>"..."}
W, [2021-11-24T09:02:08.372635 #25179]  WARN -- : [ec66473f-e1e3-4366-a246-bab1cb734676] HTTP Origin header (https://login-uat.ualberta.ca) didn't match request.base_url (https://era-app-stg-1.library.ualberta.ca)
I, [2021-11-24T09:02:08.372936 #25179]  INFO -- : [ec66473f-e1e3-4366-a246-bab1cb734676] Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms | Allocations: 136)
F, [2021-11-24T09:02:08.373329 #25179] FATAL -- : [ec66473f-e1e3-4366-a246-bab1cb734676]
[ec66473f-e1e3-4366-a246-bab1cb734676] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
[ec66473f-e1e3-4366-a246-bab1cb734676]
[ec66473f-e1e3-4366-a246-bab1cb734676] config/initializers/omniauth.rb:22:in `block (2 levels) in <main>'
```

**Comment by pgwillia** [comment]
Looks like a bug in a combination of our dependencies (https://github.com/ualbertalib/jupiter/blob/jupiter-2.1.0/Gemfile.lock#L369 + https://github.com/ualbertalib/jupiter/blob/270ecb395a59f4a1749158270be9661727f94f1d/Gemfile.lock#L393) is to blame:  https://github.com/onelogin/ruby-saml/issues/577

**Comment by pgwillia** [comment]
It looks like we have a later version of ruby-saml with the fix in 2.2.0.
https://github.com/ualbertalib/jupiter/blob/fa2a8ba74a11e693d05aef2548d5b5cc68b99e60/Gemfile.lock#L471

I'll see if I can hot fix the 2.1.0 tag and release 2.1.1.

**Comment by murny** [comment]
Isn't the issue the new URL for our staging (era-app-stg-1)? 
>  HTTP Origin header (https://login-uat.ualberta.ca) didn't match request.base_url (https://era-app-stg-1.library.ualberta.ca)

Where we expect "https://era-test.library.ualberta.ca"?

https://github.com/ualbertalib/jupiter/blob/master/config/secrets.yml#L129-L135

**Comment by pgwillia** [comment]
Confirmed that neither era-app-stg1.library not era-test.library.ualberta.ca as saml secrets worked.  Did a dry run of the Gemfile.lock changes I proposed and it works!  I'll cut 2.1.1 now.
