### ISSUE TITLE
Item(s) missing subjects

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#2639]
While reviewing the AIPs for preservation, I discovered that the subject metadata for an item (https://doi.org/10.7939/r3-3376-kc33) is not in ERA even though it is in the AIP.

According to the AIP the subject (with an obvious typo when it was entered) should be "ustainable Synthesis of Nanoscale Zerovalent IronParticles for Environmental Remediation" but instead there is no subject listed.

I suspect this may have to do with the bug identified during first pass at the recent deployment.

This item was ingested in March of 2021.

You can see other items with this issue. For example, if you navigate to the Images of Research 2021 collection (https://era.library.ualberta.ca/communities/e14a6354-b557-4a15-8e99-70ad237be121/collections/6e34a932-d48f-446f-a4f8-577ffabd0edf) you can see the list of subjects on the left. If you click on Computational Chemistry, you get the one item (https://doi.org/10.7939/r3-mjad-8c46) returned, but if you click on it the subject(s) don't display. Although they must be there since the faceting is working

**Comment by pgwillia** [comment]
Yes.  We know about this and are working to resolve it presently.

**Comment by sfarnel** [comment]
Thanks @pgwillia !
