### ISSUE TITLE
Increased database load after 2.1.1 deployment

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#2642]
**Describe the bug**
Likely unoptimized queries

**Expected behavior**
Deployments don't have a visible impact on performance.

**Additional context**

Nagios has been reporting high load averages on the database server used by Jupiter (and only Jupiter). 
There was definitely a bigger bump starting on the 28th, Sunday:
![image](https://user-images.githubusercontent.com/1220762/144089652-a3ee1eaa-8668-47d7-9842-d7650f8d526b.png)

Also, here's the trace from Netdata- it's intermittent, this one with duration ~3 minutes:
![image](https://user-images.githubusercontent.com/1220762/144089733-1bd36b31-018a-45b0-a669-b24cf8558d03.png)

The plugin for Postgres definitely shows an increase in the number of DB connections, to the Jupiter database, at that time, so I think it's being driven from the web application side:
![image](https://user-images.githubusercontent.com/1220762/144110973-2f9da78f-5c48-41e9-a949-1b0ad8374048.png)

DIT-DEVTEAM:   Have there been any recent changes to the application that might be causing this?

Henry, command line history says you were all over that server, last Friday.  Ideas?

This VM has 8Gb of memory & 4 CPU's; the database in the filesystem is only 2.2Gb:

    [root@pg-db-prd-primary-1 ~]# cd /var/lib/pgsql/
    [root@pg-db-prd-primary-1 pgsql]# du -sh .
    2.2G .

... so it ought to be wildly over-spec'd for this role.

My experience suggests: "Smells like an untuned query" (something updated recently?)

**Comment by murny** [comment]
Well the obvious one is Feature flags. As these are stored and pulled from the DB. Meaning every single request will now do an one extra additional lookup (its cached during the request). 

This shouldn't be a problem though? Not sure what else it could be? Be nice if they can tell us what the actual queries are for the increased load

**Comment by pgwillia** [comment]
Feature flags aren't until the next deployment 2.2.0.

**Comment by murny** [comment]
Oh interesting. Nevermind then! The mystery deepens 🤔

**Comment by pgwillia** [comment]
There's nothing jumping out at me 
https://github.com/ualbertalib/jupiter/compare/jupiter-2.0.3...jupiter-2.1.1

We fixed a bunch of errors in this release?

Rollbar doesn't have anything in that time frame.

I don't know how to get meaningful information from skylight
https://www.skylight.io/app/applications/Q2pLKz0AwRat/trends/current

Don't think its jobs related
![image](https://user-images.githubusercontent.com/1220762/144135092-503afe49-6a5b-47fd-ad86-0e6f579d01cb.png)

**Comment by pgwillia** [comment]
Probably corresponds with an uptick in use?

![image](https://user-images.githubusercontent.com/1220762/144136180-d95ad62c-cd31-4c63-b42c-3fa3be0a4330.png)
