### ISSUE TITLE
Item deposit form - controlled vocabulary/URI handling

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#265]
Requirements:
For generic item:
- [x] values of language, type,  license on the deposit form are from controlled vocabularies (details in https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_generic.md and #251 ) 
- [x] values should be presented in the UI as strings (a derived value in Solr?) and saved to Fedora/Triplestore as URI. 
For thesis item:
- [x] graduation date on the thesis deposit/edit form is also from a controlled vocabulary.

**Comment by sfarnel** [comment]
Just to confirm, the data dictionary includes text string value as well as URIs
