### ISSUE TITLE
Item deposit form - Second phase

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#269]
Ticket to track whats out of scope for "draft release" deadline for Item Deposit Form

Pre-beta:
- [x] display drafts on admin user detail/user dashboard #98 
- [x] Figure out thumbnail on Item View and ingest this into Fedora accordingly (is it the first file? or something smarter?) #19 
- [x] Multiple community/collection assignment 
  - Need to limit duplicate community/collection pairs (doesn't affect fedora though)? Button placements could use styling?
- Edit Item? #322 
- [x] issue with progress bar letting you click to a uncompleted step on error submission
- Figure out filename issue with regards to TempFile https://github.com/ualbertalib/jupiter/issues/400
- [x] validate link to related items?
  - Decision is to backburn this and wait for requirements. Removed link on item view since it's broken anways
- [x] look into file size limit (256 MB) on dropzone -> bumped to 1GB
- Beef up description/help on dropzone. PDF thumbnail should indicate that something happens

Post-beta?
- [x] Create CCID authenticated items (admin only? this is done already)
- Create private items (this not needed anymore?)
- Thesis Deposit with associated specialized metadata
- Loading... when deposit item button is pressed
- Date created check requirements? Optional month/day? Maybe use String field and cast to date so presence check works and allows for true optional month/day

**Comment by mbarnett** [comment]
I can handle the thumbnail as part of #19

**Comment by murny** [comment]
Most of this is done now. Closing out.
