### ISSUE TITLE
Possible indexing coverage issue?

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/jupiter#2726]
**Describe the bug**
A user contacted us to let us know they weren't able to find their [thesis](https://doi.org/10.7939/r3-tzss-f212) in Google Scholar. I wanted to check if there's a coverage issue here, as I wasn't able to find it through a Google search either

**To Reproduce**
1. Search Google and Google Scholar for "Disturbance Observer-Based Motion Control and Visual-Inertial-Actuator Odometry for UAVs"

**Expected behavior**
Theses appear in Google/Google Scholar search results

**Additional context**
Fall 2021 deposit

**Comment by seanluyk** [comment]
@leahvanderjagt tagging you for your reference

**Comment by leahvanderjagt** [comment]
@weiweishi Can you assign this issue, or would you like for us to talk to a specific team member? 

The student has shared with us that it seems like a problem with our site. The thesis is also not indexed in yahoo, bing etc and I spot checked 10 theses from the Fall 2021 set and found they are not indexed. 

Who is looking after Google Search Console issues, and Google and Google Scholar indexing for Jupiter? @sfarnel was/is the metadata team also involved in this?

**Comment by weiweishi** [comment]
Thanks for bringing this to my attention. We will work with the team to
look into this issue. There is not a point person for these indexing
problems. When issues arise, the team will decide internally who could work
on it and follow up with you and your team.

**Comment by pgwillia** [comment]
[Google Search Console](https://search.google.com/search-console?resource_id=https%3A%2F%2Fera.library.ualberta.ca%2F) has some more information about specific errors that are causing errors or exclusions.  In a similar period (December 6-12) [Data anomalies in Search Console](https://support.google.com/webmasters/answer/6211453#indexed&zippy=%2Cindex-coverage-report) admits to "An internal issue caused an increase of redirect errors during indexing, and associated email notifications. This was not due to any website issues, but was due to an internal Google issue. Pages that were dropped from the index have been scheduled for recrawling."    

![image](https://user-images.githubusercontent.com/1220762/151073021-6cd86d8d-c85c-442d-bfda-ca360978e23f.png)

**Comment by sfarnel** [comment]
Thanks all. Our team has been involved generally in defining the metadata
needed for Google Scholar indexing and ensuring it is implemented, but not
on the review and monitoring of analytics. It does look like the metadata
is what it should be, so perhaps it is what Tricia has noted and an issue
with Google.

-------------------------------------------------------

SHARON FARNEL, PhD, MLIS, MA
Head, Metadata Strategies
*she/her/hers*

UNIVERSITY OF ALBERTA
Library and Museums

5-25F Cameron Library
Edmonton, AB Canada T6G 2J8

[image: University of Alberta Logo] <https://www.ualberta.ca/index.html>

The University of Alberta respectfully acknowledges
that we are situated on Treaty 6 territory, traditional
lands of First Nations and Métis people.

**Comment by seanluyk** [comment]
Thanks for looking into this @pgwillia. So it's safe to say this isn't an issue on our end. I'll let the user know

**Comment by pgwillia** [comment]
This is Google's information about that particular thesis.  I don't think there is anything that we can do about this one until Google gets around to indexing the excluded content.
![image](https://user-images.githubusercontent.com/1220762/151211273-65dfd216-2175-4d42-bc41-1b9173e1c106.png)
More information about [urls not on google](https://support.google.com/webmasters/answer/9012289#url_not_on_google)

While we're looking at this Google suggests some actions that would improve mobile (and by extension desktop as well) usability 
![image](https://user-images.githubusercontent.com/1220762/151211843-76d11f5e-b8d6-4589-aa93-cef75a5e3d5d.png)

**Comment by seanluyk** [comment]
Thanks @pgwillia this is super helpful. I'll let the user know

**Comment by pgwillia** [comment]
Another angle on this is that the [Google Scholar documentation](https://scholar.google.ca/intl/en/scholar/inclusion.html#indexing) says:
> The publication date tag, e.g., citation_publication_date or DC.issued, must contain the date of publication, i.e., the date that would normally be cited in references to this paper from other papers. Don't use it for the date of entry into the repository - that should go into citation_online_date instead. Provide full dates in the "2010/5/12" format if available; or a year alone otherwise. This tag is required for inclusion in Google Scholar. 

This is the citation metadata that we're publishing
```
<!-- Google Scholar metadata -->
<meta name="citation_title" content="Disturbance Observer-Based Motion Control and Visual-Inertial-Actuator Odometry for UAVs">
<meta name="citation_author" content="Moeini, Amir">
<meta name="citation_publication_date" content="Fall 2021">
<meta name="citation_pdf_url" content="https://era.library.ualberta.ca/items/10d9b4cb-e1d8-4941-8fcf-4cc7ab6136d9/view/cdd2c3c5-f82f-4c38-8430-9e9d40a8d758/Moeini_Amir_202109_PhD.pdf">
<meta name="dc.identifier" content="doi:10.7939/r3-tzss-f212">
<meta name="citation_doi" content="doi:10.7939/r3-tzss-f212">
```

Perhaps Fall 2021 doesn't meet their spec.  We can adjust to just show the year.  Looks like [this was changed](https://github.com/ualbertalib/jupiter/commit/4cd2e8ff7d9bf8ee16bef370f6512c3eb8ceed84) in the 2.0.x releases.  Before just reverting the change we might want to look at if there are multiple use cases for date and add documentation about the differences.

**Comment by sfarnel** [comment]
Thanks @pgwillia dates are so essential but so tricky. I'll chat with @anayram about this so we can be sure to have a solid and sensible approach that doesn't inadvertently cause issues elsewhere

**Comment by anayram** [comment]
Sounds good @sfarnel, adding the following sample date from the Google Scholar documentation page for future reference:

`<meta name="citation_publication_date" content="1996/05/17">`

**Comment by seanluyk** [comment]
Item is in Google scholar, closing ticket
