### ISSUE TITLE
Remove "Explore ERA A+V" from ERA homepage

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/jupiter#2765]
With the move to Aviary and removal of the ERA A+V public interface, we can now remove the "Explore ERA Audio + Video" box/link on the ERA homepage. Since these are separate unrelated repositories I don't think we need to add a link to Aviary there in its place, as this has caused confusion for users in the past.

**Comment by pgwillia** [comment]
![image](https://user-images.githubusercontent.com/1220762/167488629-4cc53204-ed06-45f7-92da-98b625afd43b.png)

Remove the div for era-av and make the blank space look good.
