### ISSUE TITLE
Accommodate template changes in new batch ingest workflow

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#2853]
Changes to the new batch ingest workflow are needed in order to accommodate the new template and to have the header names used match more closely with the template’s header names. Changes to be done are listed below:

High priority
- [ ] #2931
  - Format  changed from MM/DD/YYYY to YYYY-MM-DD
  - Allow partial dates (YYYY-MM or YYYY).
- [x] #2943

Also requested
- [x] List of template headers that have been changed in the template to match the Jupiter code  (Work tracked in #2941):
  - alternative_title
  - item_type
  - owner_id - removed
  - subject
  - created
  - spatial_subjects
  - temporal_subjects
  - is_version_of
  - related_link
  - rights
  - 
- [ ] License/Rights: previously either License or Rights were required, no need to specify license_text in License. For instance, the user could just enter a rights statement and nothing in the License field. If this is too hard to change we can go with what we have right now, so this change is not a priority. Working tracked in #2942 

Related to: https://github.com/ualbertalib/jupiter/issues/1986

[Instructions to configure Google secrets](https://github.com/ualbertalib/di_internal/blob/master/Applications/Jupiter/Batch_Ingest/README.md)
[ERA Batch Ingest Templates (alfresco, item, legacy_thesis)](https://docs.google.com/spreadsheets/d/1RslH-4roDdbFER_Wa_oHB7mLTaMEmSYTfe6PcmxwG8s/edit#gid=0)

**Comment by pgwillia** [comment]
From @anayram 
> If it helps to split the request, the two priority items are:
- [ ] Dates
    Changes to (created) date field:
    Format changed from MM/DD/YYYY to YYYY-MM-DD
    Allow partial dates (YYYY-MM or YYYY).
- [ ] Need support for multiple files per item in new workflow. Previously done by delimiting multiple files in the same field with a |
