### ISSUE TITLE
Item view - Attribute display

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#294]
To prepare for the first round of user testing, item view needs to be updated to make it more usable. This includes:
![image](https://user-images.githubusercontent.com/2047614/33442067-78abe4fe-d5b1-11e7-9212-4f7efcb46f35.png)

- [ ] Move fields: Visibility, owner, and record created at to the bottom of the list
- [ ] make subject and creator show as links to search, and not in array with "[","]"
- [ ] make all links within the attributes point to faceted search results pages

The related wireframe is at:
![image](https://user-images.githubusercontent.com/2047614/33445506-39de4e02-d5ba-11e7-98e8-3ca131a2d9b3.png)

**Comment by cwant** [comment]
According to #251, `dcterms:identifier` should also be displayed in item view. Where do you guys envision it going? After DOI? At the end?

**Comment by weiweishi** [comment]
@leahvanderjagt where do you want the ids like Technical Report IDs and Structural Engineering Report IDs to appear on the item view page?

**Comment by weiweishi** [comment]
To give @cwant the definite answer to this question, based on our discussion:
For now, this field doesn't need to appear on the item view page.  We will not use dcterms:identifier for special ids. These special ids will be concatenated into the description field so that they are searchable. Metadata team will advise if this attribute can be eliminated entirely. Is this your understanding as well @leahvanderjagt @sfarnel

**Comment by sfarnel** [comment]
Thanks @weiweishi yes, that's my understanding as well. we have added this to the migration script and are re-generating a migration package. this property will be removed from the data dictionary.

**Comment by weiweishi** [comment]
No longer need identifier per conversation above. Close the issue.
