### ISSUE TITLE
Dev Environment

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#3]
I'm currently using HN2's `hydra:server` rake task and jupiter on a non-standard port. We should figure out how we want to provide local Fedora/Solr for dev going forward (possibly a Docker container? or port the rake task code?)

**Comment by mbarnett** [comment]
We can just continue w/ the rake task route for the time being, but if we have the bandwidth to get something else in place quickly, now would be a great time. It just needs a stock Fedora and Solr on accessible ports that we can point the app at, the solr config from the repo, and a way to create the right cores

**Comment by murny** [comment]
Docker would be very easy to provide for this. Especially if we are targeting latest versions. (we can do a lightweight docker-compose which only provides the datastores...mysql/solr/fedora/etc, but lets you keep using your local ruby/rails environment). I can do this once I start the User Auth work epic.

Big question to think about is whatever we do, it needs to work cleanly on travisCI as well.
