### ISSUE TITLE
Refinements for `search_term_for` (method that helps generate Solr search terms).

### ISSUE THREAD

**Issue by cwant** [ualbertalib/jupiter#300]
The current design doesn't cover a couple of use cases:

1) I need a search link, but I don't have an item handy. As an example, if I want to show all of the items owned by a specific user, I need to use search param `"owner_ssim:#{@user.id}"`. If I had an item on hand I could do `item.search_term_for(:owner)`, but  I don't. Shadowing `search_term_for` at the class level with something like `Item.search_term_for(:owner, @user.id)` would work.
2) Multi-valued fields. If an attribute has multiple values, we can't currently get a search term for one of them. E.g., `item.search_term_for(:subject)` currently produces something like `subject_tesim:"["Randomness", "Pictures", "Hamburger"]"`. Ideally I would like to have an optional second argument for `search_term_for` like `item.search_term_for(:subject, 'Hamburger)` so that I can just search for that subject. (Concrete use case is subject links in item view, part of #294).

**Comment by mbarnett** [comment]
1. The `solr_name_for` class method should get you where you want to go:

```ruby
"#{Item.solr_name_for(:owner, role: :search)}:#{@user.id}"
```

2. We could overload `item.search_term_for` to take a value, but all it's really doing is hiding the composition with a ':' character at that point

I think 

```ruby
"#{Item.solr_name_for(:subject, role: :search)}:Hamburger"
```

is probably ok?

**Comment by weiweishi** [comment]
Is there still any refactoring work required on this one? Should we group it with #344

**Comment by mbarnett** [comment]
I think this is pretty much done via some PRs in the last month or two? @cwant ?

**Comment by cwant** [comment]
Yes, we can call it done.
