### ISSUE TITLE
Restrict number of facets rendered

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#305]
![facets](https://user-images.githubusercontent.com/51773/33571044-0937b84e-d8ec-11e7-80dd-30ff5c30f807.jpeg)

At some point before launch, we'll want to not be rendering every single facet result for, say, Creators, or we'll have tens of thousands of rows rendering there.

**Comment by weiweishi** [comment]
Question: recommended number of facets returned? Are all facets treated equally?
