### ISSUE TITLE
ERA Batch Edit: BoardEx licensing terms

### ISSUE THREAD

**Issue by anayram** [ualbertalib/jupiter#3136]
**Brief description**
High priority request to replace current licensing terms used for BoardEx materials in ERA (143 items).

New licensing terms should read:
>PLEASE NOTE: BY VIEWING OR DOWNLOADING BOARDEX CONTENT, YOU ARE AGREEING TO THE FOLLOWING TERMS AND CONDITIONS:
>1. Use of this product is restricted to current faculty, staff, and students of the University of Alberta.
>2. Authorized user is granted a non-exclusive, non-transferable, and non-sublicensable right to use, reproduce and analyze the products, solely for the user’s internal research and educational purposes.
>3. Authorized user shall not use any deep-link, page-scrape, spider, robot, index, internet agent or other automatic device, program, algorithm or any other technology which does the same actions, to use, access, copy, acquire, input or store any products or information from the platform, or to search, generate searches or monitor any portion of the products.
>4. Authorized user shall not resell or re-license, share in any way, or reverse engineer the product or licensed data, or develop or attempt to develop any competing products or services.

**Item ids listing**
https://docs.google.com/spreadsheets/d/1ROqKihYwswJCPpsWVGFyGvzENc8rwfQc89M4UahqU4s

**Collection**
b41cdbfd-6af2-4a13-8ba6-59725565d445/82fbdb4f-1202-4123-acf5-96d7aeb874a5
[BoardEx Reports
](https://era.library.ualberta.ca/communities/b41cdbfd-6af2-4a13-8ba6-59725565d445/collections/82fbdb4f-1202-4123-acf5-96d7aeb874a5)

**Comment by pgwillia** [comment]
For the license update, I think we want the logging and structure of https://github.com/ualbertalib/jupiter/pull/1627/files#diff-19002e65c2a007798a7e165d8ad377132e236359727f1150de305ca682b13562 but as a rake task https://github.com/ualbertalib/jupiter/blob/master/lib/tasks/jupiter.rake like https://github.com/ualbertalib/jupiter/issues/1449#issuecomment-619273717

**Comment by pgwillia** [comment]
Connor and I chatted a bit about this. A script we run from the console might be the right size solution.  Then we can generalize to a rake task if/when this happens again.

- [ ] have logging to verify change
- [ ] get feedback about approach
- [ ] practice through test, staging, production
- [ ] have a second set of eyes available to prevent copy/paste errors

**Comment by ConnorSheremeta** [comment]
@anayram @seanluyk Due to formatting constraints the only way to display the license text currently is as one continuous block of text rather than a list with each item on an indented new line (which is how the text is laid out in the description of this issue above.) I have attached a screenshot of how this looks below. Would this layout be sufficient?

![Screenshot from 2023-05-25 10-10-28](https://github.com/ualbertalib/jupiter/assets/14242562/4db3006f-2d2a-47e9-84d4-9a912e96d245)

**Comment by seanluyk** [comment]
Hi Connor,

That will work just fine, thanks! CSU is aware of this limitation.

Sean

**Comment by ConnorSheremeta** [comment]
Will be running the scripts to complete this today, will report back by the end of day on how that went.

**Comment by ConnorSheremeta** [comment]
Ran the scripts on production alongside Omar today without issue. All 143 items now have licensing text matching the above screenshot. Thank you all for your assistance in this.
