### ISSUE TITLE
Admin Dashboard Setup

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#32]
DONE WHEN:

- [ ] admin_dashboard_controller created
- [ ] show view created
- [ ] /admin show route created
- [ ] authorization enforces only `User#admin?` allowed to visit these routes

**Comment by murny** [comment]
Most of this was done in https://github.com/ualbertalib/jupiter/pull/46.

Dashboard currently just mocked out, but has versions for jupiter/ruby/rails, Counts of objects (works, collections, Commmunties, users) and list of last 10 works/users that were created.

Authorization piece is also done.

Will update ticket once this is merged
