### ISSUE TITLE
Item edit after deposit

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#322]
- [ ] An edit form for item that has already been saved into Fedora
- [ ] connect to the deposit workflow so that user can still modify the item after it's published. 
@murny did I miss anything?

**Comment by mbarnett** [comment]
I'm thinking to start with I'll work on mapping the DraftItem properties into a Fedora-backed Item for use once it's published. That work for you @murny ?

**Comment by murny** [comment]
Yep that works. Let me know if you want any of those DraftItem properties to change so this is easier or less confusing.
