### ISSUE TITLE
Select2 tag creation on the Item deposit form (SPIKE)

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#323]
To investigate how to better handle the createTag in select2 for the item deposit form. 

Unlike other multi select boxes like languages, these taggable select boxes (creators/citations/places/subjects/etc) enable a user to create a new tag on the fly dynamically, which needs a bit more thought into how we may handle this.

How to do this? Heres two ways we might be able to handle this:

- Server Side:  Select2 by default will add both new dynamic tags and existing selections into an array. For example with authors this array may be `creator_ids` and might look like a mix of IDs and strings: `['1', '232', 'John Doe','Jane Smith']`. So without changing anything with select2, you can handle this all server side in your controller action. You take all the new tags (the strings in the array) and create them in the associated table (creator table). Then you link these to the join table for the creator and item just like you would do for the ids. Perhaps you can do something like this:
  ```
  params[:item_draft][creator_ids].each do |creator|
    # Check if creator is an ID or string and handle accordingly
    # if ID its an actual ID referencing a preexisting creator which you can just associate
    # else its a new tag which needs to be created then be associated)
    Item.creators.create(name: creator)
  end
  ```

- Client Side using Ajax: You can hook into the createTag event (https://select2.org/tagging#customizing-tag-creation) in select2. You may be able to fire an ajax post event to the server (create a json API for CRUDing each resource (creators/subjects/citations/etc/etc)) which will create this resource and return the id, which can be used to update the form. Then on form submission you are only sending the list of ids for the resource and everything should work accordingly.

**Comment by murny** [comment]
Pretty much resolved now. Decided to remove all has many to has many relationships and instead use json columns. Makes this far easier for ingest into fedora. Form submission and editing with tagging on the fly is basically resolved with latest commit on PR #280
