### ISSUE TITLE
Ordering on Creators

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#333]
It is critical to have orders in the multivalue field: creators. Fedora currently prevents the values to be saved in a specific order, and creators are presented on the UI in random order. 
This is a high priority and we need to figure out an intermediate solution to work around this issue for our first release.

**Comment by mbarnett** [comment]
One thing we could potentially do to fix this in the short term would be to serialize the array into JSON prior to saving — [“Jane Doe”, “John Doe”, “Bob Example”] becomes the string “[\“Jane Doe\“,\“John Doe\“,\“Bob Example\“]”. We can save that knowing that the order is fixed and that we can still deserialize it when we read the field back from Fedora so that we can link to the individual author facets.

**Comment by sfarnel** [comment]
Sounds like a good solution, and when we examine the various components (data model, Fedora, etc.) post-launch we can see where solutions may lie in alternatives.

**Comment by zschoenb** [comment]
The question of where we are saving the array has come up. @sfarnel we could either convert all `dc:creator` values to an array. When we revisit this problem, if we want to reclaim the individual creators, we would need to perform a mass transformation on the arrays back into single values. We could, alternatively, implement a new predicate/property to store the array, for example `http://purl.org/ontology/bibo/authorList`. @mbarnett Matt expressed some concern that introducing a new property would be more work when the undoing comes around.

**Comment by mbarnett** [comment]
I think it mostly depends on how long we want live with this JSON thing versus re-modelling. If we're undoing this in favor of a more permanent solution in a month, it's probably not worth a lot of extra time investment, but if we're living with this for a while, then tracking the information in a couple of different ways probably makes more sense? 

Basically, the more time we sink into this now, the less we have for everything else that needs to be done by end-of-January, so we should be sure it's worth the cost.
