### ISSUE TITLE
Modify ERA take down policy text

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#3397]
The text for the take down policy (https://era.library.ualberta.ca/policies#take-down-policy) needs to be modified which is here: https://github.com/ualbertalib/jupiter/blob/d8bda60e6f01752f004ca9b61ff026e63ffdf059/app/views/static_pages/policies.en.html.erb#L61
 
The new text to add to the policy is below:

_From time to time, new digital environments emerge which are more well-suited to content which has been deposited in ERA. When this occurs, we will work with depositors and communities to create successful migration experiences to these new environments and ensure that our Library's commitment to outstanding service guides our work. We will always weigh these decisions carefully and design migration plans in consideration of any affected end-users and communities._

**Comment by pgwillia** [comment]
In production
