### ISSUE TITLE
Inheritance issues with JupiterCore::LockedLdpObject

### ISSUE THREAD

**Issue by cwant** [ualbertalib/jupiter#352]
I've pushed two branches related to thesis modelling, one that handles common behavior via concerns, the other that handles it via inheritance:

* Concerns:
  https://github.com/ualbertalib/jupiter/tree/cwant/issue_335_thesis_modeling_via_concerns
  Shared code module:  https://github.com/ualbertalib/jupiter/blob/cwant/issue_335_thesis_modeling_via_concerns/app/models/concerns/base_item_behavior.rb
* Inheritance:
  https://github.com/ualbertalib/jupiter/tree/cwant/issue_335_thesis_modeling_via_inheritance
  Shared code ancestor: https://github.com/ualbertalib/jupiter/blob/cwant/issue_335_thesis_modeling_via_inheritance/app/models/base_item.rb

The test suite runs fine for the first one (concerns), but a system test fails for the second one (inheritance). The test that fails in the inheritance branch isn't handling sorting by 'record_created_at' correctly, and this breakage also shows up in the console.

Although possibly unrelated, it's been confirmed that in the inheritance branch,  `JupiterCore::LockedLdpObject#set_record_created_at` gets run twice for instances of `Item`: https://github.com/ualbertalib/jupiter/blob/cwant/issue_335_thesis_modeling_via_inheritance/app/models/jupiter_core/locked_ldp_object.rb#L490

**Comment by mbarnett** [comment]
I think we just decided we weren't going to support this at the moment. Like Single-table inheritance, it gets weird quickly.
