### ISSUE TITLE
Fix truncated datastreams from HydraNorth migration

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#360]
A handful of items with very large datastreams had them truncated during the original HydraNorth migration. Restoring datastreams larger than 2.1gb is impossible due to Solr config. Rather than trying to fix this before the Jupiter migration, we will migrate these items as-is and restore the full-length datastreams in Jupiter.

**Comment by weiweishi** [comment]
will solve this as part of #102

**Comment by mbarnett** [comment]
Just cleaning up some old tickets that have been lingering – does anyone know if this ever got solved? (I'm going to close this and ping Weiwei double-check, but if it hasn't been solved feel free to reopen).
