### ISSUE TITLE
Item type `article` and it's (publication) `status`(es)

### ISSUE THREAD

**Issue by cwant** [ualbertalib/jupiter#367]
Current `Item` model has required attribute `item_type` (`dcterms:type`). When that is set to the URI representing `article`, an additional `publication_status` (`bibo:status`) must be included (otherwise, `publication_status` must be excluded).

Currently `publication_status` is single-valued, but should be multi-valued. It should have two states:

* either the status is URI representing `published`;
* or two URIs must be present: one representing `draft`, and other representing `submitted`

Validations should be updated, as should test/seeds.

@weiweishi @ualbertalib/metadata does this match your understanding of how this should work?

**Comment by zschoenb** [comment]
This matches mine. Thanks @cwant

**Comment by weiweishi** [comment]
Thanks @cwant. And yes, this matches with what was outlined by Sharon.
Thanks for working on this.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by sfarnel** [comment]
Thanks @cwant
