### ISSUE TITLE
Figure out how to validate Thesis collections?

### ISSUE THREAD

**Issue by cwant** [ualbertalib/jupiter#378]
Theses can only be stored in certain collections. For the most part, the UI will dictate which collections theses can belong to. Can there (or should there) be a validation for which collection theses can be deposited to?

Some approaches we may want to explore:

* Hard code some community/collection names in the rails source;
* Have a `isThesisCollection` predicate for collections that indicate whether a collection can hold thesis.

**Comment by mbarnett** [comment]
related to #473 ?

**Comment by cwant** [comment]
Yeah, I think so. I guess the workflow is:

1) Make a thesis collection 'restricted';
2) Trust that an admin will deposit theses there.

Chris

**Comment by weiweishi** [comment]
This is completed via making thesis collection restricted #473
