### ISSUE TITLE
Modify Community Create/Edit To Include Description & Logo Upload

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#38]
Mockups:

* https://jupiter.mybalsamiq.com/projects/jupiter/Admin%20-%20create%20new%20community
* https://jupiter.mybalsamiq.com/projects/jupiter/Admin%20-%20community%20detail%20page

DONE WHEN:
- [x] Add description to community. Current ERA or the data dictionary should have information on what predicate to use.
- [x] (My suggestion is to try moving up to the latest #Rails 5.2 beta and investigate [ActiveStorage](https://github.com/rails/activestorage) for logos, as it seems well suited to our needs and might easily bridge the fact that Community isn't an ActiveRecord class, which most asset gems expect).
- [x] Add logo upload to community. Ideally we'd like to avoid the Hydra approach of storing the logo in Fedora and streaming it from there for display. ActiveStorage seems promising in that it can store the asset info in its own table rather than adding columns to an ActiveRecord table, since Collections aren't ActiveRecord. You may need to play with a few approaches and talk them through, but if we have to start creating, say, shadow collection records in the DB, I'm ok with that.
- [x] Display logo on community show page
- [x] Display logo on community index page

**Comment by cwant** [comment]
Some notes on the ActiveStorage investigation:

* The now-obsolete repository for ActiveStorage is here: https://github.com/rails/activestorage
  The last version of code before the merge into Rails is in the 'archive' branch, but there is also a release v0.1 which is what you get when you install ActiveStorage as a gem.
* Release v0.1 mostly works with Rails 5.1 (there is a class variable that needs to be set via an initializer that would not need to be done with Rails 5.2).
* The 'archive' branch depends strongly on Rails 5.2. It has some nice features though: serving up blobs via a rails engine, ability to resize images

So our options are:

* Accept v0.1 as it is -- it might be good enough for our current purposes; If we need to resize images, do it some other way (current ActiveStorage uses MiniMagick gem for that).
* Fork the ActiveStorage gem (from the 'archive' branch) and massage it to work with Rails 5.1
* We become a Rails 5.2 project.

**Comment by cwant** [comment]
The current class does not have a validation on 'title' -- should there be one?
Related: should there be a validation on this new description property I'm adding? (presence, minimum characters ...)

I am getting some interesting behaviours with community, I don't know if this is how it's supposed to behave:

```ruby
pry(main)> community = Community.all.first
=> #<Community id: "1d18b4f1-817d-4ab0-a54d-8b14e4f19f4f", visibility: "public", owner: nil, title: "Whatever", description: nil>

pry(main)> community.valid?
=> true

pry(main)> community.unlock_and_fetch_ldp_object do |uo|; end
=> #<Community id: "1d18b4f1-817d-4ab0-a54d-8b14e4f19f4f", visibility: "public", owner: nil, title: "Whatever", description: nil>

pry(main)> community.valid?
=> false 
```

Basically: validation don't run unless you've unlocked the object at some point.

I don't know if this is expected behaviour, or if I'm touching something that isn't fully developed.

**Comment by mbarnett** [comment]
1) vis-a-vis ActiveStorage, it sounds like if we can live with 0.1 for right now, that's fine. Between "doing custom work on ActiveStorage archive" and "moving to the Rails 5.2 dev branch", 5.2 wastes distinctly less work, I think. But it might also be worth seeing if we can somehow make this work with a different gem without running aground on the fact that this isn't an ActiveRecord class.

2) Title validation: yes

3) Whether or not descriptions are required on Communities is a stakeholder question imo (@leahvanderjagt ?)

4) This is an interesting one, and the behaviour's a bit up in the air, so I'm interested in thoughts:

What's happening is that, behind the scenes, LockedLdpObject only loads the Solr object unless you force it to do the read from Fedora with `unlock_and_fetch_ldp_object`. To make validations simple in the happy path I added the AcitveModel `.valid?`stuff to LockedLdpObject and had it always be true *if* the Fedora record isn't loaded (on the assumption that hey, the data is in Fedora, and the current object can't have been mutated because it hasn't had to read from Fedora, so sure, valid), and otherwise if the Fedora record is loaded, defer to the ActiveFedora object. This way if we happened to have some set of objects to iterate through on the UI where we needed to check validity, we would have to force every read to go to Fedora when it probably didn't need to.

In your case, by adding a new validation, but not re-saving all objects to Fedora, you've broken the assumption that every object currently in Fedora is already valid. Hence it returns true up until you actually force a read from Fedora, at which point the new validation runs.

I can see three ways around this:

1) Remove the `.valid?` shortcut from LockedLdpObject. You *have* to unlock the object to check validity. This might slow things down in cases where we could have gotten away with checking validity on the Solr cache only. This will probably break simpleform error displays on LockedLdpObjects, and force passing unlocked version to forms (this sucks).

2) Hoist the validation implementation up to LockedLdpObject. Right now you define it in an `unlocked` block and in reality you're just using ActiveFedora's implementation of ActiveModel's validations API (with all the fun attendant bugs, like "whoops despite the docs, validation callbacks just don't run, and we've known about this for 2 years, and nobody can be bothered to fix it ¯\_(ツ)_/¯"). I could move this up to our own implementation in LockedLdpObject, you'd define validations outside the unlocked block (which might or might not feel more natural anyways), and it could validate correctly against the solr cache. This is cleaner but more work.

3) We consider adding new validations an edge case, shrug, and move on.

@cwant @murny thoughts?

**Comment by cwant** [comment]
Not sure, but not crazy about the status quo where there is a method called `valid?` that may or may not actually do something meaningful.

While not ideal, I would favour removing the method over having unpredictable behaviour.

Also, is there a chance we might want to validate something that isn't exposed to solr?

**Comment by cwant** [comment]
Regarding ActiveStorage, I am fine with sticking with v0.1 for now. If we need to resize a logo in a view we should be fine using CSS rather than resizing on the server.

**Comment by mbarnett** [comment]
There's no option to not expose things in Solr -- even the idea of having values in Fedora that didn't make it into Solr was, I think, a fundamental design mistake in ActiveFedora, as it just ends with performance in the gutter when you have to touch those attributes (and if you go to any sessions about it at a conference, they'll explicitly recommend indexing everything anyways).

I'd rather move the validations up than drop the .valid? and .errors, honestly. I don't want to have to wrap every form in `unlock_and_fetch_ldp_object` just to make errors display properly, and that's going to slow down form rendering.

**Comment by mbarnett** [comment]
[Started a new issue to track hoisting validations](https://github.com/ualbertalib/jupiter/issues/76)
