### ISSUE TITLE
Theme refinements

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#399]
Theme looks wonderful so far! I have some feedback on refinements - please ask if there are any questions:

- [x] Stretch search box in navbar
- [x] Make font on navbar links heavier
- [x] Improve ERA-AV stuff
- [x] Heavier font for "Explore some of our collections & communities"
- [x] Heavier font for collection labels
- [x] Agriculture photo skinnier
- [x] Oil sands photo shorter
- [x] Mobile: stretch out search bar to full width
- [x] Mobile: make search submit button just magnifying glass icon
- [x] Mobile: move welcome text up
- [x] Mobile: collection links as per mock up
- [x] Mobile: move menu items to the left under hamburger

![era feedback 1](https://user-images.githubusercontent.com/12801010/35417674-b6ed19de-01eb-11e8-92c4-3b91a86f47a7.png)
![era feedback 2](https://user-images.githubusercontent.com/12801010/35417677-b9cb0594-01eb-11e8-8394-307f3ef46ee2.png)
![era feedback 3](https://user-images.githubusercontent.com/12801010/35417679-bc1c0096-01eb-11e8-8781-64cfa935ef83.png)
![era feedback 4](https://user-images.githubusercontent.com/12801010/35417683-be8bee9a-01eb-11e8-9aeb-457b23d2152a.png)

**Comment by cwant** [comment]
@sfbetz I've addressed each issue (itemized list above), and the latest work has been deployed to UAT. After a conversation with Shane, I went with a more simplified ERA+AV link (standard icons for play button, rather than play button in background).

**Comment by sfbetz** [comment]
All looks great! Only issue I can see is log in link is wrapping at top RH corner:
Log
In
(and can we have lower case "i"?)
