### ISSUE TITLE
timestamp in file name after deposit

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#400]
There seems to be the timestamp attached to the file name once they are deposited through the UI
![image](https://user-images.githubusercontent.com/2047614/35461963-40b76be0-02a7-11e8-9485-b2017005a3d2.png)

Could those be removed? The file deposited into fedora should maintain its original filename.

**Comment by murny** [comment]
Comes from here: https://github.com/ualbertalib/jupiter/blob/master/app/models/draft_item.rb#L178

Tempfile adds a unique ID to the file to prevent name collisions in the temp folder. Way around this? Needs investigation

**Comment by mbarnett** [comment]
This is fixed on master as of #425 having been merged
