### ISSUE TITLE
Collect historical analytic data

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#405]
To gather historical analytic data from different sources:
- [ ] pre-HN - access data in DB
- [ ] HN data - counts available in GA

**Comment by pbinkley** [comment]
Sources:

- ```era1stats``` datastream
- db tables ```file_download_stats``` and ```file_view_stats```
- both have entries per date

**Comment by mbarnett** [comment]
This is done in Production now, I believe
