### ISSUE TITLE
Crawler Friendliness & Hardening

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#416]
All of the `<a>` tags in the facet sidebar on search, communities, collection (and anywhere else they appear) and pagination links on search should be marked `rel=nofollow` to keep bots from needlessly slamming the app by crawling variations in search results. 

We probably also want to mark the entire search page as `noindex` (not collection, community, or other pages, though)

**Comment by pgwillia** [comment]
Should these and `/items/*/download` be in robots.txt as well?

**Comment by murny** [comment]
Stackoverflow with exact same question:
https://webmasters.stackexchange.com/questions/19133/should-i-add-a-nofollow-attribute-to-download-links-or-disallow-the-urls-in-r

**Comment by pgwillia** [comment]
- [ ] unique title and description for each page
- [ ] noindex [meta tag](https://developers.google.com/search/reference/robots_meta_tag) for search page 

> For the noindex meta tag to be effective, the page must not be blocked by a robots.txt file. If the page is blocked by a robots.txt file, the crawler will never see the noindex tag, and the page can still appear in search results, for example if other pages link to it. [[here](https://support.google.com/webmasters/topic/4598466?hl=en&ref_topic=4617736)]

- [ ] nofollow for download links 
- [ ] nofollow for facets
the discussion on the [Google SEO starter guide](https://support.google.com/webmasters/answer/7451184?hl=en) uses nofollow in situations where you don't endorse the content behind the link (untrusted content, paid links or crawl prioritization) i.e. user comments, 3rd party widgets or links you want to mention but not boost -- is this really what we're going for?
- [ ] [structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/)
- [ ] [Blocking 404 pages from being crawled through the robots.txt file.](https://support.google.com/webmasters/answer/7451184)
- [ ] alt attributes on images
- [ ] Google's Mobile-friendly test
- [ ] use meta name="viewport" tag to tell the browser how to adjust the content

**Comment by mbarnett** [comment]
Re:
> the discussion on the Google SEO starter guide uses nofollow in situations where you don't endorse the content behind the link (untrusted content, paid links or crawl prioritization) i.e. user comments, 3rd party widgets or links you want to mention but not boost -- is this really what we're going for?

It's not a guarantee that bots won't follow it, but it's a hint that there's no reason to, and it can't hurt.

**Comment by mbarnett** [comment]
Oh and we should also make sure we get canonical tags into the right places, ie) faceted versions of the Collection and Community pages pointing back at the unfaceted canonical version.

**Comment by pgwillia** [comment]
closed by #483
