### ISSUE TITLE
Notification Messages -- WYSIWIG

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#42]
DONE WHEN:
- [ ] WYSIWYG functionality for creating new admin notification messages (issues to think through here: malformed HTML, escaping, links, XSS issues, whether or not something like Markdown is a better fit)

**Comment by mbarnett** [comment]
Taken out of admin epic as a wishlist item we're not going to get to right now. I've spoken with Leah and she's not married to this, so we can circle back to it when we have some slack in the schedule

**Comment by weiweishi** [comment]
Closing this ticket as @leahvanderjagt doesn't think this is required.
