### ISSUE TITLE
Serving thumbnails directly from the thumbnail server

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#435]
In production, we have set up a thumbnail server to allow both app servers to write thumbnails to the same location and be able to serve them on both app servers. Currently, thumbnails are served through the rails app. We will need to make configuration changes etc to serve thumbnails directly from the thumbnail server. 

We will also need to set up the proper redirect for the thumbnail images once we figure out how we'll serve them directly from the thumbnail server.

**Comment by weiweishi** [comment]
We will do a spike to investigate how to serve the files through apache and turn Gluster into a CDN and serve the error pages from the Apache properly.

**Comment by mbarnett** [comment]
I'm going to close this/suggest we don't pursue this for the time being, in the suspicion that if a cloud host is in our future we'll actually want to get proxying through Rails, and would have to back this change out.

We can reopen if it looks like we're going to be staying with a local solution on a long-term time horizon.
