### ISSUE TITLE
Fix thumbnail viewing on item detail page

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#436]
Bug 1: 

We are stretching the thumbnail image to fit the 400px height and 100% width of the container which distorts the image if the image is really tiny

Example: 
![image](https://user-images.githubusercontent.com/1930474/35879946-c6db80ea-0b39-11e8-87f9-168759900b7d.png)

Bug 2:

We should fallback to a nice favicon based on the files extension/content type when there is no image thumbnail.

For example if it is a zip file, maybe show a zip icon? Like: https://fontawesome.com/icons/file-archive

**Comment by weiweishi** [comment]
https://github.com/ualbertalib/jupiter/pull/440
