### ISSUE TITLE
File titles with spaces make sitemap not well formed

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#466]
![screenshot from 2018-02-09 14-29-07](https://user-images.githubusercontent.com/1220762/36050981-c781dd6e-0da5-11e8-9ef0-4c40e8f794b1.png)
https://era-beta.library.ualberta.ca/sitemap-items.xml

**Comment by mbarnett** [comment]
Fixed with Tricia's merge on March 9
