### ISSUE TITLE
Consolidate docker images

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#472]
- [x] move fedora docker image to organization space and replace the existing one:
https://hub.docker.com/r/ualbertalib/fedora/, and use it in our jupiter docker stack:
https://github.com/ualbertalib/jupiter/blob/master/docker-compose.yml#L40

- [x] consolidate changes made by @jefferya at https://hub.docker.com/r/jefferya/docker-fcrepo4/ to include OAI provider in our fedora docker image.

**Comment by pgwillia** [comment]
- [ ] delete all the ualbertalib dockers (except for jupiter)
- [ ] delete rubyhydra/ruby_base, use the official ruby docker repo
- [ ] delete [di_docker_images](https://github.com/ualbertalib/di_docker_images) in favour of repo per docker

**Comment by pgwillia** [comment]
Leaving this for a higher priority ticket. [oaiprovider-4.7](https://github.com/ualbertalib/docker-fcrepo4/tree/master/oaiprovider-4.7) exists. Works for me when I create and use the image locally `docker build -t docker-fcrepo4 oaiprovider-4.7/` but the image that I pull from dockerhub built from the same code has tomcat but no fcrepo context. Fixing that and incorporating into UAT deployment is the next step

**Comment by murny** [comment]
Closing out issue. The main work for this has been completed. Weather we want to be using OAI Provider fedora docker on UAT or not is another issue.
