### ISSUE TITLE
Document requirements for "lower-casing" all ual predicates

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#478]
This also seems to involve removing underscores? Are there any other major requirements here? It would be good to specify this up front so that we can plan for mapping Ruby-friendly names into their requirements properly.

**Comment by mbarnett** [comment]
>  It doesn't seem there's an easy way to get around with this constraint without some significant development at our end.

I disagree? I'm pretty sure we could get this working today, but I'd need to know what requirements I'm trying to meet before I take a shot at it. This might just be because I have more of how this stuff works in my head than anyone else, but that's all the more reason to make sure these requirements pass through proper Github issues.

So all lower case, and no underscores. Anything else?

**Comment by mbarnett** [comment]
It would also be good if someone could provide a rationale for why we're violating RDF naming conventions (http://www-sop.inria.fr/acacia/personnel/phmartin/RDF/conventions.html#lexicalConventions), so that I can document our reasoning in the codebase

**Comment by weiweishi** [comment]
I've booked a meeting for tomorrow morning to have a chat in-person for
this and another issue that has recently raised during the implementation
phase.




*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by danydvd** [comment]
Based on our meeting today:

- All the UAL properties in Data Dictionary are now camel-cased according to RDF conventions.
- The newly added "dataDictionaryLabel" is removed as it is no longer necessary.
- Jupiter [ontology](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/jupiter_ontology.md) is now up-to-date and includes all UAL properties and terms.
- A list of all [UAL properties](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/UAL_properties.md) and terms is available in the Data Dictionary.
- Everything else remained unchanged.

**Comment by mbarnett** [comment]
Thanks Danoosh. I'll tweak my PR accordingly

**Comment by sfarnel** [comment]
Thanks @danydvd and @mbarnett

**Comment by mbarnett** [comment]
@danydvd it looks like a couple of terms are missing from https://github.com/ualbertalib/metadata/blob/master/data_dictionary/UAL_properties.md.

We've got ual:recordCreatedInJupiter, ual:sitemapLink, and ual:Community in place on our end.

On the flip side, @weiweishi it looks like we're not using ark, nnaFile, or nnaItem for anything? I'm not sure if that's correct or not because I have no context for this.

**Comment by sfarnel** [comment]
Thanks @mbarnett The ual properties is generated from the graph in the triplestore and only captures those properties from the DD which are application agnostic. Weiwei started [this page](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/readme_application_properties.md) in December for capturing the application specific properties until we all as a larger group decide on the best way to document these. (Danoosh and I were just chatting about a separate graph in the triplestore as a longer term possibility). We can definitely add the properties you mentioned to this page. @danydvd would you mind doing so?

**Comment by danydvd** [comment]
Sure. I can do that. However, I might need input from @mbarnett on some of the properties.

For example: currently in the application specific readme we have "record_created_at". This seems similar to "ual:recordCreatedInJupiter". Is that right?

Where would you want ual:sitemapLink and ual:Community located (e.g. item or community ...)

**Comment by weiweishi** [comment]
Thanks @mbarnett @danydvd and @sfarnel. 

We should use StrictVocabulary to catch anything else that is used in the code but not defined in the term references. 

@sfarnel do we have a need for ark - we didn't really use them in any public UI. They are generated as shadow arks during doi generation but I don't know if the value is actually saved into this property. Do you think this is an early experiment with ARK that was never really implemented?

@mbarnett please add nnaFile and nnaItem - they are for a legacy identifier and some legacy information that we will only migrate them so we have the information on the object but will not use them anywhere in the application.

**Comment by weiweishi** [comment]
and @danydvd record_created_at should be updated as record_created_in_jupiter (as we want it to very clearly indicate it's a timestamp for object created in this application) - I will update that Readme page. 

ual:sitemapLink is for fileset, and ual:Community is the class used for Community objects.

**Comment by sfarnel** [comment]
Thanks @weiweishi ark is only for the legacy data migrated as we captured this in the past. I don't believe we have specification to capture these in Jupiter.

**Comment by weiweishi** [comment]
thank you @sfarnel. @danydvd do you mind do a quick check to see if we have data in the ark field? reason I'm asking is I can't seem to find the code in current HN that implements and uses ark (we had Chris R working on the implementation of ARK, but I don't think we put that work into production as we decided to use DOIs instead).

**Comment by danydvd** [comment]
There is nothing in the triplestore. In fact there is no property containing phrase "ark" in the triplestore (gillingham_20171222)

**Comment by sfarnel** [comment]
Thanks @danydvd 

We had http://terms.library.ualberta.ca/id/arkid but if it was never captured in the end then we can remove it from the DD.

**Comment by weiweishi** [comment]
Thank you @sfarnel and @danydvd

**Comment by danydvd** [comment]
ual:ark is removed from the DD.

**Comment by weiweishi** [comment]
this is completed with PR #480
