### ISSUE TITLE
Fallback image for Communities without logos and CCID protected Items

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#481]
Leah suggests using the ERA logo for now, until we can come up with a better idea.

- Communities without an image should show a fallback image (ERA Logo)
- CCID protected items should show UofA logo and login button where thumbnail and file download/view should be for non logged in users

**Comment by murny** [comment]
This is now on UAT. How to test?

- For community images fallback, simply check out the `Browse` link on the navbar (or go here: http://uatsrv01.library.ualberta.ca/communities), if you scroll down past the first few communities, you should see a few without any logos and are using the ERA logo instead (for example this community: http://uatsrv01.library.ualberta.ca/communities/a7d24108-580c-4683-8d39-7161efe9400d). 
![image](https://user-images.githubusercontent.com/1930474/37179784-0f9343c4-22e4-11e8-913b-97b14aa37857.png)
Verify this looks good, and is acceptable behaviour.

- For CCID protected items, you can search for 'CCID' in the search box (http://uatsrv01.library.ualberta.ca/search?search=ccid). The results will be CCID protected items. Assuming your logged out, you should see a UofA logo as the thumbnail:
![image](https://user-images.githubusercontent.com/1930474/37179883-71d13da2-22e4-11e8-84b3-ea7163c6064f.png) Most of these do not have files associated with them, so if you click on one, you won't see anything regarding thumbnail or viewing/downloading file. I have added a file to this CCID item for testing however: http://uatsrv01.library.ualberta.ca/items/1b6fab7c-b5df-46ac-abb7-0874f8069190

  So when logged out you should see something like: 
  ![image](https://user-images.githubusercontent.com/1930474/37180023-da1889d8-22e4-11e8-87d5-555ea4e3eb03.png)

  When logged in you should experience normal behaviour. Verify this works as expected.

Let me know if you got any questions, or feedback. Thanks!

**Comment by murny** [comment]
@leahvanderjagt / @sfbetz  said everything looked good. There was two issues however:

- UofA Thumbnail should have the `Item restricted to University of Alberta users` text on the thumbnail itself, so it shows up in the search list etc. Issue created here #550

- Secondly, discovered a bug with downloading an item, the url gets updated with this download link, which means any time a user refreshes/uses back/forward buttons, a new item gets downloaded. This probably shouldn't happen. Issue created here #551


Closing this issue now
