### ISSUE TITLE
Homepage/Theme feedback

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#482]
- Main title (H1) and lead text should overlay banner image ( and remove current paragraphs under header (copy to come later, probably just one sentence))
- Change Font weight/bold of the headers (for all) and custom font weight changes in navbar
- Change footer links to static content links and add others, this repalces static nav as shown in mockups
  - Remove Address/Web Site Privacy Policy => Add Powered by Jupiter, Help, Policies, About Us
- Change overlay headers font size/boldness on images for Our Communitys/Collections
- Fallback image for Communities, use ERA logo instead? #481

**Comment by murny** [comment]
Regarding banner with overlay text here are some options (for white text on a dark background, can do the opposite if this is preferred):

### Tint image and overlay text on it:
![image](https://user-images.githubusercontent.com/1930474/36442039-b237f27e-1631-11e8-9056-5276ee5fe5d3.png)

or a darker tint:
![image](https://user-images.githubusercontent.com/1930474/36442179-1c145bec-1632-11e8-9ae5-7ddce3bb9e27.png)

### Put text in a box with dark background
![image](https://user-images.githubusercontent.com/1930474/36442215-4036a6d8-1632-11e8-99c1-cc659d2764a1.png)

or add a bit of tint on image, with text in a box
![image](https://user-images.githubusercontent.com/1930474/36442209-3aa3f414-1632-11e8-9210-259d490cf2fe.png)

### Highlight text with dark background
![image](https://user-images.githubusercontent.com/1930474/36442198-33a16f3e-1632-11e8-89e0-05aeac652552.png)

Of course the copy and headline being used will change and this will make quite a difference with how things will look. So keep this in mind.

Any preferences of the above? @sfbetz @leahvanderjagt

**Comment by leahvanderjagt** [comment]
Here's the language I'd like. We'll be running it past a few different groups to see how it resonates. 

ERA: Education and Research Archive: (Head)
University of Alberta research shared with the world (Dek)

**Comment by pbinkley** [comment]
Note that our Nagios monitoring now depends on detecting the words "Welcome to ERA" to determine that the site is up. If we change the wording, we should let Neil know.

**Comment by murny** [comment]
![image](https://user-images.githubusercontent.com/1930474/36511178-f4c3aeb6-1722-11e8-92dc-007f61aa7bbb.png)
![image](https://user-images.githubusercontent.com/1930474/36511198-043231ec-1723-11e8-8a1f-1ff71390940c.png)

**Comment by murny** [comment]
Made additional changes: Increased font, line break after ERA, fix tagline

Allowing text to only flow half page:
![image](https://user-images.githubusercontent.com/1930474/36553674-2c5d223e-17ba-11e8-9f3d-fca772d4f823.png)

Or allowing text to expand full page:
![image](https://user-images.githubusercontent.com/1930474/36553664-2653705a-17ba-11e8-93cb-2b6d352a5f38.png)

**Comment by murny** [comment]
Closing:
Separate ticket for 'Fallback image for Communities, use ERA logo instead?' already exists here: #481
Created issue to populate static content here: https://github.com/ualbertalib/jupiter/issues/519
