### ISSUE TITLE
CCID authenticated users can't view ccid-protect objects on era-beta

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#484]
Logged in with my ccid. The search result only displays public objects:
![image](https://user-images.githubusercontent.com/2047614/36221657-0ce116b6-117c-11e8-8f6c-ffab8fad9a2d.png)

When trying to view an ccid-protected object:[5e65169a-b27e-4259-a22f-7c779e87f03a](https://era-beta.library.ualberta.ca/items/5e65169a-b27e-4259-a22f-7c779e87f03a)
it says 
![image](https://user-images.githubusercontent.com/2047614/36221707-39c304d2-117c-11e8-9302-e4dbf6eac73d.png)

**Comment by mbarnett** [comment]
Is the version that's on beta still the 0.8 tag, or has it been redeployed since? I'm wondering if some fixes that landed after the 0.8 tag shouldn't have fixed this.

**Comment by mbarnett** [comment]
Answered my own question by poking around on Kimberely: I believe this is already fixed on master, if we tag and deploy a new beta

**Comment by murny** [comment]
It's a old version as theres css fixes not in there. For example the breadcrumbs not being in a container:
https://era-beta.library.ualberta.ca/communities/4a9ba2aa-4fa0-4f19-b590-39b92d61a84d

**Comment by weiweishi** [comment]
It's still the 0.8 tag. Will tag the new release to deploy once
the postgresql PR is merged, and will check this again.

can't verify on UAT as we'll also need to fix the uat ccid login - we send
the metadata to ist with callback links to https instead of http. So we
will either need to give them an new metadata with the non-https callback
link, or add a self-signed ssl cert for uat. I think I'd prefer the latter.


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by mbarnett** [comment]
On UAT, being signed in via the dev login _should_ behave the same as being logged in via CCID, at least as far as showing protected items goes.

**Comment by weiweishi** [comment]
If that's the case, I don't think I see these restricted items with
non-admin@ualberta.ca on UAT:
http://uat.library.ualberta.ca/search?search=


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by mbarnett** [comment]
Do you have an example id handy?

**Comment by weiweishi** [comment]
we are all good. verified on UAT things are working. Will add a few in the seed file. Close the ticket.
