### ISSUE TITLE
400/500 pages, other table-stakes production stuff

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#5]

**Comment by murny** [comment]
Need to handle 301 redirects for all old pages to new pages (if urls have been changed)

**Comment by pbinkley** [comment]
This should include the 410 page needed by some legacy redirects https://github.com/ualbertalib/jupiter/pull/460#discussion_r167699589

**Comment by cwant** [comment]
Any requirements for this one? I assume we want error pages that use the app layout? Other than that, would taking the text from the stock rails error pages suffice?

**Comment by pbinkley** [comment]
Yes, let's go with app layout and stock text. If Leah or Sonya want more than that we'll put in a post-beta issue.
