### ISSUE TITLE
era-beta: odds and ends

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#509]
- when I log in with my ccid it shows I have 34 items none of which seem to belong to me (this is likely just a temporary issue but just wanted to note it in any case)
- in the ERA processing community, Journal Articles (ERA Processing) collection, there are two private items that seem to be showing (again likely just a temporary issue but just wanted to note it in any case)

**Comment by mbarnett** [comment]
Just updating this with information from the discussion in Slack, so we don't lose track of the info:

The first issue, where we all own random items, is an artifact of jumping off of MySQL to Postgres and will be resolved after the data is remigrated to fix some other issues anyways.

The second issue, both items Sharon mentioned (found in this collection: https://era-beta.library.ualberta.ca/communities/1b56d739-0cc9-41d9-ad64-baa0eebe3a60/collections/19c64bce-902d-4c00-8e23-c31b78122669) have a visibility of "http://terms.library.ualberta.ca/public", and Danoosh is looking into the migration package data at the moment

**Comment by danydvd** [comment]
In migration script, private items (generic items) are items that do not have a "Read" permission object (only have "Write") or they have "Read" permission with an agent with a person's email (e.g. ashiri@ualberta.ca). 

In current migration script, the visibility variable is assigned to items that have "Read" permission with an agent with a person's email (e.g. ashiri@ualberta.ca) and all other private items would not get a visibility triple (as the visibility variable is always null). 

I am modifying the script to:

- [ ] assign visibility triple with value "ual:draft" for items with only "Write" permission object. 
- [ ] audit the post migration triples to ensure triples are added 

Thesis items will get a "ual:draft" in dcterms:accessRights if they have "acl:hasEmbargo" object that has a "acl:visibilityDuringEmbargo"

**Comment by weiweishi** [comment]
@danydvd I think if an object, thesis or not, has "acl:hasEmbargo" object that has a "acl:visibilityDuringEmbargo", the dcterms:accessRights should be http://terms.library.ualberta.ca/embargo?

**Comment by danydvd** [comment]
@weiweishi you are correct. I had forgotten about a method in the migration script that changes accessRights value to ual:embargo if the ual:embargoReleaseDate is smaller than the migration date. Sorry for the confusion.

**Comment by murny** [comment]
Closing out issue, sounds like this was data migration issues. 

Please feel free to reopen if this is still an issue with production.
