### ISSUE TITLE
Add copy/content to Static pages once completed

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#519]
Creating a issue for this since there currently nothing for this

Once copy/content for the about/contact us/policies pages are done, we will need to move them into the application

**Comment by leahvanderjagt** [comment]
Static text for launch here:
https://docs.google.com/document/d/1wUkDUmL13AV02YRjs5Vw8HYaeoDHffm9oq7xcqV_u0M/edit?ts=5a83620b

We may change some things around a bit post-launch.
