### ISSUE TITLE
Need some way of getting `.count` or `.limit` on LockedLDPObject objects?

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#52]
It would be nice for example on the admin dashboard, to show how many Works/Communites/Collections we have in our system (using something like `Work.count`). 

Also be nice to just show the last 10 deposited works or something to the admin as well (using something like `Work.limit(10)` or maybe providing an order clause as well?)

Doesn't seem like you can currently do this via AF. Probably have to query solr or something instead?

**Comment by mbarnett** [comment]
Related to #47, for future reference

**Comment by mjgiarlo** [comment]
ActiveFedora does already support calling `#count` on either specific models or on `ActiveFedora::Base`. It uses Solr to make this calculation. (It does not support `#limit`, though.)

**Comment by mbarnett** [comment]
Thanks for the clarification, Mike. Shane actually meant we need to add it to our home-brewed Solr abstraction that we're introducing to start breaking our dependency on ActiveFedora

**Comment by mjgiarlo** [comment]
@mbarnett Gotcha! :cool:
