### ISSUE TITLE
Embargo expiry job

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#526]
We need to set up a Sidekiq job for scanning items with VISIBILITY_EMBARGO and whose embargo_end_date is < current date,and transition them to the post-embargo visibility. I believe there's also a requirement to push information regarding this change into the embargo_history attribute?

**Comment by murny** [comment]
Need to investigate how to run this periodically/reoccurring? Job probably runs once a day and checks for any expired embargo_end_date. Need to use a cron job or use a cron-like gem to give this behaviour for us with sidekiq.

https://github.com/ondrejbartas/sidekiq-cron
https://github.com/javan/whenever
???

**Comment by murny** [comment]
Is there a requirement for how often we want to be checking embargo dates? Every day? At 6 AM or something?

**Comment by mbarnett** [comment]
Hydranorth did it at midnight IIRC

**Comment by murny** [comment]
Looks like it was 10:01 PM? From digging into the ansible playbook here's the relevant section:
```
     - name: cronjob for remove embargoes
       cron: name="embargoes" hour=22 minute=1 job="cd /var/www/sites/hydranorth && RAILS_ENV={{rails_env}} bundle exec rake hydranorth:remove_lapsed_embargoes"
       tags: embargoes
       when: ansible_hostname == "bournemouth"
```

I guess we can agree it be daily. I'll make it 10 PM (no 1 minute cause that's silly) unless someone says otherwise

**Comment by murny** [comment]
This is now in production. Closing issue
