### ISSUE TITLE
SEO - use structured data to improve meta description

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#527]
Just a thought, but wouldn't this be the place schema.org/open graph/etc comes into play? Instead of fitting all this content into the meta description, you would use the appropriate meta tags to mark up this page for the year/authors/description etc.?

From Go Live Checklist

> Structured Data: High Pages using structured data are tested and are without errors. Structured data helps crawlers understand the content in the current page.

Suggestion from #483

**Comment by sfarnel** [comment]
Thanks @pgwillia!

Yes, absolutely! For launch we're doing a few things, mainly covering what we did for HydraNorth. @pbinkley  has been capturing this in a document (which I can't seem to find at the moment but Peter can point us there!)

And then post-launch we begin investigating and planning for schema.org (ualbertalib/metadata#166)

**Comment by sfarnel** [comment]
thanks @weiweishi spike is assigned to @johnhuck who will be working on this as he clears a few other things off of his plate. if there is more immediate need let me know and we can work to shuffle priorities

**Comment by weiweishi** [comment]
No, this is great! I'm just checking in and grouping tickets for different
milestones (immediate project closeout phase or future enhancement etc). I
will group this as a future enhancement and will wait for John's
investigation completes. Thank you very much!


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by sfarnel** [comment]
Awesome!

**Comment by johnhuck** [comment]
Thanks for checking in, @weiweishi. If there is anything you think I should know, or conversations you would like me to be a part of, or timelines you would like me to work to, just give me a shout. Cheers!

**Comment by pgwillia** [comment]
Duplicate of https://github.com/ualbertalib/jupiter/issues/673
