### ISSUE TITLE
Map Owner id to owner email address in triplestore

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#529]
Currently, in the application, owners are stored as owner_ids in the object's metadata. These IDs are application specific and can't serve our long-term preservation requirements. So we will need to map owner_id to owner email for
- preservation package constructed by PMPY
- triples stored in the triplestore.  

A separate ticket in PMPY will track the work for fetching the information for the preservation package.

**Comment by weiweishi** [comment]
Will wait until the Object/Metadata store evaluation project is concluded, and decide how this should be handled.

**Comment by weiweishi** [comment]
will checkin with @sfarnel if we can close this issue for now.

**Comment by sfarnel** [comment]
@weiweishi agree it makes sense to close for now
