### ISSUE TITLE
Deposit on era-beta fails because of virus checking

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#545]
It keeps complaining about virus checking

![image](https://user-images.githubusercontent.com/2047614/37177076-9235e790-22db-11e8-923e-53515314d242.png)

Need to work with @henryzhang87 to figure out what would be the issue with clamav/clamby set up on the production stack.

**Comment by sfbetz** [comment]
We'll have to resolve this to conduct user testing. Is there an easy workaround that we can implement while sorting out a permanent solution so I can sneak in some testing of deposit?

**Comment by mbarnett** [comment]
As far as I know this is now resolved on the Production stack, so I'm closing this ticket. Please reopen if anyone's still seeing this issue.
