### ISSUE TITLE
[Jupiter] Add version.rb file for jupiter?

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#55]
Nice to have but a `version.rb` file for jupiter project would be handy. Just like what most ruby gems, these are still really handy in applications as well. 

Can use this version to put the version in the html source of our website and other places like on the admins dashboard. This is really helpful for debugging, so you know what version of code is in production.

Also instead of manually cutting tags and pushing them up into github like we are currently doing for hydranorth this should all be done via rake tasks (no different then what a ruby gem has for free)

Simple approach? Copy what a ruby gem has.

Some different examples from big ruby projects:

https://github.com/gitlabhq/gitlabhq/blob/master/lib/gitlab/version_info.rb
https://github.com/discourse/discourse/blob/master/lib/version.rb
https://github.com/diaspora/diaspora/blob/master/config/defaults.yml#L7
https://github.com/tootsuite/mastodon/blob/master/lib/mastodon/version.rb

**Comment by mbarnett** [comment]
Added a VERSION constant in jupiter_core.rb

**Comment by weiweishi** [comment]
Adding a version.rb file seems to be a simple enough task and will put us on a better track for release tagging/management. It seems that all we need to do is to use one of the version management files from @murny's examples, and add this to application.rb file like so?https://github.com/tootsuite/mastodon/blob/master/config/application.rb#L14

**Comment by murny** [comment]
Yep exactly. That's all you need to do :+1:

**Comment by weiweishi** [comment]
- move versions from model to version.rb
- gemcutter gem?
- find better ways to present the version information?

**Comment by weiweishi** [comment]
timebox for 1 working day

**Comment by murny** [comment]
Work is now done and in master. 

Leaving this issue open until we test the release management process of cutting and tagging new versions and add documentation to README.md

**Comment by mbarnett** [comment]
Pretty sure we can call this done now, yes?
