### ISSUE TITLE
Thumbnail generation for large spreadsheets never finishes

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#555]
A 62mb .xslx ran for 54 cpu hours in the to-pdf stage without finishing. The long-running process was:

```
/usr/lib64/libreoffice/program/soffice.bin --invisible --headless --convert-to pdf --outdir /tmp /tmp/891ce3f1-82bd-4f46-aa81-ac1c5e74621e-120180310-4974-hxkknk.xlsx
```

The spreadsheet has a single worksheet with 182721 rows and 73 columns. When unzipped the worksheet xml was 404mb.

**Comment by weiweishi** [comment]
Project stakeholders approve that we will continue to use the generic spreadsheet logo for all spreadsheets. No longer need to generate thumbnails for .xls files.
