### ISSUE TITLE
Author field in deposit missing example text

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#556]
Can we add example text below the Author / Creator field in all forms that says:

Example: Doe, Jane B.

**Comment by mbarnett** [comment]
The current prompt/placeholder text is: "Enter one or multiple author/creators"

Would you prefer "Enter one or multiple author/creators. Example: Doe, Jane B." as a placeholder, or the example underneath the input, similar to the way that Alternate Title has a small "Enter a secondary/translated title, if appropriate." underneath?

**Comment by sfbetz** [comment]
Let's go with second option: leave the placeholder text as is and add underneath the input "Example: Doe, Jane B."
