### ISSUE TITLE
Deleting item leads to 404 error

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#579]
Trying to delete test items leads to a 404 error. 

Logged in to my sfbetz user account - trying to delete this item:
https://era-beta.library.ualberta.ca/items/06ec0895-075d-4098-80c9-ebb1795db937

Delete fails whether I try it from delete button on a search results page like this: https://era-beta.library.ualberta.ca/search?search=lorem+ipsum

Or from user account page like this: https://era-beta.library.ualberta.ca/admin/users/877

Error message:

This era-beta.library.ualberta.ca page can’t be found
No webpage was found for the web address: https://era-beta.library.ualberta.ca/items/06ec0895-075d-4098-80c9-ebb1795db937
HTTP ERROR 404

I am able to successfully delete "draft" files with no issues.

**Comment by murny** [comment]
This is a duplicate issue: https://github.com/ualbertalib/jupiter/issues/468

Nothing wired up for handling deletion of items

**Comment by sfbetz** [comment]
Okay, thanks! Will close this issue b/c duplicate.

**Comment by murny** [comment]
Alright works for me. I quoted your description to the other issue, as its more informative and better written.  Thanks!
