### ISSUE TITLE
Add ResourceSync​ ​Change​ ​Notifications?

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#653]
Right now the ResourceSync capability we've implemented is just a 'Resource List'. More work is required for Describing Changes which seems to be what the project documentation wants. Creating this ticket to see what the stakeholders (@leahvanderjagt @sfarnel @johnhuck ) want to accomplish.

ResourceSync​ ​Change​ ​Notifications [from Jupiter/Coar metadata review](http://www.openarchives.org/rs/1.1/resourcesync#DesChanges)

**Comment by weiweishi** [comment]
We are not implementing ResourceSync completely in Jupiter. If this is deemed as a high priority for @leahvanderjagt and Geoff, we will need to reach out to Google and ResourceSync to tackle this issue.

**Comment by mbarnett** [comment]
Closing this, since there doesn't seem to be any way forward. We can revisit if and when ResourceSync and Google's Sitemap parsing get on the same page, instead of Google punishing any site that tries to implement ResourceSync
