### ISSUE TITLE
[Jupiter] Bad proportions for thumbnail css in search results

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#661]
Landscape-mode thumbnail are displayed with their true proportions, but portrait-mode ones are squashed to a square. Presumably we want them to appear in their true proportions.

Thumbnail:
![p1020101-20--20copy jpg](https://user-images.githubusercontent.com/272816/38587828-3ece8390-3ce0-11e8-8198-f1a7a1448b49.jpg)

Screenshot of search results:
![thumbnailsinsearchresults](https://user-images.githubusercontent.com/272816/38587933-8a343744-3ce0-11e8-8505-b579bb9c225f.png)

**Comment by pbinkley** [comment]
This problem exists in the main item page as well as in search results.

**Comment by weiweishi** [comment]
Confirmed with @leahvanderjagt and @abombak that the views (both search and item view) should:
- recognize the orientation of the thumbnail image and present accordingly in landscape/portrait mode
- critical to have thumbnails for reports/documents are presented properly with their letter-size proportion (350x270 or 4x3)
![image](https://user-images.githubusercontent.com/2047614/47049802-9bbec500-d15b-11e8-8866-548c8912037b.png)
- landscape thumbnails should be presented as is. 
- for cases that the images are out of proportion, can crop/trim the image to fit into the maximum length/width allowed.

**Comment by pbinkley** [comment]
So "out of proportion" is defined as having the short dimension < 270 when the long dimension is converted to 350? And cropping should be centered?

**Comment by weiweishi** [comment]
it would be more like
- long dimension would be a maximum of 350 (or on the view pages, a fragment of 350, such as 175px)
- if the short dimension exceeds 270, (or relative to the long dimension, such as 135 px), trim/crop the short dimension to fit 135 px.

**Comment by weiweishi** [comment]
Update this file: https://github.com/ualbertalib/jupiter/blob/master/app/assets/stylesheets/image.scss#L2-L3
with 175x135 or 4x3 dimensions.

**Comment by pgwillia** [comment]
I found an alternate solution.  https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
The results look like this:
![screenshot from 2018-11-28 15-09-32](https://user-images.githubusercontent.com/1220762/49185639-a1ddbf00-f31f-11e8-8699-0e7850683046.png)
![screenshot from 2018-11-28 15-09-24](https://user-images.githubusercontent.com/1220762/49185640-a1ddbf00-f31f-11e8-93d9-3a5aff65a328.png)
![screenshot from 2018-11-28 15-09-16](https://user-images.githubusercontent.com/1220762/49185641-a1ddbf00-f31f-11e8-9508-5b2b7653f4c0.png)
Is this acceptable?

**Comment by murny** [comment]
Might have to be careful with this approach? 
https://caniuse.com/#feat=object-fit

Looks like this doesn't work on IE11 and Some Edge  (<15) versions :cry: . 

Which might be a fair amount of users? (From looking at google analytics it looks like since jupiter launched we get about 5.8% of users using IE and 3.8% using Edge (good news is 75% of edge users are on the higher supported versions), so that's almost 8% of our user base?)

**Comment by pgwillia** [comment]
Thanks for that.  Used the solution provided.
