### ISSUE TITLE
503 for OAI path

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#670]
Since it will be a few days before the OAI server is back, let's start providing a 503 Service Unavailable response for the /oai path, with a Retry-After header of 24 hours, so people don't have to ask us if the service has moved.

**Comment by mbarnett** [comment]
Do the OAI harvesters use GET, POST, both, or <some-other-verb-goes-here>?

**Comment by pbinkley** [comment]
GET and POST are both legal. The spec doesn't use any other actions.

**Comment by mbarnett** [comment]
Perfect, thanks
