### ISSUE TITLE
Google Analytics isn't configured properly in production

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#677]
EDIT: GA code not appearing is now fixed. Keeping issue open to track PR #678 

Looks like one server has it and other doesn't. 

If you go here: view-source:https://era.library.ualberta.ca/ and refresh page a few times, you can see the GA code appearing and disappearing.

Also the javascript is cached with an empty GA_TOKEN so no page events are being sent:
https://github.com/ualbertalib/jupiter/blob/master/app/assets/javascripts/jupiter/analytics.js.erb

(maybe better solution is to move these pageview events to the same script inlined in the head, since configuration seems to be a challenge...this is fixed in PR #678 )

**Comment by mbarnett** [comment]
Weird. With Ansible's whole purpose being to deploy repeatable server configuration across a whole set of servers, this should be impossible.

**Comment by murny** [comment]
Looks like Google Analytics finally started working again on Thursday April 19th. Closing out this issue
