### ISSUE TITLE
Admin Analytics Tab

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#680]
Left as a TODO both in [wireframe](https://jupiter.mybalsamiq.com/projects/jupiter-admin/Analytics) and the live interface.
![screenshot from 2018-04-13 14-23-40](https://user-images.githubusercontent.com/1220762/38757663-0b8bb154-3f2b-11e8-8f63-ab78956057a0.png)

**Comment by mbarnett** [comment]
Superseded by #1610
