### ISSUE TITLE
Update to Bootstrap 4.2.1

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#683]
There is no breaking changes so https://github.com/ualbertalib/jupiter/pull/682 has been/will be merged. But there is a few new things and some nice utilities added so we should do some refactoring for this.

https://blog.getbootstrap.com/2018/04/09/bootstrap-4-1/

**Comment by weiweishi** [comment]
- [ ] update to the latest bootstrap version PR https://github.com/ualbertalib/jupiter/pull/960
- [ ] @murny  and @ConnorSheremeta  will go through the bootstrap changelog together to identify places that require refactoring

**Comment by ConnorSheremeta** [comment]
This is now in master, closing issue

**Comment by ConnorSheremeta** [comment]
This is now in master, closing issue
