### ISSUE TITLE
Jupiter: The main search results should sort by relevance by default 

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#693]
It's unintuitive and doesn't make much sense that when you search for a specific title, it can be pages deep, because we currently sort by title.

Leah writes: 

> The user story is: "When I search ERA,  I expect my results to be sorted according to the returned item's relevance to the text I have submitted to the search form." or something like that. I agree we could look at how Sam has dealt with this stuff.

Collection pages and other pages displaying a faceted interface should continue to sort by title in the absence of a specific search parameter.

Needs consultation w/ Metadata re: if they want to track how specific fields are weighted.

**Comment by weiweishi** [comment]
This is deemed as high priority.

**Comment by pbinkley** [comment]
Note that Solr uses relevance ranking if the query is sorted by "score", or if the sort field is not specified. I'd suggest going with the default Solr relevance ranking at first, and let Metadata evaluate that before putting effort into tweaking weighting of fields.
