### ISSUE TITLE
Wireframes for admin features

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#70]
Includes desktop and mobile view. User needs documented here: https://docs.google.com/document/d/1708SrAcuFZJaW-S73OscPpYIGZQ4SNjrtROHSul_Nf4/edit

Dashboard landing page: 
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Dashboard

Site messages / notifications: 
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Announcements

Manage and edit static pages: 
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Static%20Pages
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Edit%20Static%20Page

Manage users: list, detail, login as pages:
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Users
https://jupiter.mybalsamiq.com/projects/jupiter-admin/User%20Detail

Manage communities and collections: landing, add/edit community and collection, detailed community collection
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Communities%20and%20Collections
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Create%20Community
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Create%20Collection
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Community%20Detail
https://jupiter.mybalsamiq.com/projects/jupiter-admin/Collection%20Detail

Still outstanding are mockups for item management - requires completion of search results wireframing and item submission / edit wireframing before we can complete this peice.

**Comment by sfbetz** [comment]
Admin- manage items wireframes done:

https://jupiter.mybalsamiq.com/mockups/6133900.png

**Comment by cwant** [comment]
@sfbetz @leahvanderjagt (Leah), a couple of comments about the user detail page here:

https://jupiter.mybalsamiq.com/projects/jupiter/Admin%20-%20user%20management%20detail%20view

* Wireframe does not indicate whether the user is an admin or regular user;
* In the item list, it might be better to move the edit/delete buttons into the item title column rather than in the date deposited.

**Comment by leahvanderjagt** [comment]
I think this is all Admin. I will let @sfbetz comment on the placement of
those buttons b/c I am ambivalent about the choice

___________________________________________________________



*Leah VanderjagtDigital Repository Services Coordinator, University of
Alberta t. 780.492.3851 / **leahv@ualberta.ca <leahv@ualberta.ca> *

*The University of Alberta is situated on traditional Treaty 6
territory and homeland of the Métis peoples.*
Amiskwaciwâskahikan / ᐊᒥᐢᑲᐧᒋᕀᐋᐧᐢᑲᐦᐃᑲᐣ / Edmonton

**Comment by sfbetz** [comment]
The item list in Admin - user management was a placeholder waiting on completion of Admin -manage items (which is now done) - sorry! We want item management to present consistently across all screens, so any screen where a user is managing items should look the same (and I think is waiting on search). I've updated the wireframes accordingly.

**Comment by sfbetz** [comment]
And just to clarify following up on a convo with @cwant - it would  be very useful to have the user's role listed as well (eg "Admin", "User").

**Comment by weiweishi** [comment]
Close this ticket as I believe the wireframes are now completed
