### ISSUE TITLE
PMPY implementation in Jupiter

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#702]
I believe all the work has been down to bring PMPY inline with Jupiter's data model, we need to implement this in production ASAP. 
- [x] Add code to Jupiter on save to push IDs into preservation queue #720 
- [x] Update logging to capture additional information https://github.com/ualbertalib/pushmi_pullyu/issues/144 (PR here: https://github.com/ualbertalib/pushmi_pullyu/pull/146)
- [x] Test of PMPY in test env
- [x] coordinate with Ops to implement
  - [x] set up a new container in ERA (called jupiter)

**Comment by murny** [comment]
Work for the first two bullets are completed in PRs (#720  and https://github.com/ualbertalib/pushmi_pullyu/pull/146). 

So once these are reviewed and merged we can get this on staging for testing. 

In mean time I'm going to go work on a different issue (update my CSP PR to work with 5.2).

**Comment by weiweishi** [comment]
All tasks are completed. PMPY is in place.
