### ISSUE TITLE
Monitor Google Search Console Excluded/Duplicate Content

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#704]
We've got 176k items excluded from Google's index right now, all of which seem to be new URLs for file downloads. It's unclear if this is a temporary situation until Google notices the 301 Moved Permanently redirects on the former location of these files. We should keep an eye on this.

**Comment by pgwillia** [comment]
>Index coverage issues successfully fixed for site https://era.library.ualberta.ca/
>To owner of https://era.library.ualberta.ca/,
>Google has validated your fix of Index coverage issues on site https://era.library.ualberta.ca/. The specific issue validated was 'Submitted URL blocked by robots.txt'.
>3644 pages on your site were validated as fixed.
>To examine full details on the validation progress and to learn if there are other Index coverage related issues to fix, please follow this link.

![screenshot from 2018-07-09 13-00-43](https://user-images.githubusercontent.com/1220762/42470569-20246d68-8378-11e8-8b3b-857d10f737d4.png)

**Comment by weiweishi** [comment]
The concern mentioned in this particular issue seems no longer present. Close the ticket.  
![image](https://user-images.githubusercontent.com/2047614/47050143-87c79300-d15c-11e8-8d00-0619089abd78.png)
