### ISSUE TITLE
Jupiter: wrong orientation in thumbnail of portrait-mode jpg

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#783]
**Describe the bug**
When a jpg using EXIF Orientation to express portrait mode is deposited, the thumbnail is rendered in landscape mode, i.e. it looks sideways with the top of the image to the left.

**To Reproduce**
1. Download [this image](https://era.library.ualberta.ca/items/50db1ef8-7010-42cd-b799-402e57ddd26e) from ERA
2. Deposit it into a current Jupiter instance

**Expected behavior**
The thumbnail should be in portrait mode, with the statue's head at the top

**Screenshots**
![volodya](https://user-images.githubusercontent.com/272816/43025504-4674f784-8c2f-11e8-8aaf-84dabe56c995.png)

**Additional context**
The example is from production ERA, and I've confirmed that the same thing happens in a fresh deposit in a dev instance of current master (8a7586e). The example jpg's EXIF properties have "Orientation: Right-top".

**Comment by weiweishi** [comment]
There is a big image collection needs to be ingested and this may affect the collection. so 
@leahvanderjagt will send the link to the batch so we can test objects with portrait orientation to see if this affects them. If so, this becomes a higher priority.

**Comment by weiweishi** [comment]
@leahvanderjagt will send the link to the batch, and we will test and do spike to investigate the impact on this collection.

**Comment by leahvanderjagt** [comment]
Links to the batches:
Manifest: https://drive.google.com/open?id=1AlflT-SSNPIoLN-GAjlm37-dCzigHd5Q-8fWGwq0SJ8
Files: https://drive.google.com/open?id=1_0nUIW_uYF9Mae96o7xvse9C9azJ18C0

**Comment by weiweishi** [comment]
verified several portrait mode photos in this collection that they are not impacted. 
https://drive.google.com/open?id=11eBLhVbdUqVYs_03yNjq1WjNSYAUPObn
https://drive.google.com/file/d/1XReW8h5_lLt8DWwnoU54QqhkRcrrAMvG/view
https://drive.google.com/file/d/15HKBaS-IDyGCyOcKW9xz96SuH7xFSOtq/view

Remove this ticket from current sprint based on our discussion. @leahvanderjagt

**Comment by pbinkley** [comment]
Note that the samples in Weiwei's set don't have the EXIF Orientation property set, so they are natively portrait mode. The fact that they work shows that this batch is ok (assuming the whole batch is consistent), but it leaves open the question whether images that use EXIF Orientation will be correctly handled.

**Comment by pbinkley** [comment]
The question at this point is whether old mis-oriented EXIF images will produce good thumbnails if the derivatives are regenerated. If this can be confirmed, we just need to regenerate all thumbnails for these images. The scope of the current issue is to test the regeneration; if it's good, spin off another issue to script the regenerating.

Timebox for investigation: 1/2 day

**Comment by pbinkley** [comment]
When processing with Imagemagick convert, it looks like the ```-auto-orient``` flag will take care of orienting the image according to the EXIF orientation: http://www.imagemagick.org/script/command-line-options.php#auto-orient
