### ISSUE TITLE
Jupiter: Deposit item type "Conference/Workshop Presentation" becomes "Conference Paper"

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#789]
**Describe the bug**
When an item is deposited with item type "Conference/Workshop Presentation", it becomes "Conference Paper" once the item is saved.

**To Reproduce**
1. Deposit an item with Item type  "Conference/Workshop Presentation"
2. Save

**Expected behavior**
Item type should remain  "Conference/Workshop Presentation"

**Additional context**
I've just deposited an item this way in UAT http://uat.library.ualberta.ca/items/f63df45f-c375-4104-a69c-0ac90cc3f2f2 

**Agreed strategy**
- Conference/Workshop Poster remains mapped to http://vivoweb.org/ontology/core#ConferencePoster but the display label in the data dictionary and on the item view page is revised to Conference/Workshop Poster
- Conference/Workshop Presentation should be mapped to http://vivoweb.org/ontology/core#Presentation and the display label in the data dictionary and the item display page is revised to Conference/Workshop Presentation
- items with current property http://vivoweb.org/ontology/core#ConferencePaper have it replaced with http://vivoweb.org/ontology/core#Presentation
- will take the site down to update the URIs all at once. Will notify @leahvanderjagt when this is planned 
- Will coordinate with @sfarnel's team for the data cleaning task

**Comment by sfarnel** [comment]
The item types in the list do not match up with the data dictionary.  @weiweishi @pbinkley @leahvanderjagt can @danydvd and I touch base with you to review and make changes as needed?

**Comment by pbinkley** [comment]
I've confirmed that the item was saved with ```type: http://vivoweb.org/ontology/core#ConferencePaper``` in Fedora.

**Comment by weiweishi** [comment]
I think maybe a quick touch-base would be good.

The data dictionary indicates that we don't have a data type:
Conference/Workshop Presentation. We have one for Conference Paper, and one
for Conference Poster.

I recall a past discussion that we agreed to map Conference/Workshop
Presentation to Conference Paper, but I can't find that trace of that
discussion anymore. So clarification on this data type would be really
helpful.

Cheers!

Weiwei


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by pbinkley** [comment]
The user concern that Anna mentioned was the desire to distinguish the
slides from the actual paper; so "presentation" is what they were after.

**Comment by weiweishi** [comment]
Then we will probably need
- modification on the data dictionary to add new data type
- modification on code to add new data type
- potential data cleaning work?


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by sfarnel** [comment]
When we investigated this we didn't find a vocab that a general property for "presentation" so rather than minting our own we went with the designation between paper/poster. But I can see instances where something more generic may be worthwhile. If this is so desired, we can a) investigate whether there may be a vocab now that has a usable property, b) define our own. I will ask @danydvd to do some investigating.

**Comment by sfarnel** [comment]
Thanks @danydvd this would seem to capture the more generic 'presentation'. 

So my understanding then is:

- Conference/Workshop Poster remains mapped to http://vivoweb.org/ontology/core#ConferencePoster but the display label in the data dictionary and on the item view page is revised to Conference/Workshop Poster
- Conference/Workshop Presentation should be mapped to http://vivoweb.org/ontology/core#Presentation and the display label in the data dictionary and the item display page is revised to Conference/Workshop Presentation
- items with current property http://vivoweb.org/ontology/core#ConferencePaper have it replaced with http://vivoweb.org/ontology/core#Presentation

Is that correct @pbinkley @weiweishi @leahvanderjagt @danydvd ?

**Comment by pbinkley** [comment]
I like the presentation option but I don't think we've done any kind of
process to add it - @leahvanderjagt how do you feel about it?

**Comment by weiweishi** [comment]
@leahvanderjagt has approved the strategy to handle this new content type.

**Comment by danydvd** [comment]
- The display label in the data dictionary for http://vivoweb.org/ontology/core#ConferencePoster is revised to Conference/Workshop Poster.
- http://vivoweb.org/ontology/core#Presentation is added to the data dictionary and the display label is set to Conference/Workshop Presentation.
- http://vivoweb.org/ontology/core#ConferencePaper is removed from data dictionary.

**Comment by mbarnett** [comment]
Note from grooming meeting:

This may require us to either:

1) take the site down to update the URIs all at once

 or 

2) add the new URI (while retaining the old URI), cleaning up the data at our leisure, and then removing the old URI once that process is complete

Removing the old URI but leaving the site up will cause the application to crash/misbehave when displaying or editing items with the old URI on them.

**Comment by weiweishi** [comment]
Deployed to production.
