### ISSUE TITLE
Thesis Graduation Date displaying date twice

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#798]
Some theses that have a more specific (yyyy-mm) Graduation Date have the date information appearing twice, e.g. (https://doi.org/10.7939/R3RR1Q16P), 

Graduation date
    2017-11:Fall 2017

Others seem fine, e.g. (https://doi.org/10.7939/R3SB3XD61),

Graduation date
    Spring 2018

The display should be like the second example.

**Comment by weiweishi** [comment]
@sfarnel this seems to be a data issue that needs to be fixed. The data for the first object is:
```
Thesis.find('1d101233-6a43-4c9d-80c6-617ef9c2592e').graduation_date
=> "2017-11:Fall 2017"
```

**Comment by sfarnel** [comment]
Thanks @weiweishi I will ask @anayram to look at this data and make the fixes

**Comment by anayram** [comment]
Created issue in metadata repo with reference to present ticket. Closing and following up at ualbertalib/metadata/issues/383
