### ISSUE TITLE
Jupiter: Fix flapping tests

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#811]
Three tests are continually flapping on Travis CI (although they seem reliable locally). The flapping portions were disabled in these PRs https://github.com/ualbertalib/jupiter/pull/810/files and https://github.com/ualbertalib/jupiter/pull/812/files, but we should fix this ASAP to restore the coverage for the portions of the tests currently being skipped.

**Comment by pgwillia** [comment]
1987 / 2739 LOC (72.54%) covered now vs 2183 / 2739 LOC (79.7%) covered recently.
Specifically the deposit wizard has lost out on coverage.

**Comment by weiweishi** [comment]
We will timebox it for 2 days for Sprint 4.

**Comment by murny** [comment]
Another flapping test that's been cropping up a few times currently in travisCI is this one:
https://travis-ci.org/ualbertalib/jupiter/builds/428341082
```

Failure:
SearchControllerTest#test_should_get_results_in_relevance_order_when_a_query_is_present [/home/travis/build/ualbertalib/jupiter/test/controllers/search_controller_test.rb:90]:
--- expected
+++ actual
@@ -1 +1 @@
-["8aac2982-8a18-416c-b4b7-6b7a60d238b2", "d26e9b4e-26ee-4994-bfcc-ad34b2ca33a6", "bc044ae5-3a1c-4d39-a459-52ae1cda38da"]
+["8aac2982-8a18-416c-b4b7-6b7a60d238b2", "bc044ae5-3a1c-4d39-a459-52ae1cda38da", "d26e9b4e-26ee-4994-bfcc-ad34b2ca33a6"]
bin/rails test test/controllers/search_controller_test.rb:86
```
Essentially the array isn't coming back in the correct order :thinking:

**Comment by mbarnett** [comment]
But only sometimes? Maybe relevance sort isn't stable in solr...

**Comment by murny** [comment]
Yeah only sometimes, its flapped on last couple dependency upgrades...rerunning the build fixes it.

**Comment by pgwillia** [comment]
Replying to https://github.com/ualbertalib/jupiter/issues/811#issuecomment-421146853

The problem is that the scores of those two documents are identical.
```
"response":{"numFound":3,"start":0,"maxScore":0.81081206,"docs":[
      {
        "id":"4b9ef927-99db-403b-a751-5b3e335346b1",
        "score":0.81081206},
      {
        "id":"462facb0-edf6-4bac-92f4-ca84ebb335b4",
        "score":0.50675756},
      {
        "id":"7b506374-dbf4-4456-b92c-cb8706abb5bd",
        "score":0.50675756}]
  },
```
If I make the title of item3 longer then it will be scored lower and stop the test from flapping.

**Comment by pgwillia** [comment]
![failures_test_be_able_to_deposit_a_new_item_into_jupiter_successfully](https://user-images.githubusercontent.com/1220762/45576722-9f49ee00-b835-11e8-98f7-2d9466135729.png)
Is it just that the header is covering part of the selector?
![failures_test_be_able_to_deposit_a_new_thesis_into_jupiter_successfully](https://user-images.githubusercontent.com/1220762/45576723-9fe28480-b835-11e8-91df-7a77f9a53ab0.png)
Same?!
![failures_test_anybody_should_be_able_to_sort_results](https://user-images.githubusercontent.com/1220762/45576726-a1ac4800-b835-11e8-8d1e-ab2ded66d83c.png)
Is this the relevance order being equal quirk?

**Comment by pgwillia** [comment]
Reading list:
https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

Going to schedule cron of this job daily until someone picks this up again to (hopefully) get more data points. https://travis-ci.org/ualbertalib/jupiter/settings

**Comment by pgwillia** [comment]
Re: https://github.com/ualbertalib/jupiter/blob/master/test/system/search_test.rb#L249
https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html#CommonQueryParameters-ThesortParameter
Something like `score desc, title_ssi asc` would be helpful but not easy to change in our implementation.

**Comment by weiweishi** [comment]
- Could rewrite the test to remove the javascript/use the file location for the file upload.
- Could make smaller tests to cover complete feature tests.

**Comment by pgwillia** [comment]
https://travis-ci.org/ualbertalib/jupiter/builds/478263501?utm_source=github_status&utm_medium=notification

Error:
DepositItemTest#test_should_populate_community_and_collection_when_coming_from_collection_page:
Capybara::ElementNotFound: Unable to find link or button "Log In"
    test/application_system_test_case.rb:26:in `login_user'
    test/system/deposit_item_test.rb:106:in `block in <class:DepositItemTest>'
bin/rails test test/system/deposit_item_test.rb:103

**Comment by pgwillia** [comment]
Will pick this up in a new issue.
