### ISSUE TITLE
Jupiter: Add Changelog to the project

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#819]
As agreed, we will add CHANGELOG.md to the project. 
**Requirements**
- key audience will be for the product owner, stakeholders, service support team, and other potential adopters of the codebase, instead of devs. 
- It should use plain language instead of technical language and summarize the notable changes including features/bug fixes
- It should use proper markdown
- It should provide a link back to the main issues (Epic, features, or original bug reports)
- It should keep an "Unreleased" section at the top to keep track of work that hasn't been released into production yet. 
- It should list releases in reverse-chronological order 
- An example to follow is:
https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by mbarnett** [comment]
With the idea here that this should be updated by Pull Requests containing the relevant changes, so every PR author is responsible for their own Changelog updates. @murny to look at adding a Danger rule to help enforce this.

**Comment by weiweishi** [comment]
Changelog is now in place. Close the ticket.
