### ISSUE TITLE
I18n and ERB everything

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#83]
Let's remove all HAML and I18n all things in the views and else where (anything that gets displayed to an end user)

Done when:
- [x] Convert all HAML views to ERB
- [x] Remove all hard coded strings to I18n in views, models, controllers, etc
- [ ] Organize I18n en.yml file

**Comment by mbarnett** [comment]
PITA but if we could add a checklist of known areas where this needs to happen for this to be considered done,

![that would be great](https://media.tenor.com/images/3f59e47524bcc4e3244bb09f89d7705d/tenor.gif)
