### ISSUE TITLE
Page not found (404) error on item deposit

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#840]
**Describe the bug**
At the final stage of item upload through the interface, hit the button to deposit and received this error:

![image](https://user-images.githubusercontent.com/4697932/44858875-386ee700-ac30-11e8-91f7-8dc70122e961.png)

**To Reproduce**
1. Log into ERA
2. Click on Deposit
3. Describe item
4. Upload file
5. Hit Deposit item

**Expected behavior**
Item should be created in ERA

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Windows 7
 - Firefox
 -  52.9.0 (64-bit)

**Comment by weiweishi** [comment]
@sfarnel seems to be a one-time error? Do you remember which community/collection you were trying to deposit into?

**Comment by sfarnel** [comment]
Thanks @weiweishi it looks like it must have worked in the end as there seem to be two copies of the item in ERA. Can you delete cb5155ac-b6ce-4a6b-8dd8-6723bcc23b88 Will let you know if the problem comes up again.

**Comment by sfarnel** [comment]
Thanks @weiweishi I was able to add the file to the other one (d9de33ed-9926-4fe2-9109-6442e1d0c1a8) so you can go ahead and deletecb5155ac-b6ce-4a6b-8dd8-6723bcc23b88

**Comment by weiweishi** [comment]
The record is now removed - close the issue.
