### ISSUE TITLE
[Jupiter] Clamav package update breaks the virus checking on deposit

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#869]
Clamav packages were updated on Wednesday night on production application servers:

```
clamav-data-0.100.1-3.el7.noarch              Wed 19 Sep 2018 04:23:01 AM MDT
clamav-server-systemd-0.100.1-3.el7.x86_64    Wed 19 Sep 2018 04:22:58 AM MDT
clamav-scanner-systemd-0.100.1-3.el7.x86_64   Wed 19 Sep 2018 04:22:58 AM MDT
clamav-devel-0.100.1-3.el7.x86_64             Wed 19 Sep 2018 04:22:58 AM MDT
clamav-0.100.1-3.el7.x86_64                   Wed 19 Sep 2018 04:22:58 AM MDT
clamav-update-0.100.1-3.el7.x86_64            Wed 19 Sep 2018 04:22:44 AM MDT
clamav-lib-0.100.1-3.el7.x86_64               Wed 19 Sep 2018 04:22:44 AM MDT
clamav-filesystem-0.100.1-3.el7.noarch        Wed 19 Sep 2018 04:22:44 AM MDT
```
And this breaks the virus check on deposit. (Same issue was identified on the staging environment the day before. )

![image](https://user-images.githubusercontent.com/2047614/45770755-8019da80-bc00-11e8-90a7-287abd3b8513.png)

Actions taken/required:
- [ ] temporarily disable 
- [ ] Sys admin will revert to an earlier working version and lock the version
- [ ] enable
- [ ] rescan files ingested
- [ ] better communication when problem is noticed on staging, how to stop the auto update in production before the issue is solved. 

@nmacgreg @henryzhang87 @kgood @pbinkley I think this captured our conversation re: solution for this issue?

**Comment by weiweishi** [comment]
Checked that gem version used in the app. Unchanged, and no new version is available. 
  * clamby (1.4.0)

**Comment by henryzhang87** [comment]
# Troubleshootings

- step 1: check if the command line is running well as root
   
   clamscan  /var/tmp/demo.txt

   if it runs well, that means clamav is not a problem

- step 2: there is a rake task in /var/www/sites/jupiter/lib/tasks named clamav.rake

```
cd /var/www/sites/jupiter
RAILS_ENV=production rake clamav:check_virus["/era_assets/ZZ/wq/ZZwqy7D5Dx91VXdMrBnfAdhc"]

if this works well as root, then further proof that clamav application is not a problem
```
- step 3: check with user "apache", that is what Jupiter app is running under

```
[root@kendal ~]# cd /var/www/sites/jupiter/
[root@kendal jupiter]# sudo -u apache RAILS_ENV=production rake clamav:check_virus["/era_assets/ZZ/wq/ZZwqy7D5Dx91VXdMrBnfAdhc"]
ERROR: Could not connect to clamd on LocalSocket /var/run/clamd.scan/clamd.sock: Permission denied
ClamAV 0.100.1
ERROR: Could not connect to clamd on LocalSocket /var/run/clamd.scan/clamd.sock: Permission denied
```
The above showed that it is a permission problem for the user "apache". It doesn't have enough permission to access /var/run/clamd.scan/clamd.sock

- step 4: check the permission on /var/run/clamd.scan
```
[root@kendal jupiter]# ls -lh /var/run/ | grep clam
drwx--x---.  2 clamscan   virusgroup   60 Oct  2 05:06 clamd.scan

```
# Diagnosis

From the above, it is owned by clamscan and belongs to virusgroup. Apache doesn't belong to virusgroup. In addition, its mode is 710, which means that apache has no access to the directory at all

# Solution

In the ansible playbook, do the followings

- chmod 0770 /var/run/clam.scan
- usermod -G clamscan,virusgroup apache
