### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#87]
DONE WHEN: 

- [ ] We have breadcrumb pathing in the UI similar to those shown in the mockups

Note that an item can belong to multiple community/collection pairs, so a stakeholder question would be how this should be represented in the UI

**Comment by cwant** [comment]
I think I remember this being asked of Leah at the Monday meeting: I think the answer was to show multiple sets of breadcrumbs.

**Comment by leahvanderjagt** [comment]
Yes, Sonya and I think we should just list both breadcrumb paths. We will
do some UX exploration around that to see if it's confusing to users.



___________________________________________________________



*Leah VanderjagtDigital Repository Services Coordinator, University of
Alberta t. 780.492.3851 / **leahv@ualberta.ca <leahv@ualberta.ca> *

*The University of Alberta is situated on traditional Treaty 6
territory and homeland of the Métis peoples.*
Amiskwaciwâskahikan / ᐊᒥᐢᑲᐧᒋᕀᐋᐧᐢᑲᐦᐃᑲᐣ / Edmonton

**Comment by cwant** [comment]
For reference, here is the aforementioned mockup:

https://jupiter.mybalsamiq.com/projects/jupiter/Item%20view

**Comment by cwant** [comment]
Merged via PR #104
