### ISSUE TITLE
Extraneous text appearing along with Conference/Workshop Poster in Item type filter

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#879]
**Describe the bug**
Extraneous text appearing with item type Conference/Workshop Poster in Item Type filter.

**To Reproduce**
1. Go to ERA home page
2. Click on Search
3. Scroll down to the item type filter
4. Click on Show 4 more
5. See "translation error: ..." that shows as part of the item type

**Expected behavior**
Item type should appear as Conference/Workshop Poster

**Screenshots**
![image](https://user-images.githubusercontent.com/4697932/46164309-e62edf00-c24a-11e8-837f-db0188a0df4d.png)

**Desktop (please complete the following information):**
 - Windows 7 Enterprise
 - Firefox 60.2.4

**Comment by weiweishi** [comment]
discovered typo in the code. Will make the change and hopefully to get into the next release tomorrow.
