### ISSUE TITLE
File downloads

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#88]
Files are serialized into Fedora by Hydraworks. This _should_ be fairly straightforward, but we may need to reference Hyrax's implementation.

(I've moved multi-file zipping to its own ticket)

DONE WHEN:
- [x] Files can be downloaded via Jupiter
- [ ] Download permissions are being applied correctly via policy (owner or user is authenticated if visibility is authenticated or anyone if visibility is public)
- [ ] Correct masking of buttons when user does not have correct permissions
- [x] UI "files section sidebar" partial is implemented.

**Comment by weiweishi** [comment]
just to confirm that this issue is not yet done in PR #279, for all the permission handling etc? @mbarnett

**Comment by mbarnett** [comment]
The exact permission logic has not been wired up, but it is stubbed out at the moment.

**Comment by mbarnett** [comment]
More specifically, we just need to decide exactly what the logic in here should be: https://github.com/ualbertalib/jupiter/blob/master/app/policies/item_policy.rb#L28

**Comment by leahvanderjagt** [comment]
Hi Matt, do you need stakeholder input? I'm happy to provide if necessary

**Comment by mbarnett** [comment]
I have a feeling this is already defined somewhere else, but if you want to dump the info in here we can get this finished off.

I think the logic is something like: You can download all of the files in an item if any of the following are true:

1) You're an admin

2) You own the item

3) The item is open access and you're anyone, logged in or not logged in

4) The item is ccid protected and you're logged in with a ccid

Are those all of the scenarios? Are there any others?
