### ISSUE TITLE
[Jupiter] Batch Ingest Request: Medical Laboratory Images

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#883]
**Brief description of the batch**
This is a batch of images from a faculty member in Medical Laboratory Sciences. This was part of a CTL funded OER project in the summer of 2018. 

**Manifest**
https://docs.google.com/spreadsheets/d/1ZrTS4ah1gO8SMnM-msIWtGizeJlE527w-SfTzcGux14/edit?usp=sharing

**Batch files**
https://drive.google.com/drive/folders/16XaL-jEYsuqbxbcy8lEvLo9kAkUQ9Fri?usp=sharing 

**Additional notes**
Version of batch ingest template: https://docs.google.com/spreadsheets/d/178o_-ZEV3Ii-IzJ0AcJQTQqFsH3Ew2WCgyj2aZw99iY/

**Comment by weiweishi** [comment]
@sfarnel Some of the objects in this bach have been ingested successfully. However the number of the files in the batch doesn't match the number of records in the manifest? Would you please check?

Thank you!

**Comment by sfarnel** [comment]
Thanks @weiweishi Argh; something obviously went awry when I copied these from Team to Shared Drive. All images should now be in the folder.

**Comment by sfarnel** [comment]
Thanks @weiweishi Will ensure file extension is there in future, and that the manifest and objects are in the same folder (others in the batch folder were separated so I was following that). Report looks great! Closing ticket.
