### ISSUE TITLE
[Jupiter] OpenSearchDescription 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#893]
Similar to this issue, add it for Jupiter as well
https://github.com/ualbertalib/discovery/issues/1243

**Comment by weiweishi** [comment]
Leah doesn't think we need to implement this for ERA.

**Comment by murny** [comment]
While it may not be "needed", it's a free improvement to usability and accessibility of our site (both things we care about). 

And it takes a few minutes to implement (especially since we have to fix/add it to discovery anyways). So why not add it?
