### ISSUE TITLE
Deposits will not save into certain ERA Communities/Collections

### ISSUE THREAD

**Issue by ERAHelp** [ualbertalib/jupiter#895]
User reported that item deposited into Psychology, Department of/Journal Articles (Psychology) Community/Collection will not Save and returns a "Page Not Found" error.  Error traced by Weiwei to the /Journal Articles (Psychology) Collection. An item was successfully deposited to this C/C by this user in 2017, however.

This is a continuance of a bug reported on October 10/2018 by another user, where the Centre for Teaching and Learning (CTL) / Presentations (Centre for Teaching and Learning) Community/Collection reported the same error when attempting to deposit an item. Weiwei has corrected this specific C/C for this specific user.

I checked ERAHelp mail to determine that the CTL C/C was created on August 17, 2018 -- "The new CTL Community/Collections are here: https://era.library.ualberta.ca/communities/bfb75d06-72cf-40c3-9560-6b8f599a4b05"

Anna

**Comment by sfarnel** [comment]
Also came up in https://github.com/ualbertalib/jupiter/issues/840

**Comment by weiweishi** [comment]
I believe this has already been fixed? @ERAHelp @abombak ?

**Comment by abombak** [comment]
Ack! Tickets from two years ago when my memory only goes back to yesterday! ;-)  I believe that this was corrected, yes, and the issue can be closed.

Anna
