### ISSUE TITLE
500 error when navigating to a collection

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#898]
I receive a 500 error when I try to navigate to the Northern North America Collection.

1. Go to ERA home and click on collections
2. Type halpern in the search bar and select Joel Martin Halpern Image Archive
3. Under Collections in this Community click on Northern North America Collection
4. See error below:

![image](https://user-images.githubusercontent.com/4697932/47534735-bb4da000-d875-11e8-9ef9-a18a9ba3aa65.png)

I should get to the list of the items in the collection.

**Desktop (please complete the following information):**
 - Windows 7 Enterprise
 - Firefox Quantum 60.3.0

**Comment by weiweishi** [comment]
I think this is caused by one of the items on the first page of this collection. 

Getting this error message in the log. Maybe we should do better things to handle the error raised from these problematic files. 
ActionView::Template::Error: `identify /tmp/mini_magick20181012-38321-wt3u0k.jpg` failed with error:identify: Not a JPEG file: starts with 0xef 0xbf `/tmp/mini_magick20181012-38321-wt3u0k.jpg' @ error/jpeg.c/JPEGErrorHandler/316

**Comment by mbarnett** [comment]
This issue has the somewhat dubious distinction of being one of the oldest bugs that yesterday's deployment fixed!

At long, long last the Joel Martin Halpern Image Archive's Northern North America Collection is browsable, and this is the corrupted image in question that was long keeping it from being browsable: https://era.library.ualberta.ca/items/f1c4404a-f946-4077-8356-572b5cc10b0a

**Comment by mbarnett** [comment]
@seanluyk just flagging the data issue on that one item over to you if there's anything that anyone can or wants to about getting a working copy of that image or clean up that record

**Comment by seanluyk** [comment]
@mbarnett, thanks, we'll track down a replacement file

**Comment by seanluyk** [comment]
@mbarnett a replacement file has been tracked down, with thanks to @piyapongch and @kgood! But, when I attempt to edit to swap in the new file, I still get a 500 error. Object in question: https://doi.org/10.7939/R3RF5KF6T

**Comment by mbarnett** [comment]
Hmm, I think I can see what the issue is in Rollbar. I'll try fixing it and report back later on today.

**Comment by mbarnett** [comment]
@seanluyk You should be able to edit it and swap the file, now

**Comment by seanluyk** [comment]
@mbarnett thanks, the file has been successfully swapped

**Comment by pgwillia** [comment]
![image](https://user-images.githubusercontent.com/1220762/179624449-e06846fc-d39a-4da6-ac91-83cc668f4a50.png)
