### ISSUE TITLE
Multi-file zipping for multi-file downloads

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#90]
Decision captured from the mockup meeting and comment below:

For phase 1, Leah is okay with just having the "Download all" button to simply just initiate the download for all files (much like google drive etc aka as if the user actually clicked each and every download button themselves).  aka: queue up multiple parallel downloads. 

Wishlisty down the road:

Zipping all files with the license file would be a nice to have. But since we do not store this anywhere we would have to generate this on the fly. This could take a long time to process this request. (we could email them to the user when the zip has been finished but what about users who are not logged into the system etc?)

If zip is very easy to accomplish (without the license) then probably do the zip approach (zip file is probably a better UX anyways)? Looks like dropbox creates a zip file for multiple files. Needs some investigation of the two approaches.

**Comment by murny** [comment]
From mockup meeting, Leah is okay with just having the "Download all" button to simply just initiate the download for all files (much like google drive or dropbox etc).

Zipping all files with the license file would be a nice to have. But since we do not store this anywhere we would have to generate this on the fly. This could take a long time to process this request. (we could email them to the user when the zip has been finished but what about users who are not logged into the system etc?)

**Comment by mbarnett** [comment]
Just so I'm clear, meaning we would queue up like 10 parallel downloads in the browser or w/e?

**Comment by murny** [comment]
Yes exactly

**Comment by leahvanderjagt** [comment]
Yes

___________________________________________________________



*Leah VanderjagtDigital Repository Services Coordinator, University of
Alberta t. 780.492.3851 / **leahv@ualberta.ca <leahv@ualberta.ca> *

*The University of Alberta is situated on traditional Treaty 6
territory and homeland of the Métis peoples.*
Amiskwaciwâskahikan / ᐊᒥᐢᑲᐧᒋᕀᐋᐧᐢᑲᐦᐃᑲᐣ / Edmonton

**Comment by mbarnett** [comment]
Well that's somewhat easier. I don't know if any discussions happened wrt external (to Fedora) file storage happened while I was gone, but the parallel downloads would tend to argue in favor of that, as the performance of starting N different connections with the Rails server to stream the files piecewise from Fedora could be an issue, although we might be able to live with it for the time being.

**Comment by weiweishi** [comment]
Need to confirm if the work is already been done. @murny
