### ISSUE TITLE
[Jupiter] Fall 2018 Thesis Ingest

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#906]
**Brief description of the batch**
This is the fall 2018 Thesis ingest from IST's Thesis depositor Alfresco instance

**Manifest**

https://drive.google.com/file/d/0BzYFAJbWCvK5OXhHN250dEpUOVhFUi1xTmp1aW5HQXlDaVhV/view?usp=sharing
(only selected people are shared with this file, please contact Weiwei if you need access)

**Batch files**
Files are in IST's Alfresco system. 

**Additional notes**
Batch ingest to be completed before Nov. 15.

**Comment by weiweishi** [comment]
FYI, @leahvanderjagt @ERAHelp @abombak

**Comment by sfarnel** [comment]
Thanks @weiweishi When these are ingested can you send me the list of DOIs (if it's easy to augment this list or just provide author, title, DOI) then I will have sent for cataloguing after Nov 15 embargo is lifted. Thanks!

**Comment by weiweishi** [comment]
batch ingest completed and the batch ingest report is at https://drive.google.com/file/d/1VZC6KzCCk5V9vxe5-NKJVZBCpVOCk7s1/view?usp=sharing
@sfarnel please let me know if this is sufficient.

**Comment by sfarnel** [comment]
Thanks @weiweishi There seems to be some weird parsing of the data; would you be able to check that. If not we can fix on this end.

**Comment by weiweishi** [comment]
The file is delimited by "|" instead of ",". If you download the file and adjust the delimiter's setting, it should be okay. Google Drive rendering the file weirdly. Also attached the plain txt file here, should be okay to parse but let me know otherwise. Thanks @sfarnel 
[ERA-Thesis-Fall_2018_batch_ingest_report.txt](https://github.com/ualbertalib/jupiter/files/2586696/ERA-Thesis-Fall_2018_batch_ingest_report.txt)

**Comment by weiweishi** [comment]
Hi @sfarnel it seems that the embargoes lifted properly? The three you sent all have an embargo date of 2020-11-15 and that's why they are not visible/accessible yet. Here I've attached the new report, including only the publicly accessible ones:
[ERA_Fall_ingested_thesis_without_embargoed_items.txt](https://github.com/ualbertalib/jupiter/files/2590287/ERA_Fall_ingested_thesis_without_embargoed_items.txt)

**Comment by sfarnel** [comment]
Thanks @weiweishi List sent off for cataloguing. Closing issue and will reopen if anything comes up.
