### ISSUE TITLE
"Viewers"

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#91]
Presumably PDF, Image Etc. (Word? Spreadsheets? This could get pretty intense). This needs a lot of speccing out and is probably out of scope for an initial phase. Most people's browsers will generally handle common formats (certainly JPEG/GIF, and PDF for most modern browsers)

DONE WHEN:

TBD

**Comment by weiweishi** [comment]
Related to a bigger discussion regarding evaluation and selection of viewers in Digitization phase of Jupiter. Park this for future consideration.

**Comment by weiweishi** [comment]
Closing this issue for now as we will definitely enter this conversation again in Jupiter Phase II, with more design details and requirements.
