### ISSUE TITLE
[Jupiter] Test Datacite DOI API

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/jupiter#911]
We now have a test account with Datacite, so we should test Jupiter's EZID-based DOI management against Datacite's emulation of the EZID API. When the tests are successful we can unblock #711.

It looks like [doi_service_test.rb](https://github.com/ualbertalib/jupiter/blob/c4901e866d9753f4a0f51aa45efd20f254bb0bb5/test/services/doi_service_test.rb) does all the tests we need: minting, updating, update unavailable, removal.

**Comment by pgwillia** [comment]
From https://support.datacite.org/docs/datacite-ez-api-guide#section-authentication

> Remember our accounts have basic security constraints:
> 
>     you will be allowed to register DOI names only under the prefixes that have been assigned to you
>     your DOI names can only refer to URLs under host domains you control

I'm getting "ERROR -- : EZID MintIdentifier -- error: unauthorized" I believe it's because we haven't been assigned any prefixes see https://doi.test.datacite.org/clients/cisti.ual/prefixes

@pbinkley has emailed datacite support

**Comment by pbinkley** [comment]
You should have an email forwarded by me with our assigned prefix. Let me know if it didn't get through.

**Comment by pbinkley** [comment]
Datacite account for testing is CISTI.UAL (password to be shared offline). Test prefix: 10.21967 . API end points:  https://mds.test.datacite.org or https://ez.test.datacite.org - we'll be using ez.test for our EZID API work in Dataverse and Jupiter. Support: https://support.datacite.org.

**Comment by pgwillia** [comment]
Ummm....
```
[2018-11-09T15:12:13.580231 #29747] ERROR -- : EZID MintIdentifier -- error: [facet 'enumeration'] the value 'text' is not an element of the set {'audiovisual', 'collection', 'datapaper', 'dataset', 'event', 'image', 'interactiveresource', 'model', 'physicalobject',
'service', 'software', 'sound', 'text', 'workflow', 'other'}. at line 14, column 0
```

**Comment by pbinkley** [comment]
Maybe you're supposed to use a different font in your API payload? Looks like tech@datacite.org is the next step https://support.datacite.org/docs/how-to-contact-datacite .
