### ISSUE TITLE
Embargo batch of items - request from ERA service manager

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/jupiter#934]
Pending exploration of a model for consultation for item access permissions, I would like to have all items in this collection
(https://era.library.ualberta.ca/communities/5a69bd79-86e9-4208-82d9-917c95873ed5/collections/09baae86-ac16-44f8-9cc6-a157c27e9589)

be set with an embargo date of November 28, 2028. Can this batch change be carried out?

**Comment by leahvanderjagt** [comment]
@weiweishi Not sure where the assignment goes for this task. Let me know if more information is needed.

**Comment by weiweishi** [comment]
This has now been completed:
Script used in the rails console is:
```
resp = ActiveFedora::SolrService.instance.conn.get "select", params: {q: "member_of_paths_dpsim:\"5a69bd79-86e9-4208-82d9-917c95873ed5/09baae86-ac16-44f8-9cc6-a157c27e9589\"", fl:"id", rows: 359}
result = resp["response"]["docs"]
result.each do |i|
  id = i["id"]
  Item.find(id).unlock_and_fetch_ldp_object do |t|
    t.visibility = CONTROLLED_VOCABULARIES[:visibility].embargo
    t.visibility_after_embargo = CONTROLLED_VOCABULARIES[:visibility].public
    t.embargo_end_date = "2028-11-28".to_date
    t.save! 
  end
end
```
359 items updated.
