### ISSUE TITLE
Batch ingest Loppnow

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#944]
**Brief description of the batch**
Batch ingest for Loppnow

**Manifest**
https://drive.google.com/open?id=1Jn3jJ_ZsEO1mJnxehMfEnIHzxWsR-NwkgF426A-pz7g

**Batch files**
https://drive.google.com/drive/folders/1XRXtcAhYveh-PZMUvV45TFY2WKBS8Xs9?ogsrc=32

**Additional notes**
Any additional information to add.

**Comment by weiweishi** [comment]
@dancockcroft Here are some changes needed in the batch manifest:
- label "fileName" should be "file_name"
- required field "language", "visibility" and "owner_id" was blank. owner_id should be set as "1" for all batch ingest items. 
- can we update the controlled vocabularies used in the batch ingest process, use the actual values instead of the labels used on UI. 
eg:
item_type should be one of the following:
book
chapter
conference_poster
conference_paper
dataset
image
article
article
learning_object
report
research_material
review

language should be one of the following:

english
french
spanish
chinese
german
italian
russian
ukrainian
japanese
no_linguistic_content
other

license should be one of the following:

attribution_noncommercial_4_0_international
attribution_4_0_international
attribution_noncommercial_noderivatives_4_0_international
attribution_noncommercial_sharealike_4_0_international
attribution_noderivatives_4_0_international
attribution_sharealike_4_0_international
cc0_1_0_universal
public_domain_mark_1_0

and visibility should be one of the following:

public
authenticated
embargo

Please let me know if you have any further question on this. tagging Leah too so she's aware the additional work needed. @leahvanderjagt

**Comment by weiweishi** [comment]
@dancockcroft @ERAHelp  Additional question: the file names used for the items on this batch, doesn't match with the PDF files in the batch folder. Could you please check into this?

Thank you!

**Comment by weiweishi** [comment]
Thank you for all the changes: @dancockcroft 
re: your question on "visibility" - I think the investigation sheet should pass that information into the batch manifest (No.6 on your list) 

I'm a little hesitant to say that the default should be "public", as we definitely don't want to make items that should be embargoed public - I'd rather this to be blank, and validation will fail if the visibility is not set, and we can intervene manually.

**Comment by dancockcroft** [comment]
@weiweishi Would you like to add a 'visibility' column to the investigation sheet? I think if I add it to the very end it shouldn't throw too much off.

**Comment by dancockcroft** [comment]
@weiweishi RE: your additional question: I added the wrong files to the folder, not sure why! Fixed.

**Comment by weiweishi** [comment]
@dancockcroft sure. Adding a "visibility" column to the investigation sheet will probably help ensuring this information is available for the batch ingest.

**Comment by dancockcroft** [comment]
Additional items/files added.

**Comment by dancockcroft** [comment]
Author sending postprints, batch not ready for now.

**Comment by dancockcroft** [comment]
@weiweishi All errors fixed, should be good to go.

**Comment by dancockcroft** [comment]
Manually deposited.
