### ISSUE TITLE
Batch ingest WujastykPostprints

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#948]
**Brief description of the batch**
Batch of Wujastyk postprints.

**Manifest**
https://docs.google.com/spreadsheets/d/1aSkJAtIoZILOCGD3CCpEbzwAO8h9dt6yCkzuILyLvF8/edit#gid=1874714861

**Batch files**
https://drive.google.com/drive/folders/1SGBpgXCPSq_OMqg_7744iAbY7QwlZXbo?ogsrc=32

**Additional notes**
Older batch, updated to match new manifest template.

**Comment by dancockcroft** [comment]
Updated as per #944

**Comment by dancockcroft** [comment]
@weiweishi No errors during testing. Should be good to go.

**Comment by weiweishi** [comment]
Thanks @dancockcroft for the testing, and the report is here: (it's a comma delimited file, but github doesn't support the upload of the csv file)
[2019_03_21_21_42_15.txt](https://github.com/ualbertalib/jupiter/files/2994088/2019_03_21_21_42_15.txt)

**Comment by weiweishi** [comment]
Closing the issue for now - @dancockcroft if you see any error, please feel free to reopen the issue.
