### ISSUE TITLE
Fix less issue with docker setup and rails console

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#963]
@ConnorSheremeta  noticed an issue with `pry-rails` when running the console in a full docker setup. This is a result of us using alpine linux for the Dockerfile which doesn't come with `less`

https://github.com/pry/pry/issues/1494

Looks like this can easily be solved by adding `less` as a package:

`apk --update add less`

**Comment by mbarnett** [comment]
We're no longer really recommending anyone run Rails directly in the container, right? We can close this?

**Comment by murny** [comment]
Yep if your doing Development work we recommend using the normal docker-compose.yml instead of the docker-compose.demo.yml (which should be used for just Demoing, quickly checking out the app for non developers)

Will close this.
