### ISSUE TITLE
Batch ingest TRIA2019

### ISSUE THREAD

**Issue by dancockcroft** [ualbertalib/jupiter#967]
**Brief description of the batch**
Follow-up on older investigation. 

**Manifest**
https://docs.google.com/spreadsheets/d/1lRjJ65x1X-U6xzQWqF4dcsAV2L157QJjtKYTup5AuN8/edit#gid=0
**Batch files**
https://drive.google.com/drive/folders/1eGmvvSQDG7NwjsiGU3UsTaskNIg5vU2U?ogsrc=32

**Comment by dancockcroft** [comment]
3 items added.

**Comment by dancockcroft** [comment]
@weiweishi No errors during testing. Should be good to go.

**Comment by weiweishi** [comment]
Report is available here. Feel free to reopen the issue if there's any problem. 

[2019_03_21_21_54_07.txt](https://github.com/ualbertalib/jupiter/files/2994106/2019_03_21_21_54_07.txt)

**Comment by dancockcroft** [comment]
Original investigator did not input uniform author names. The manifest has been updated, not sure if it would be faster to manually edit the item. I should have spotted this the first time, sorry about that!

**Comment by dancockcroft** [comment]
Two licenses ported to 4.0 as per Leah.

**Comment by dancockcroft** [comment]
Manually completed.
