### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#97]
(At this point I'm not 100% sure there's any UI/UX work we need to do around this...)

**Comment by mbarnett** [comment]
Chatted with Sonya (and Leah?) a couple of weeks ago, and we don't think there's anything that needs to be done in terms of specific work for an authorization sprint, other than possibly tweaking the wording of that button

**Comment by murny** [comment]
The  "Sign in with University of Alberta CCID (Campus Computing ID)" button on the `login` page? Did they like this page itself? Could we move it into a modal instead or something? etc?

**Comment by mbarnett** [comment]
Yeah. My impression was that they were fine with it as is, although if you've got a better idea I'm sure they're open to it.

**Comment by weiweishi** [comment]
Close the ticket as it seems we are okay with the current design/layout. @leahvanderjagt 
@sfbetz please reopen the ticket if there's anything needs to be done.

**Comment by sfbetz** [comment]
It looks good to me. Minor change: 
-remove the line that says : "ERA is now a CCID enabled service .... please use it to login"
-add beneath the button "If you do not have a CCID please contact us at erahelp@ualberta.ca"

**Comment by sfbetz** [comment]
NEW PLAN: Leah says we don't need a separate login page, and the login link can go directly to CCID login.
