### ISSUE TITLE
[jupiter]refactor sitemap to pull file level metadata from activestorage. 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#972]
With file data stored in ActiveStorage the workaround below is not required:

https://github.com/ualbertalib/jupiter/blob/add9c58c6b8c9642931a2e58e296c8ce3bd923c6/app/models/file_set.rb#L9

https://github.com/ualbertalib/jupiter/blob/add9c58c6b8c9642931a2e58e296c8ce3bd923c6/config/terms.yml#L42

and

https://github.com/ualbertalib/jupiter/blob/04b317ad20ce6237fa395bb3a36c615bee24699d/app/jobs/file_attachment_ingestion_job.rb#L48-L55

Furthermore with ResourceSync out this is not even being used currently.

**Comment by mbarnett** [comment]
No longer relevant to the way sitemap is generated
