### ISSUE TITLE
Rails 6 upgrade

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#975]
Although [Rails 6](https://edgeguides.rubyonrails.org/6_0_release_notes.html) has not been released yet, there are some refactoring work/new features we'd like to keep track as part of the Rails 6 upgrade.  This epic is to ensure we don't lose track of these related issues, when we plan our Rails 6 upgrade.

**Comment by murny** [comment]
Duplicated by #1287  . Closing this issue out
