### ISSUE TITLE
Jupiter Refactoring

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#976]
This is to track the potential issues related to the refactoring work to remove Fedora/ActiveFedora and Solrizer from our stack, if the decision from the metadata/object datastore is to remove Fedora from the web application.  The refactoring work is also captured in the document here: https://github.com/ualbertalib/jupiter/blob/master/docs/jupiter_phase_2.md

**Comment by mbarnett** [comment]
Happily, we did this!
