### ISSUE TITLE
View and download summary table request

### ISSUE THREAD

**Issue by leahvanderjagt** [ualbertalib/jupiter#979]
Hi there:

I need a spreadsheet/csv file with these fields:

community
collection 
item name 
uuid
number of views
number of downloads

This is a little bit urgent (I think I need this w/in a week). Can this be done?

**Comment by murny** [comment]
Some pseudocode might look like this (assuming ActiveFedora works like ActiveRecord...which it doesn't...so your millage may vary here):

```ruby

data = []

Community.all.each do |community|
  row = [community.name]
  community.collections.each do |collection|
    row << collection.name
    collection.items.each do |item|
      row << item.id
      views, downloads = Statistics.for(item_id: item.id)
      row << views
      row << downloads
    end
  end
  data << row
end

puts data.to_csv
```

Essentially just looping over all communities, and for each community list all of its collections and for each collection list all its items. Then outputting everything out as a CSV format

**Comment by pbinkley** [comment]
Lovely, thanks! It turns out I can't run the rails console on kimberley any more, no doubt invoking it wrong in that environment - I'll clear that up with Weiwei and try this out.

**Comment by pbinkley** [comment]
Thanks! I ended up with this:

```
require 'csv'

data = ''

Community.all.each do |community|
  community.member_collections.each do |collection|
    collection.member_objects.each do |item|
      row = [community.title, collection.title]
      row << item.title
      row << item.id
      row << item.visibility
      views, downloads = Statistics.for(item_id: item.id)
      row << views
      row << downloads
      data << row.to_csv
    end
  end
end

File.write ('/tmp/leahstats.csv', data)
```

I've sent Leah the csv.
