### ISSUE TITLE
Batch Ingest FliegelUpdate

### ISSUE THREAD

**Issue by mmstang** [ualbertalib/jupiter#981]
**Brief description of the batch**
Update of older, incomplete investigation. Reformatted to meet new manifest specifications.

**Manifest**
https://docs.google.com/spreadsheets/d/1-XEfGv807-cwEgykNEl7aNPhAmR-D49yh6wFiQVdVV0/edit#gid=0

**Batch files**
https://drive.google.com/drive/folders/1PKvS53zZmePTidr6TCg2NJ8Z1LJJ4-gX?ogsrc=32

**Comment by dancockcroft** [comment]
@weiweishi Looks ready for ingest.

**Comment by dancockcroft** [comment]
One license ported to 4.0.

**Comment by dancockcroft** [comment]
Manually deposited.
