### ISSUE TITLE
[Jupiter] Refactor thumbnail generation code

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#983]
Noticed this when working on this issue: #982. 

Some refactors could be had here. We basically got 5 places where thumbnail generation happens (communities, items, theses, draft items and draft theses). Some are done in the model, others done in the view. Lots of repeated code across the application.

These two views for example are exactly the same:
https://github.com/ualbertalib/jupiter/blob/c88f89cabb034deac19f0872c1d41e4d2ea4103b/app/views/admin/theses/draft/_thumbnail.html.erb
https://github.com/ualbertalib/jupiter/blob/c88f89cabb034deac19f0872c1d41e4d2ea4103b/app/views/items/draft/_thumbnail.html.erb

These code blocks are pretty similar:

https://github.com/ualbertalib/jupiter/blob/c88f89cabb034deac19f0872c1d41e4d2ea4103b/app/models/community.rb#L32-L37
https://github.com/ualbertalib/jupiter/blob/c88f89cabb034deac19f0872c1d41e4d2ea4103b/app/models/concerns/draft_properties.rb#L48-L59
https://github.com/ualbertalib/jupiter/blob/c88f89cabb034deac19f0872c1d41e4d2ea4103b/app/models/concerns/item_properties.rb#L62-L73

Be nice if we could DRY up a lot of this duplicated code (maybe move it into a concern/helper etc?). Or just reevaluating what this code does and why we need it in the model etc? Maybe we can all share the same thumbnail partial everywhere?

**Comment by mbarnett** [comment]
Think this is now being tracked on #1343
