### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#99]
Updated (Nov. 10)

To-do:
- [x] search result with more information returned for each item #244 
- [x] facet with Community/Collection pair (wireframe needs to be updated)

TODO:

Key Decisions:

- Facets behave as `AND`ing logic, which means filters are always narrowing down results. Also only can choose one filter per facet (as choosing two makes no sense as this would return zero results)
- Facets should show 6 filters per facet, with a "More" button
- Show items, communties and collections on search results (split them in tabs or something (kinda like github)? So we can control each section accordingly (have facets/sorts/etc that makes sense for each))

Unknowns:
- Default sort is by Most Recent when no search? (what is the date field determing most recent? I think its the forms date created field right? or is it the item deposit upload date (like when the user actually uploaded the item)? Otherwise "Relevance" when a search is given

Mockup:
![Image of Search Mockup](https://jupiter.mybalsamiq.com/mockups/6086062.png)
https://jupiter.mybalsamiq.com/projects/jupiter/Search

**Comment by sfbetz** [comment]
Wireframes here: https://jupiter.mybalsamiq.com/mockups/6086062.png
